### ISSUE TITLE
Remove all volumes when shutting down

### ISSUE THREAD

**Issue by nick-lehmann** [containers/podman-compose#105]
`docker-compose` offers to possibility to remove all volumes used by your services by appending the `-v` option to the `down` command. It is very useful to me in my daily work and unfortunately it seems to be missing in `podman-compose`.

Is there a good reason why this option should not be added? Otherwise, I would simply add it myself and open a PR 👍

**Comment by lcarva** [comment]
I have a PR for this in https://github.com/containers/podman-compose/pull/214

Not sure how to get a review on it.

**Comment by nick-lehmann** [comment]
@lcarva Thank you very much! I can't help you to get it reviewed besides upvoting it...

**Comment by bam80** [comment]
Hmm, doesn't quite work for me: #377

**Comment by muayyad-alsadi** [comment]
@bam80 I've just fixed it.

**Comment by bam80** [comment]
Thank you. I'm thinking how to get your fix, I was installed stable version..

**Comment by muayyad-alsadi** [comment]
@bam80 it's pushed 1.0.3 to pypi

https://pypi.org/project/podman-compose/

you can just `pip3 install podman-compose`
you can add `--user` if you like

you can always install from github too

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by bam80** [comment]
@muayyad-alsadi Thank you!

Tried the fix, it seems somewhat problematic, still:
#378
