### ISSUE TITLE
Missing `config` command

### ISSUE THREAD

**Issue by yajo** [containers/podman-compose#106]
To debug your `docker-compose.yml` file it's very useful the `docker-compose config` command, which outputs the final configuration that gets used by docker-compose, including all merges, variable expansions, etc.

podman-compose is missing that subcommand.

**Comment by pleonex** [comment]
This is also required to make it work with VS Code Remote Container extensions. It tries to run this command (after symlink to podman-compose):

```
docker-compose -f /myrepo/.devcontainer/docker-compose.yml config --services
```

**Comment by mabulgu** [comment]
Hi. Is someone working on this issue? If not, I would love to start working on this.
