### ISSUE TITLE
Refactor to be called as an interface implementation from docker-compose

### ISSUE THREAD

**Issue by westurner** [containers/podman-compose#126]
See: "Support podman as a backend"
https://github.com/docker/compose/issues/7292

Could docker-compose call into podman-compose if a CLI arg or an environment variable is passed (and appropriate abstractions in docker-compose are implemented)?

```bash
DOCKER_COMPOSE_DRIVER=podman
docker-compose --driver=podman
```

**Comment by muayyad-alsadi** [comment]
As far as I know docker-compose talks to a daemon not a cli

https://github.com/docker/compose/blob/master/compose/cli/docker_client.py

And it does not do mapping to fix user-space limitations.

**Comment by westurner** [comment]
Docker compose works by interacting with the docker socket. Factoring out
an interface and a compose implementation for each of those messages to the
socket would make it possible to write an implemention that instead calls
podman.

Would you be open to a patch that adds something like an adapter facade
(which would implement that interface and call into podman-compose?

There needn't be multiple docker-compose.yml parser implementations.

**Comment by manics** [comment]
FYI the Podman `apiv2` aims to be compatible with the docker API https://podman.io/blogs/2020/01/17/podman-new-api.html

**Comment by westurner** [comment]
Thanks, hadn't seen the mostly-docker-compatible HTTP apiv2: /swagger :
https://github.com/containers/libpod/blob/master/pkg/api/server/swagger.go

Docker-compose.yml v3 services do not require swarm mode (which podman
doesn't support), but there's otherwise no easy/built-in zero-downtime way
to do rolling or blue-green deployments without swarm or k3s/k8s?

https://docs.docker.com/compose/compose-file/

**Comment by westurner** [comment]
"Announcing the Compose Specification"
https://www.docker.com/blog/announcing-the-compose-specification/

- https://www.compose-spec.io/
- https://github.com/compose-spec/compose-spec/
- "Call for maintainers"
  https://github.com/compose-spec/compose-spec/issues/57
