### ISSUE TITLE
volumes directories not created

### ISSUE THREAD

**Issue by pruje** [containers/podman-compose#175]
Sorry if this has already been reported. I didn't find it in issues.

When using volumes like:
```yml
  volumes:
     - ./volumes/dir:/path/to/volume
```
if the local directory `volumes/dir` does not exists, podman returns an error.
I'm running in root, so it's not a permission problem.

With docker-compose, every volume directories and subdirectories are automatically created if not exists.
This missing feature is very annoying when using complex compose files with tons of volumes, because I need to make `mkdir -p ...` for each volume.

I would be very happy if you can implement it. Thanks!

**Comment by muayyad-alsadi** [comment]
In the case of docker, it's docker not docker-compose that creates them. If I understand it well, podman not podman compose should create them.

**Comment by pruje** [comment]
Indeed. A long time ago I thought that it worked on docker-compose but not in docker, but you're right. I will create an issue to the podman project. Thanks for the response.
