### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by bhanukumar22** [containers/podman-compose#187]
Hello,

I have installed the latest version of podman-compose.
Have entered all values in docker-compose.yml and ran below command. 

python /usr/local/lib/python3.6/site-packages/podman_compose.py -f ./docker-compose.yaml up

File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 882
    **args.__dict__,
                   ^
SyntaxError: invalid syntax

Getting the above error. Please check and help me to see if there is any issue.

Thanks in advance

**Comment by bhanukumar22** [comment]
No response or help!
Dropped the plan of using podman-compose. Was able to bring up the container using podman run

**Comment by muayyad-alsadi** [comment]
please use latest podman-compose devel branch using python 3

most likely you are using python or non-latest branch.
