### ISSUE TITLE
Console not working correctly after down command

### ISSUE THREAD

**Issue by DanBmh** [containers/podman-compose#188]
I'm glad you could solve the lost process after stopping the containers recently with #186, but my console terminal is still not working correctly afterwards.

I can see my terminal prompt again, but not the commands I'm typing. They still get written, but aren't visible. 
Pressing enter only multiple times, results in my terminal path getting printed one after another and not with a new line inbetween, like normally.

Currently my workaround is to open a new terminal tab and close the old, but i think this will be more time consuming if you have a ssh session and have to login each time again.

I'm starting the containers with: `podman-compose -f my-compose.yml -t identity up` and the containers have the `tty:true` flag but not the `stdin_open: true` flag, if this is important.

**Comment by muayyad-alsadi** [comment]
I guess typing `reset` and hit enter would resolve your problem.

**Comment by DanBmh** [comment]
Thanks, this is better than my solution.
