### ISSUE TITLE
seccomp:unconfined supported?

### ISSUE THREAD

**Issue by markstos** [containers/podman-compose#199]
I'm trying to use this in my service definition:

```
security_opt:
      - seccomp:unconfined
```

I can error about this with podman-compose:

```
Error: invalid --security-opt 1: "seccomp:unconfined"
```
Is my syntax wrong or this an unimplemented feature of `podman-compose`?

**Comment by markstos** [comment]
I was able to get the container to start when using `podman` directly with the syntax of `--security-opt seccomp=unconfirmed`.

However, the YAML I gave above is what's correct when using docker-compose.yml with `docker`. So it appears this tool needs to translate the YAML above to `--security-opt seccomp=unconfirmed`

**Comment by Darrenmeehan** [comment]
I believe I've hit this issue when attempting to use https://github.com/photoprism/photoprism

**Comment by markstos** [comment]
@Darrenmeehan To help move this along, you could do your own peer review by testing the patch I've submitted and confirming whether it works or not in your environment.

**Comment by Darrenmeehan** [comment]
I've confirmed this much works. I ran into some other issues with securityopts, which I'd be willing to fix. I would like to see some feedback from maintainers on this change before I commit time to doing this.

**Comment by therhenals** [comment]
Error: invalid --security-opt 1: "apparmor:unconfined"

**Comment by muayyad-alsadi** [comment]
@therhenals what is your version?

**Comment by muayyad-alsadi** [comment]
this is fixed for both `seccomp:unconfined` and `apparmor:unconfined`
please test

**Comment by FallingSnow** [comment]
I'm running into this issue as well.
```
$ podman --version
podman version 3.4.7
```
```
ERROR: for netdata  Cannot create container for service netdata: fill out specgen: invalid --security-opt 1: "apparmor:unconfined"

ERROR: for netdata  Cannot create container for service netdata: fill out specgen: invalid --security-opt 1: "apparmor:unconfined"
```

**Comment by markstos** [comment]
@FallingSnow Your command used docker-compose, but this the issue tracker for podman-compose, which is a separate project.

**Comment by FallingSnow** [comment]
I updated podman and installed podman-compose and tried that. Seems it works now. Thank you!
