### ISSUE TITLE
Containers not Communicating

### ISSUE THREAD

**Issue by jasi110** [containers/podman-compose#202]
I have a docker-compose.yml that brings up three zookeeper instances, and three Solr instances to create a SolrCloud (cluster).  The zookeepers all use port 2181, 2888, and 3888, and the solrs all use port 8983.  Using podman-compose with no options fails to run the second and third of each since the "Address is already in use".  Using "-t publishall" or "-t identity" fail with the containers not being able to communicate with each other, or not being able to find the network.

How can this be accomplished with podman-compose or is it unsupported?
Thanks.

**Comment by muayyad-alsadi** [comment]
Identity requires root
And others would fail unless you adjust the port

Typically there is -d somthing you could pass to solr/zk to customize the ports.

**Comment by jasi110** [comment]
Ok.  I tried using identity under sudo and that still had problems.  Wouldn't having to change all the ports to be unique a strike against using Podman?  By having the ports match, it's as if you have different machines for each container like real world failover.  I'm just thinking that this could be an issue for those migrating from docker-compose to podman-compose.
Have there been any thoughts about how to do it or is it not possible?

**Comment by muayyad-alsadi** [comment]
If you use sudo it should work without changing ports.

Why it's needed for rootless? because of slirp4netns.

You need root to create veth and configure network and adjust routing tables ...etc.


https://github.com/rootless-containers/slirp4netns/issues/172

**Comment by jasi110** [comment]
Ok.  Thanks.
