### ISSUE TITLE
add build --no-cache

### ISSUE THREAD

**Issue by maweki** [containers/podman-compose#205]
I haven't found a way to force redo a `podman-compose build` where I have changed some data but not the actual Dockerfile. The only way I found was removing all images via `podman rmi --all`.

`docker-compose` offers a `--no-cache` option for that.

**Comment by zdyxry** [comment]
This option is already supported in this PR ： https://github.com/containers/podman-compose/pull/157

**Comment by joe733** [comment]
Voting to `close` issue.
