### ISSUE TITLE
Cannot set port to 8181.

### ISSUE THREAD

**Issue by pvanthony** [containers/podman-compose#225]
Please bear with me. This most likely be my setting problem. I am just not able to get this docker-compose to port 8181. It always defaults to port 80 even after I change it to 8181.

So when I run as root it works because port 80 is allowed as root. When I run it as user called xibo, it is trying to get port 80 but it is not allowed. I would like it to be 8181.

What am I doing wrong?

Got the docker file from here.
https://xibo.org.uk/docs/setup/xibo-for-docker-on-linux

Unfortunately xibo developers do no support podman currently.

Any advice would be great.

Here is the docker-compose.
version: "2.1"

services:
    cms-db:
        image: mysql:5.6
        volumes:
            - "./shared/db:/var/lib/mysql:Z"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
    cms-xmr:
        image: xibosignage/xibo-xmr:release-0.8
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: config.env
    cms-web:
        image: xibosignage/xibo-cms:release-2.3.6
        volumes:
            - "./shared/cms/custom:/var/www/cms/custom:Z"
            - "./shared/backup:/var/www/backup:Z"
            - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom:Z"
            - "./shared/cms/library:/var/www/cms/library:Z"
            - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts:Z"
            - "./shared/cms/ca-certs:/var/www/cms/ca-certs:Z"
        restart: always
        links:
            - cms-db:mysql
            - cms-xmr:50001
        environment:
            - XMR_HOST=cms-xmr
        env_file: config.env
        ports:
            - "8181:8181" <-- this was 80:80
        mem_limit: 1g
    cms-quickchart:
      image: ianw/quickchart
      restart: always

**Comment by FedericoAntoniazzi** [comment]
Are you sure that port 8181 is not being used by others containers?
Sometimes happens that you forget containers in stop state or kill and they keep "using" the port 8181

**Comment by muayyad-alsadi** [comment]
you can verify that using `netstat -tnlp | grep 8181`
