### ISSUE TITLE
podman-compose fails because of inspect change

### ISSUE THREAD

**Issue by joequant** [containers/podman-compose#232]
My podman-compose has started to fail because it cannot parse the the volume inspect.  The key "mountPoint" has changed to "Mountpoint" which causes podman-compose to fail.

**Comment by coffeemakr** [comment]
I had the same issue, when I installed podman-compose from PyPI, but it is fixed in the current development version.
```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by Himura2la** [comment]
Have the same issue. That's sad that this software is in so early state, I hope I can replace docker with podman already, but having such issues makes this impossible..

**Comment by muayyad-alsadi** [comment]
@Himura2la  please use the devel branch using the pip command above. I'm planning to do a pip release but I did not have enough time to walk over all tests.

**Comment by Himura2la** [comment]
I did. By the way, I just found out that Podman natively supports docker-compose now (https://www.redhat.com/sysadmin/podman-docker-compose), so maybe this should be in README?
