### ISSUE TITLE
adding and dropping capabilities doesn't work

### ISSUE THREAD

**Issue by n1trux** [containers/podman-compose#239]
Adding capabilities with `cap_add` or `cap_drop` doesn't work.

>## cap_add, cap_drop
>
>Add or drop container capabilities. See `man 7 capabilities` for a full list.
>
>```
>cap_add:
>  - ALL
>
>cap_drop:
>  - NET_ADMIN
>  - SYS_ADMIN
>```

([Relevant Docker Compose docs](https://docs.docker.com/compose/compose-file/#cap_add-cap_drop))

`podman run` has the following options to add capabilities:

```
–cap-add=capability

Add Linux capabilities.

–cap-drop=capability

Drop Linux capabilities.
```

([relevant podman run docs](http://docs.podman.io/en/latest/markdown/podman-run.1.html#options))

Weirdly enough, they seem to be supported: https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L528-L531

**Comment by muayyad-alsadi** [comment]
Could this be related to not being run as root?

Would passing those things to rootless podman  work?

**Comment by n1trux** [comment]
hm yeah, running as root doesn't work with SELinux enabled either. If I setenforce 0, it works as root, but not as user. I can't drop capabilities the user has in their cgroup, so I'm a bit lost how to debug this.

**Comment by SEIAROTg** [comment]
I had the same problem.

I found the support for `cap_add` was added in e8147e3 (Apr 2020) while there hadn't been a single release onto PyPI between Sep 2019 and Nov 2021. Running `pip install --upgrade podman-compose` fixed this for me.

https://pypi.org/project/podman-compose/#history
