### ISSUE TITLE
No container with name or ID app found

### ISSUE THREAD

**Issue by ewinge** [containers/podman-compose#248]
I'm trying to run this application, which was written for docker-compose:

https://github.com/uts-cic/acawriter

It seems to build, but ends up with the following error:

	$ podman-compose up -d
	[...]
	Trying to pull registry.access.redhat.com/app...
	  name unknown: Repo not found
	Trying to pull registry.redhat.io/app...
	[...]

	125
	podman start app
	Error: unable to find container app: no container with name or ID app found: no such container
	125
	$

**Comment by muayyad-alsadi** [comment]
Try build before up

**Comment by ewinge** [comment]
Thanks, the build fails:

	In PackageManifest.php line 131:
							 
	  Undefined index: name  					 

	Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
	Error: error building at STEP "RUN composer install --no-cache": error while running runtime: exit status 1
	125

I guess this probably isn't an issue with podman-compose, however the application does work with docker.

**Comment by gnubyte** [comment]
Tacking on for anyone that finds this in a related search on duckduckgo/google:
if you are seeing this message `Error: no container with name or ID "<your service name>" found: no such container`. Podman by default searches quay.io, a redhat image repo for images to pull. If you want to use docker's image repo, you have to specify it.
try prefixing the `image` with `docker.io/<user>/<name-of-image>`

For example:
```
  redis:
    restart: always
    image: docker.io/redis
```
