### ISSUE TITLE
support CLI variables COMPOSE_PROJECT_NAME and COMPOSE_FILE

### ISSUE THREAD

**Issue by lutostag** [containers/podman-compose#249]
Hey there,

First off wanted to say what a nice great project you all are working on here. I was able to run rootless containers without having to change my compose files at all and get up and working! :guitar: :notes: 

Anyways, I was hoping to be able to use the same environment variables as specified by https://docs.docker.com/compose/env-file/#compose-file-and-cli-variables

The list is here (strikethrough'd ones that probably do not make much sense for podman):
* `COMPOSE_API_VERSION`
* ~`COMPOSE_CONVERT_WINDOWS_PATHS`~
* `COMPOSE_FILE`
* ~`COMPOSE_HTTP_TIMEOUT`~
* ~`COMPOSE_TLS_VERSION`~
* `COMPOSE_PROJECT_NAME`
* ~`DOCKER_CERT_PATH`~
* ~`DOCKER_HOST`~
* ~`DOCKER_TLS_VERIFY`~

I have at least used `COMPOSE_FILE` and `COMPOSE_PROJECT_NAME` a bit in some makefiles in current projects.

I am able to add support for those two in a PR, if that would be helpful to anyone else.

(Note that I do not need to load from the `.env` file exactly in my case, just having the defaults set from those env variables would be sufficient for my usecase).

Open to any feedback on the idea before offering a PR :smile_cat: 

Thanks again.

**Comment by muayyad-alsadi** [comment]
please confirm that it works now.

**Comment by muayyad-alsadi** [comment]
sorry, I did not see that you offered a PR. but there is a TODO, you might want to work on it

```
        # TODO: should read and respect those env variables
        # see: https://docs.docker.com/compose/reference/envvars/
        # see: https://docs.docker.com/compose/env-file/
        dotenv_dict.update({
            "COMPOSE_FILE": filename,
            "COMPOSE_PROJECT_NAME": self.project_name,
            "COMPOSE_PATH_SEPARATOR": ":",
        })
```

this means that we need to replace

```
            args.file = list(filter(os.path.exists, [
                "docker-compose.yml",
                "docker-compose.yaml",
                "docker-compose.override.yml",
                "docker-compose.override.yaml",
                "container-compose.yml",
                "container-compose.yaml",
                "container-compose.override.yml",
                "container-compose.override.yaml"
            ]))
```

with something like

```
compose_file_ls = os.environ.get("COMPOSE_FILE", "docker-compose.yml:container-compose.yml").split(":")
args.file = list(filter(os.path.exists, compose_file_ls))
```

and I'm not sure how to do the `*.override.yml` thingy

**Comment by lutostag** [comment]
Hey there @muayyad-alsadi wow, that was quick! Thanks for that.

I think I might not have explained myself, because I think the code on the dev branch accomplishes something else.

I was hoping the options `COMPOSE_FILE` and `COMPOSE_PROJECT_NAME` just give us alternative ways to set the cli flags (`--file` and `--project-name` respectively).

The code above I think exposes these as variables to the docker-compose for replacement, which is helpful too!

I took a stab at it and opened up it as a PR here if that helps to explain my needs better (linked just above).

Open to feedback on it. Thanks again @muayyad-alsadi for diving right in!

**Comment by muayyad-alsadi** [comment]
the PR does not handle the `*.override.yml` feature

maybe it should be like this

```python
override_re = re.compile('(\.[^\.]*)$')
separator = os.environ.get("COMPOSE_PATH_SEPARATOR", ":")
file_default = ["docker-compose.yml", "docker-compose.yaml", "container-compose.yml", "container-compose.yaml"].join(separator)
file_from_env = os.environ.get("COMPOSE_FILE", file_default)
file_from_env_ls = file_from_env.split(separator)
file_from_env_override = [ override_re.sub(r'.override\1', f) for f in ls ]
file_from_env_w_override = file_from_env_ls + file_from_env_override
if not args.file:
    args.file = list(filter(os.path.exists, file_from_env_w_override))
```

**Comment by lutostag** [comment]
I will take a stab at it tomorrow. Thanks for pointing out how it interacts with the overrides, I missed that :+1:

**Comment by lutostag** [comment]
Hi @muayyad-alsadi, so I took a closer look at how docker-compose implements overrides and `COMPOSE_FILE`.

It seems like docker-compose will use one xor the other. If a COMPOSE_FILE is specified, override.yml files are not included unless explicltly included in the env variable.

So I think in order to follow along with docker-compose's cli, I would suggest not adding the extra functionality, suggested above.

**Comment by muayyad-alsadi** [comment]
Please push your proposal and I'll merge it.

**Comment by muayyad-alsadi** [comment]
@lutostag  any update.

**Comment by lutostag** [comment]
@muayyad-alsadi https://github.com/containers/podman-compose/pull/250 should be good to go from my point of view. Any comments would be appreciated.

**Comment by ConorSheehan1** [comment]
Can this be reopened?
looks like #250 was closed and not merged :(

**Comment by muayyad-alsadi** [comment]
how different is it from #371  ?
what is not covered there?

**Comment by ConorSheehan1** [comment]
@muayyad-alsadi `COMPOSE_PROJECT_NAME` still does not work. 
#371 only references `COMPOSE_FILE`.
This issue references both `COMPOSE_FILE` and `COMPOSE_PROJECT_NAME`.


The only workaround I've found is to explicitly pass `-p` with every `podman-compose` command https://github.com/containers/podman-compose/pull/250#issuecomment-852861020

**Comment by muayyad-alsadi** [comment]
@ConorSheehan1  please try the above push

**Comment by ConorSheehan1** [comment]
@muayyad-alsadi that worked, thanks!
