### ISSUE TITLE
single pod, multiple networks

### ISSUE THREAD

**Issue by fugkco** [containers/podman-compose#259]
Hello all,

I have a pod that has a service running that has to run on a VPN. I've been able to make this setup work and I'm able to access the service on my local network too.

The set up is:

```
podman pod create --name=mypod --share net -p 8080:8080
podman run -d --name=vpn --cap-add=NET_ADMIN --device /dev/net/tun --restart unless-stopped openvpn
podman run -d --name=myservice --restart unless-stopped myservice 
```

I've now figured out that the container `myservice` may also need a non-vpn connection. Therefore I'd like to add an additional nic to the container, that _isn't_ running over the VPN.

Is there a solution at all for this?

Failing that, I can setup a small proxy within the same pod that I can point `myservice` to. Would it be possible to ensure said proxy doesn't run over the VPN?

Note, I'm aware that I could potentially run aforementioned proxy on a separate pod, and then point myservice to the proxy pod, though I'd like to avoid that if possible.

Happy to provide additional clarifications.

Thanks

**Comment by fugkco** [comment]
Heh, so it turns out I posted this in the wrong place. Closing.

**Comment by myagues** [comment]
Hello,

I am looking for this exact configuration, did you find a way of making it work within a single pod?

**Comment by fugkco** [comment]
@myagues I didn't get it in the end, but also I didn't pursue it. If you do want to ask, you probably want to raise an issue in https://github.com/containers/podman
