### ISSUE TITLE
podman-compose pull should pull all images even those with a build section

### ISSUE THREAD

**Issue by andyrafter** [containers/podman-compose#265]
RE: https://github.com/containers/podman-compose/blob/6289d25a42cfdb5dfcac863b1b1b4ace32ce31b7/podman_compose.py#L1064

docker-compose behaviour is to try and build images when running `docker-compose up`, ignoring the image URI.
docker-compose pull will always try and pull images, regardless of build section being present. This behaviour means that

````
docker-compose pull
docker-compose up
```

will always run pre-built images if they exist and not force compose users to either manually run `docker pull` or build the images themselves.

`podman-compose pull` is filtering out any services with a build section, and I believe this is incorrect.

**Comment by g-braeunlich** [comment]
@muayyad-alsadi Would be glad if you could have a look at my MR!
Or do you see any reasons to deviate from the docker-compose implementation?

**Comment by muayyad-alsadi** [comment]
here is an old article

http://crunchtools.com/docker-pull-myfinger/

docker wants to promote their service, that's why they dismiss common sense that prefer local/private/trusted vs. remote/public/untrusted

there are many hacks that was successful because of npm preferred remote/public/untrusted vs. local/private/trusted.
here is a good article about it

https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

what do you think?

**Comment by g-braeunlich** [comment]
Yes, it is true, that images we pull are compromised.
But this is a problem with pull in general and this case (having both image and build at once) is in my opinion totally different:
Normally, if you have both image and build, you are pushing yourself to the registry in question.
In our case, we are building our images via CI and pushing them to a private registry (specified by the image section).
We dont want to build again on the target host.

And in the current implementation there is no way to pull images with a build section.

**Comment by muayyad-alsadi** [comment]
Should we add an option for this? --pull-builds?

**Comment by g-braeunlich** [comment]
Again: please correct my, if I miss something. But do you see any additional risk by just following the docker-compose way?
If you dont want to pull, then you would have the possibility to do a
`podman-compose build` first.
Therefore, from a user perspective, I cannot imagine a usecase, where you dont want to pull all images (also those with build), if you explicitly called `podman-compose pull`.
But maybe I am wrong.

**Comment by muayyad-alsadi** [comment]
I have personal compose that have build and image (because I want to rmi)
That are not part of any registry (not even private)

I don't want to pull public images with that name.

**Comment by g-braeunlich** [comment]
Ah. Yes, thats a valid usecase, I did not think about. What about only pulling prefixed images and add the option, you proposed additionally?

Am 5. August 2021 12:25:56 MESZ schrieb Muayyad Alsadi ***@***.***>:

**Comment by muayyad-alsadi** [comment]
Update your pull request and I'll merge it.

**Comment by g-braeunlich** [comment]
I updated the commit. Some comments:
* I also took care of images prefixed with `localhost/`
* I also took care of the following situation
```yml
services:
   a:
     image: a
     build: ...
   b:
     image: a
```
