### ISSUE TITLE
New release from podman-compose

### ISSUE THREAD

**Issue by Syntax3rror404** [containers/podman-compose#270]
When is there a new release? The current one is now very old I think

**Comment by NicolasCARPi** [comment]
See current discussion about the activity of this project: https://github.com/containers/podman-compose/issues/276 (hint: it's low)

**Comment by rhatdan** [comment]
We need new maintainers to step up.

**Comment by dannyhpy** [comment]
I think we also need to know what features/bugfixes are necessary in order to make a release

**Comment by abitrolly** [comment]
There are quite a lot of changes since 0.1.7dev to bump it to 01.8dev

https://github.com/containers/podman-compose/compare/efcbc75f631e693791a7f71abc49d9d05559ae92...devel#diff-956dd8b5765533c7e8f5bb94c8a1b4735dfcfd9cff54829f3494b87460fab50bR37

**Comment by muayyad-alsadi** [comment]
I've just released `v0.1.10` and `v1.0.2`
