### ISSUE TITLE
[Question] Is there a way to provide podman `--net / --network` options?

### ISSUE THREAD

**Issue by aanno** [containers/podman-compose#283]
Is there a way to provide podman `--net / --network` options?

I would like the have an podman-compose equivalent of 

```
podman run --net slirp4netns:allow_host_loopback=true,enable_ipv6=true --env HTTP_PORT=8081 --env HTTPS_PORT=8082 -p 8081:8081 -p 8082:8082 -d praqma/network-multitool
```

But the `--net slirp4netns:allow_host_loopback=true,enable_ipv6=true` part is delicate. Is there a way to archive this? What about other podman-specific options?

Kind regards,

aanno

**Comment by muayyad-alsadi** [comment]
try latest devel branch with 

```
podman-compose -t identity --podman-run-args='--net slirp4netns:allow_host_loopback=true,enable_ipv6=true' up
```

**Comment by aanno** [comment]
Thank you for making this possible! At present I use it for circumventing the problem that podman-compose does not support external networks at present.
