### ISSUE TITLE
How do I set log-level when using podman-compose

### ISSUE THREAD

**Issue by mnsmithuk** [containers/podman-compose#284]
Hi,

When using podman, i can do podman --log-level=error  to set the log-level.

How do I set the log-level when running containers using podman-compose ?

**Comment by Xantios** [comment]
Hi,

How about something along the lines of:
`podman-compose --podman-args="--log-level info" up`

Have a good one!

**Comment by muayyad-alsadi** [comment]
Does this answer your question?

**Comment by mnsmithuk** [comment]
Yes it did, thank you.  Appoligies I thought I had already responded to this.

**Comment by shreyas** [comment]
anyone looking for this in 2025, the syntax has apparently changed. here's what worked for me on ubuntu 25.04 LTS - 

`podman-compose --podman-args '--log-level=info' ...`
