### ISSUE TITLE
Podman run log-driver option

### ISSUE THREAD

**Issue by jd-daniels** [containers/podman-compose#297]
I can't seem to find a way to pass --log-driver to the podman-compose call to podman via podman up. Is this supported?

From podman-run man page:

   --log-driver="driver"
       Logging driver for the container. Currently available options are k8s-file, journald, and none, with json-file aliased to k8s-file for scripting compatibility.

Thanks!

**Comment by muayyad-alsadi** [comment]
I guess this can be solved with this proposal


https://github.com/containers/podman-compose/issues/278

**Comment by muayyad-alsadi** [comment]
please test

**Comment by jd-daniels** [comment]
This won't quite work for log-driver because podman-compose seems to call podman pod and podman start, not just podman run, the other two don't have a log-driver option.

Example:
[]$ podman-compose --podman-args="--log-driver=journald" up -d
['podman', '--version', '']
using podman version: podman version 2.2.1
podman pod --log-driver=journald create --name=deploy --share net -p 8443:8443 -p 443:8443
Error: unknown flag: --log-driver
125
<podman run redact>
Error: error retrieving pod deploy: no pod with name or ID deploy found: no such pod
125
podman start --log-driver=journald deploy_idp_1
Error: unknown flag: --log-driver
125

**Comment by g-braeunlich** [comment]
Any update on this?

**Comment by muayyad-alsadi** [comment]
Use --podman-<COMMAND>-args

**Comment by g-braeunlich** [comment]
What about respecting the `logging` config for services as referenced [here](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging)?
There are not many options to choose from currently for the driver:
* `k8s-file`
* `journald`
* `none`
Same for the dirver options:
* `path`
* `max-size`
* `tag` (journald only)

If you want, I could create a PR.

**Comment by muayyad-alsadi** [comment]
Yes please
