### ISSUE TITLE
Variable substituion not fully supported

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#302]
Docker-compose has variable substitution support:
https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution

However, I e.g. tried to start a Redis container with a password:
```yml
version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: always
    networks:
      - redisnet
    expose:
      - 6379
    env_file:
      - redis.env
 ```
 
 `redis.env` being:
 ```
 REDIS_HOST_PASSWORD=password-here
 ```

**Result:** It did not replace the `REDIS_HOST_PASSWORD` variable correctly.

It failed like this:
```
podman start -a nextcloud_redis_1

*** FATAL CONFIG FILE ERROR (Redis 6.2.3) ***
Reading the configuration file, at line 2
>>> 'requirepass'
wrong number of arguments
1
```

---

Having learned that I tried another documented method (see the already given link to the spec):
> `${VARIABLE:?err}` exits with an error message containing err if `VARIABLE` is unset or empty in the environment.

I.e. like this:
```yml
version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD:?err}
    restart: always
    networks:
      - redisnet
    expose:
      - 6379
    env_file:
      - redis.env
```

However, that also fails:
```
$ podman-compose […] up
using podman version: podman version 3.1.2
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==0.1.7.dev0', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1419, in main
    podman_compose.run()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 825, in run
    self._parse_compose_file()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 901, in _parse_compose_file
    content = rec_subs(content, [os.environ, dotenv_dict])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 173, in rec_subs
    value = dict([(k, rec_subs(v, dicts)) for k, v in value.items()])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 173, in <listcomp>
    value = dict([(k, rec_subs(v, dicts)) for k, v in value.items()])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 173, in rec_subs
    value = dict([(k, rec_subs(v, dicts)) for k, v in value.items()])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 173, in <listcomp>
    value = dict([(k, rec_subs(v, dicts)) for k, v in value.items()])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 173, in rec_subs
    value = dict([(k, rec_subs(v, dicts)) for k, v in value.items()])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 173, in <listcomp>
    value = dict([(k, rec_subs(v, dicts)) for k, v in value.items()])
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 180, in rec_subs
    value = var_err_re.sub(sub_err, value)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 178, in <lambda>
    sub_err = lambda m: dicts_get(dicts, m.group(1), RuntimeError(m.group(3)),
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 165, in dicts_get
    raise value
RuntimeError: err
```

**Note:** Also if I specify the password (additionally) inline in `environment`, it does not work and ends the same.

More information:
* If I use `${REDIS_HOST_PASSWORD:err}` (the alternative syntax), it seems to start, but… I guess it sets `err` as the variable then, which is of course not what it is supposed to do.
* ~~Also is `command` even supported? If I execute a shell in the container and run `top` I just get `redis-server *:6379` as the command line.~~
  **Edit:** Ah, apparently I just cannot "see" that with `top`, it seems to work fine.

```
$ podman-compose version
using podman version: podman version 3.1.2
podman-composer version  0.1.7dev
podman --version
podman version 3.1.2
0
```

Fedora 34 CoreOS

**Comment by rugk** [comment]
BTW as podman-compose rersolves host environment variables, a workaround is to set these variables before podman-compose is run:

E.g. like this:
```
$ cat ~/.bashrc.d/redis-podman-workaround.sh
# workaround for https://github.com/containers/podman-compose/issues/302
export REDIS_HOST_PASSWORD=your-password-here
```

:sweat_smile:

**Comment by muayyad-alsadi** [comment]
Env are read from `.env` file not the file passed to services

**Comment by rugk** [comment]
They are passed to the container, actually. They are just not properly replaced in the compose file.

Also, as said, I also tried it with `environments` inline and it does not work either:
> Note: Also if I specify the password (additionally) inline in environment, it does not work and ends the same.

Thus I conclude the env file is not the issue/reason here. The issue has to be the missing variable substitution support.

**Comment by muayyad-alsadi** [comment]
every thing seems working fine

```
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD:?err}
```

this means that it show exit with error message `err`

and this is what it did

```
RuntimeError: err
```

the question is where does it read those environment from,
docker-compse does not read them from service `env_file:` but from a file named `.env` in the current working directory

here is an example

* https://github.com/containers/podman-compose/blob/devel/tests/interpolation/docker-compose.yml
* https://github.com/containers/podman-compose/blob/devel/tests/interpolation/.env

and the result of up is

```
podman start -a interpolation_variables_1
export EXAMPLE_BRACES='Host user: alsadi'
export EXAMPLE_COLON_DASH_DEFAULT='My default'
export EXAMPLE_DASH_DEFAULT='My other default'
export EXAMPLE_DOT_ENV='This value is from the .env file'
export EXAMPLE_EMPTY=''
export EXAMPLE_LITERAL='This is a $literal'
export EXAMPLE_VARIABLE='Host user: alsadi'
```

**Comment by rugk** [comment]
Ah okay thanks, I was confused about these many things, `env_files` and `.env`  etc.
This makes sense though, thanks. :slightly_smiling_face:
