### ISSUE TITLE
Does not it read .env correctly?

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#303]
I'm having another compose and variable error, I think…

So I have an image with this:
```
environment: &nextcloud_environment
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
      - TEST=
```

and

`.env`: 
```
REDIS_HOST_PASSWORD=abc
TEST=abc
```

Run:
```
$ export REDIS_HOST_PASSWORD=yikes
$ export TEST=awesome
```
 
 Now start it and inside of the container I get:
 ```
 # echo $TEST

# echo $REDIS_HOST_PASSWORD
yikes
```

Now run `export unset $REDIS_HOST_PASSWORD` or `unset $REDIS_HOST_PASSWORD` (did not know the correct syntax right now, just run both).

Run the container again and the commands given above – both variables are now empty/unset.

## Problems
* Maybe `TEST=` is not the correct syntax, but should it really error without… aahhh well… it's an empty string I set. Of course forget it.
* Is it really correct that `$REDIS_HOST_PASSWORD` is unset in the second case? I.e. I would have expected it to read from `.env` automatically? … but I'm wrong?

## Relevant spec part

> Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values.

https://github.com/containers/podman-compose/issues/302

**Comment by rugk** [comment]
Okay now having written that up and tried way too many thi9ngs, I guess I just trapped into the same error as last time.

`REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:?REDIS_HOST_PASSWORD variable missing}` would be the correct way, would not it?

So close it, unless you see an error in podman-compose here…

**Comment by muayyad-alsadi** [comment]
this might be fixed with #370 

@rugk please test

**Comment by rugk** [comment]
I'll need to wait when I'll get the update… :upside_down_face:

**Comment by muayyad-alsadi** [comment]
you don't need to wait, you can just type 

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

or 

```
pip3 install --user https://github.com/containers/podman-compose/archive/devel.tar.gz
```
