### ISSUE TITLE
KeyError: 'environment' when run "exec"

### ISSUE THREAD

**Issue by monfrost** [containers/podman-compose#308]
I am using podman-compose with a docker-compose yaml file. All the container run well, but when a try to run the exec inside the cointainer i get the following error:
 podman-compose -f docker-compose.prod.yml exec web echo
  File "/home/pamonlan/.local/lib/python3.8/site-packages/podman_compose.py", line 1345, in compose_exec
    env = dict(cnt['environment'])
KeyError: 'environment'

I solve the problem changing the:

    env = dict(cnt['environment'])
by:
    env = dict(cnt.get('environment', {}))

**Comment by muayyad-alsadi** [comment]
Please test
