### ISSUE TITLE
Issue with `podman create --name=tvheadend --pod=tvheadend`

### ISSUE THREAD

**Issue by Hoeze** [containers/podman-compose#310]
Hi, I tried to use this Docker-compose file:
https://hub.docker.com/r/linuxserver/tvheadend

However, when running it I get the following error:
```bash
podman pod create --name=tvheadend --share net -p 9982:9982 -p 9981:9981
a88ac4e736cca85c55788e84a23e44613dd374194f0d9004e2449a45e96d1abe
0
podman create --name=tvheadend --pod=tvheadend -l io.podman.compose.config-hash=123 -l io.podman.compose.project=tvheadend -l io.podman.compose.version=0.0.1 -l com.docker.compose.container-number=1 -l com.docker.compose.service=tvheadend -e PUID=1000 -e PGID=1000 -e TZ=Europe/London --mount type=bind,source=/opt/container/tvheadend/mounts/config,destination=/config --mount type=bind,source=/mnt/recordings,destination=/recordings --add-host tvheadend:127.0.0.1 --add-host tvheadend:127.0.0.1 ghcr.io/linuxserver/tvheadend
Error: name "tvheadend" is in use: pod already exists
125
podman start -a tvheadend
Error: "tvheadend" is a pod, not a container: no such container
125
```

Is there some fix for this issue?

----
I'm using podman on Ubuntu 20.04 from the Kubic repo.
I installed `podman-compose` with `pip3 install podman-compose`:
```
# pip show podman-compose
Name: podman-compose
Version: 0.1.5
Summary: A script to run docker-compose.yml using podman
Home-page: https://github.com/containers/podman-compose
Author: Muayyad Alsadi
Author-email: alsadi@gmail.com
License: GPL-2.0-only
Location: /usr/local/lib/python3.8/dist-packages
Requires: pyyaml
Required-by: 
```

**Comment by muayyad-alsadi** [comment]
Please use latest devel branch

**Comment by dannyhpy** [comment]
@Hoeze Edit the `docker-compose.yml` file and rename the service from `tvheadend` to something like `tv` and see if it works. From what I read in your message, it seems like pods can't have the same name as containers..

**Comment by dannyhpy** [comment]
@Hoeze Have you tried to change the name as I said? Anyway, this is an issue related to `podman`,**not** `podman-compose`

**Comment by Hoeze** [comment]
@dannyhpy Yes, I just tried. Indeed, changing the name works.
It would be nice to not have this restriction as it confuses first-time users switching from docker like me.

**Comment by dannyhpy** [comment]
@Hoeze I agree, you could open an issue like this in the **containers/podman** repository if you want. It's mostly an issue related to **podman**

**Comment by muayyad-alsadi** [comment]
the latest `podman-compose` 1.x no longer creates an explicit pod

please try latest code.
