### ISSUE TITLE
podman-compose run does not start depends_on

### ISSUE THREAD

**Issue by septatrix** [containers/podman-compose#312]
Just as the title suggests: Only the main container but not containers listed under `depends_on` are started

**Comment by septatrix** [comment]
See: https://github.com/containers/podman-compose/blob/d97a20d563a833e6087c4351798b28129cbc5e8b/podman_compose.py#L1303

**Comment by developedsoftware** [comment]
Are you accepting pull requests for this? Happy to tackle some of the todos…

**Comment by muayyad-alsadi** [comment]
Yes please

**Comment by muayyad-alsadi** [comment]
please test
