### ISSUE TITLE
--dry-run misses podman version output…

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#317]
## STR

Any simple compose fle.
Command: `podman-compose --dry-run -p caddy up`

For an example, see https://github.com/containers/podman-compose/issues/316

## What happens

What I discovered:
* It does not show the podman version as the first line/startup.
* ~~It misses the image generation, i.e. sth. like `podman volume inspect caddy_caddy_data || podman volume create caddy_caddy_data`~~
  Edit: Oh, I overlooked that, it does, actually show this.

## What should happen

The things above should also be included in the dry-run.

## System

```
$ podman-compose version
using podman version: podman version 3.2.0
podman-composer version  0.1.7dev
podman --version
podman version 3.2.0
0
$ podman version
Version:      3.2.0
API Version:  3.2.0
Go Version:   go1.16.3
Built:        Wed Jun  9 16:24:16 2021
OS/Arch:      linux/amd64
```

same as in https://github.com/containers/podman-compose/issues/314, basically

**Comment by rugk** [comment]
What it also mises is of course the reply of the hashes of the containers etc. created by podman, but I guess this is okay. :upside_down_face:

**Comment by muayyad-alsadi** [comment]
I guess I've just fixed that.
