### ISSUE TITLE
Able to report version using --version argument

### ISSUE THREAD

**Issue by iongion** [containers/podman-compose#335]
In common automation tools that get required tools installed/provisioned, we prefer to have reproducible environments.

Thus, the ability to `podman-compose` to report its own version is what we would need, `docker-compose` provides one.

![image](https://user-images.githubusercontent.com/867609/132485540-0ebbd546-8ae1-445a-a872-3767822c13b8.png)

**Comment by muayyad-alsadi** [comment]
it was 

```
podman-compose version
```

but it's now both

**Comment by iongion** [comment]
Thank you, perfect!
