### ISSUE TITLE
"handle is invalid" error for volume inspection/creation but not for pod creation during a podman-compose up (On windows)

### ISSUE THREAD

**Issue by ultymatom** [containers/podman-compose#336]
Hello,

I'm trying to use podman-compose on windows, I've got podman configure with minikube (so podman remote on my windows and a VM is created by Minikube to run podman), I don't have any problem with podman, everything is working perfectly.

But with podman-compose I've got an issue.

I'm learning podman so I started with the apps that were used for a pluralsight class (that worked well when I was using docker).

it starts by creating a pod, which completes succesfully, then it inspects the volumes defined in the docker-compose.yml (or create it if it does not exist), But this part fails with "handle is invalid" (I'm not totally sure what it means but as I understood it, it means my Podman is not good for execution Podman command (sry I may be totally wrong but I'm a beginner :D) ) for both inspection and creation of the volume.

I noticed that in the podman-compose.py, the creation of the pod is done by the function run of the class Podman, and for the 2 others (inspection and creation of a volume) it's done by the function output of the same class.

they both use the module subprocess, run uses Popen, and output uses check_output. So I modify the script so that the inspection of the volume is executed thanks to run and not output (so Popen instead of check_output).
And the command is successful (I managed to display the json that I have if I do the podman inspect by myself), the "podman-compose up" still finishes with error because the return of the two functions are not similar, but it looks like Popen and check_output does not execute the command the same way.

I wanted to know if someone knows why with this difference of execution and how I can avoid that.
Because I can't manage to make work podman-compose

Creation of pod:
![image](https://user-images.githubusercontent.com/90399827/132702668-9b204c09-8681-4deb-8e27-97db62ed5129.png)

Inspection of a volume:
![image](https://user-images.githubusercontent.com/90399827/132702830-7ce7c3bb-fd41-4546-be4d-1d9b5870f682.png)

def run:
![image](https://user-images.githubusercontent.com/90399827/132702911-49134d84-b792-48ca-b952-b397ac1f9a79.png)

def output:
![image](https://user-images.githubusercontent.com/90399827/132702985-a901c45e-8a8f-4d21-8a2e-b807af1c5589.png)

I changed this line: (line 362)
![image](https://user-images.githubusercontent.com/90399827/132703193-5d2afdd8-39b7-4f3d-8cc6-4d95ed525bd5.png)
 to this line:
![image](https://user-images.githubusercontent.com/90399827/132703272-956f8e63-b102-40e0-b9d1-dfea50141fe0.png)

And here is the 2 different output I had:
![image](https://user-images.githubusercontent.com/90399827/132703427-fdd3b035-1229-4cc6-a771-bdf82cfcb851.png)

after the modification:
![image](https://user-images.githubusercontent.com/90399827/132703564-eeef8e8e-4a4c-4e03-b8f4-1a3a0245baaf.png)

the error at the end is because of the format of the return

I use this version of Podman:
podman --version
C:\Users\tipaty\Downloads\podman-2.2.1\podman.exe version 2.2.1

I don't know how to check my version of podman-compose, but I know it's not devel, I just  installed with pip install podman-compose (date: 6 of september 2021)

Thanks in advance for your help.

**Comment by muayyad-alsadi** [comment]
this might be due to having  `bash` OR operator (`||`).
maybe your windows setup does not have bash or understand shell OR operator?

**Comment by muayyad-alsadi** [comment]
please make sure to use the devel

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by ultymatom** [comment]
Hello,

The bash operator is only in the log output, it's just something displayed with the print function, in the script they do a try with the inspect command, and if the return codes is not 0, it executes the create command

I try with the devel version and same problem. except that it happens even before because in the devel version it tries to do podman --version with the check_output at the begining of the script, so I've got the error also (but this stays the exact same problem)

I tried new things today.

I modify the function so that it executes "Powershell.exe C:/Users/tipaty/Downloads/podman-2.2.1/podman volume inspect swarm-stack_counter-vol"

I still have the same output on the python script, but if I execute it in cmd prompt I've got the message I'm supposed to have:
![image](https://user-images.githubusercontent.com/90399827/133103130-07ff379c-6ad3-46b9-9804-ef5225ea7bf9.png)

I know that in the profile of powershell I've got this executing:

& minikube -p minikube podman-env | Invoke-Expression
$env:Path += ";C:\Users\tipaty\Downloads\podman-2.2.1;;C:\Users\tipaty\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts"

When i play the command ""Powershell.exe C:/Users/tipaty/Downloads/podman-2.2.1/podman volume inspect swarm-stack_counter-vol" I can see it has been executed in cmd prompt and in the python script (I put a 60 sec spleep to check)

I know that if do not execute what is in the profile, podman remote do not work. So what I don't understand is that everything seems to wrk has it would but the result with subprocess.check_output is not the one expected.

I'm starting to be a bit lost :D

**Comment by ultymatom** [comment]
Hello, more news hoping that someone can help me.

the problem happens also on another computer so this does not seem to be an isolated issus.

And second, i discover that when I want to redirect the output of a podman command I have the same error:

![image](https://user-images.githubusercontent.com/90399827/133444449-fe61934b-d0b5-4e53-bde4-acf8e9103a09.png)

**Comment by muayyad-alsadi** [comment]
so this is a problem of `podman` not `podman-compose`

@rhatdan  it seems that podman gives an error when having its output redirected on windows.

**Comment by ultymatom** [comment]
Yes, indeed it's a problem of podman, I also noticed that when I use Popen and add stdout=subprocess.PIPE in the arguments of the function (it allows to store the stdout) I also have the "handle is invalid error". I suppose that it needs to write somewhere the output and so we have the error (here I'm juste guessing)

**Comment by ultymatom** [comment]
I checked on the podman github annd there is an issue about it has been corrected, se we need to wait for a next release
https://github.com/containers/podman/issues/11444

So i close the issue here.
