### ISSUE TITLE
Update pip installable version to have latest updates

### ISSUE THREAD

**Issue by paigerube14** [containers/podman-compose#338]
Are we able to get an updated version of podman-compose to be pip installable?  Looks like the [release](https://github.com/containers/podman-compose/releases/tag/v0.1.5) hasn't been updated since Sept. 2019

**Comment by muayyad-alsadi** [comment]
I've just published a stable release 0.1.8 with hundreds of bug fixes.

https://pypi.org/project/podman-compose/
