### ISSUE TITLE
podman-compose fails with creating pod on first step

### ISSUE THREAD

**Issue by jezkerwin** [containers/podman-compose#346]
Podman version : 3.2.3
podman-compose version : 0.1.7dev
Linux : RHEL 8.4

When attempting to execute podman-compose over a docker-compose.yml file, the command to create the pod fails with the following error below.

The starting of the containers then fails because it can't find the pod.

```
[vagrant@rhel8 vectr]$ podman-compose up
['podman', '--version', '']
using podman version: podman version 3.2.3
podman pod create --name=vectr --infra-name=vectr_infra --share net -p 8081:8443
Error: unknown flag: --infra-name
125
```

**Comment by muayyad-alsadi** [comment]
I've assumed that all podman support that flag.  For now try the equivalent
cntnet mapping

**Comment by syedahaider97** [comment]
> I've assumed that all podman support that flag. For now try the equivalent cntnet mapping

Sorry, how do we go about doing that?
