### ISSUE TITLE
Support podman-compose build --format docker

### ISSUE THREAD

**Issue by casabre** [containers/podman-compose#354]
**Is your feature request related to a problem? Please describe.**
I have a docker-compose file which has also some build sections. Some of the Dockerfiles are using `SHELL ["/bin/bash", "-c"]`. When running podman-compose build, serveral 
```shell
WARN[0024] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -c] will be ignored. Must use `docker` format
```
are popping up. See also [podman #8477](https://github.com/containers/podman/issues/8477)

**Describe the solution you'd like**
A forwarding of the --format docker flag to any underlying build process. Something like
`podman-compose build --format docker` could do the job.

**Describe alternatives you've considered**
None, besides building it manually.

**Additional context**
None

**Comment by muayyad-alsadi** [comment]
you can already pass it like this

```
$ podman-compose --help

--podman-build-args args
                        custom arguments to be passed to `podman build`
$ podman-compose --podman-build-args='--format docker' build
```

unless you suggest making it passed by default

@rhatdan  what do you think?

**Comment by casabre** [comment]
@muayyad-alsadi thanks for letting me know. Was not aware of that flag.

But it seems not to work somehow
```shell
$ podman-compose --podman-build-args='--format docker' build
usage: podman-compose [-h] [-f FILE] [-p PROJECT_NAME] [--podman-path PODMAN_PATH] [--no-ansi] [--no-cleanup] [--dry-run]
                      [-t {1pod,1podfw,hostnet,cntnet,publishall,identity}]
                      {pull,push,build,up,down,run,start,stop,restart} ...
podman-compose: error: argument command: invalid choice: '--podman-build-args=--format docker' (choose from 'pull', 'push', 'build', 'up', 'down', 'run', 'start', 'stop', 'restart')
```

Is there a specific version necessary respectively a specific podman version?

**Comment by muayyad-alsadi** [comment]
Try latest devel branch of podman-compose

**Comment by muayyad-alsadi** [comment]
@casabre  you seems to have an older version of podman-compose

**Comment by casabre** [comment]
@muayyad-alsadi I installed the pypi.org version which was available at the time raising the issue. I go for an update and thanks for the info.
