### ISSUE TITLE
Hostname doesn't resolve properly in a container in a pod when using `--share net`

### ISSUE THREAD

**Issue by paalbra** [containers/podman-compose#357]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hostname doesn't resolve properly in a container in a pod when using `--share net` when creating pod. This gives me problems with sudo (and probably other stuff?)

**Steps to reproduce the issue:**

```
podman pod create --name=test123 --share net
podman run --name=test123_1 --pod=test123 --entrypoint /bin/bash debian:latest '-c' 'echo Hostname: $(hostname); grep -P "$(hostname)|test123" /etc/hosts; apt update > /dev/null 2>&1; apt install sudo > /dev/null 2>&1; sudo ls -ld /'
podman pod rm -f test123
```

**Describe the results you received:**

Notice the "unable to resolve" part and missing grep match on hostname.

```
f2308d485de8503d00dce0ab23cbfb269b226c93e38d1a72e04d53cc71f64aac
Hostname: 88b14cd0c470
10.0.2.100      test123 f2308d485de8-infra
sudo: unable to resolve host 88b14cd0c470: Name or service not known
dr-xr-xr-x. 21 root root 4096 Oct 15 13:20 /
f2308d485de8503d00dce0ab23cbfb269b226c93e38d1a72e04d53cc71f64aac
```

**Describe the results you expected:**

From another machine with podman 3.2.3:

```
a340145125e6c7a5b0a704bd64ae85cfb1b114e31ac06c1b65d4df891bc19298
Hostname: 85945c831fb6
10.0.2.100      test123 a340145125e6-infra
127.0.1.1 85945c831fb6 test123_1
dr-xr-xr-x. 21 root root 6 Oct 15 13:21 /
a340145125e6c7a5b0a704bd64ae85cfb1b114e31ac06c1b65d4df891bc19298
```

**Additional information you deem important (e.g. issue happens only occasionally):**

If I create the pod with `podman pod create --name=test123` (without `--share net`):

```
60fc6f54a6130d7bf1a4da704266112b2259850379b874c448b465c2efa46436
Hostname: test123
10.0.2.100      test123 60fc6f54a613-infra
dr-xr-xr-x. 21 root root 6 Oct 15 13:24 /
60fc6f54a6130d7bf1a4da704266112b2259850379b874c448b465c2efa46436
```

**Output of `podman version`:**

```
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 21:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: server
    version: "34"
  eventLogger: journald
  hostname: thatmachine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.19-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 13217677312
  memTotal: 16648974336
  ociRuntime:
    name: crun
    package: crun-1.0-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.0
      commit: 139dc6971e2f1d931af520188763e984d6cdfbf8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 16991117312
  swapTotal: 16991117312
  uptime: 301h 36m 20.65s (Approximately 12.54 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 12
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 21:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

I believe so. 3.4.0 is on top of releases page ( https://github.com/containers/podman/releases/tag/v3.4.0 )

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Dell desktop.

**Comment by rhatdan** [comment]
Rather then do that I reopened the issue and transferred it to podman-compose.

**Comment by muayyad-alsadi** [comment]
should I just change it to `--share net,uts` ?

**Comment by Luap99** [comment]
> should I just change it to `--share net,uts` ?

Yes, or even better do not set `--share` at all and let it use the default.

**Comment by rhatdan** [comment]
@muayyad-alsadi Yes, I question why there was ever a UTS namespace, since network and uts are so closely associated.

**Comment by muayyad-alsadi** [comment]
I guess if we add uts in that case two contains on same pod with two different hostnames won't work which is the case for 1podfw mapping.

**Comment by muayyad-alsadi** [comment]
@rhatdan I've started working on `podman network create` and using identity mapping by default 

https://github.com/containers/podman-compose/issues/363

the only problem is that podman's default DNS only resolves container names, and I want to create an alias named after the service, for example the container name is typically `myproj_web` which the service is called just `web`, containers expects to reach each other via service name not container name

how can I do this?  should I use `--add-host=host:ip`, can I make a CNAME record from the full name of the container to the service name? without trying to guess the ip?

**Comment by Luap99** [comment]
@muayyad-alsadi You can use `--network-alias` https://github.com/containers/podman/blob/main/docs/source/markdown/podman-run.1.md#--network-aliasalias

**Comment by muayyad-alsadi** [comment]
@Luap99  thank you very much, I've applied that, please help us test 1.x branch which uses `podman network create` instead of the single pod shared network workaround.

**Comment by muayyad-alsadi** [comment]
since it worked fine in 1.x I'll close this.
