### ISSUE TITLE
Ignores `compose.yaml`

### ISSUE THREAD

**Issue by ctron** [containers/podman-compose#360]
**Describe the bug**

`podman-compose` ignores the (preferred) `compose.yaml` file.

Also see: https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file

**To Reproduce**
1. Have a setup with a `compose.yaml` file
2. Run `podman-compose up`

**Expected behavior**

Starts as it would when the file was named `docker-compose.yml`.

**Actual behavior**

Does not find file.

**Output**

~~~
$ podman-compose up
using podman version: podman version 3.4.1
no docker-compose.yml or container-compose.yml file found, pass files with -f
~~~

**Environment:**
 - OS: Fedora 35
 - podman version:  3.4.1
 - podman compose version: podman-compose-0.1.7-6.git20210129.fc35.noarch

**Additional context**

**Comment by ctron** [comment]
@muayyad-alsadi The most recent version of podman-compose seems to be 0.1.8: https://github.com/containers/podman-compose/tags … where could I find a 1.x version?

**Comment by muayyad-alsadi** [comment]
For the sake of testing you can use devel branch which is now 1.x


pip3 install
https://github.com/containers/podman-compose/archive/devel.tar.gz

I'll publish it to pip after doing some tests.

**Comment by ctron** [comment]
I guess Fedora won't "upgrade" to a "devel" branch.

Is there any plans for a 1.0 release? Or is there a chance to backport this change?

**Comment by muayyad-alsadi** [comment]
I'll publish 1.x very soon.

Note you can pip install with --user
To do the install into your home

And yes I guess it's there in 0.1.9 (the one published to pypi).

**Comment by muayyad-alsadi** [comment]
@ctron I've just made the release of `v1.0.2`
