### ISSUE TITLE
Wont properly parse depends_on with conditions

### ISSUE THREAD

**Issue by Lyderik** [containers/podman-compose#364]
**Describe the bug**
Wont properly parse depends_on with conditions

**To Reproduce**
Use a docker-compose.yml with depends_on with conditions
```YML
version: '2.2'
services:
    service_name:
        ...
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
         ...
```
This origintes from overleafs [docker-compose.yml](https://github.com/overleaf/overleaf/blob/old-master/docker-compose.yml) and is working on my old server with docker-compose

**Expected behavior**
To support depends_on format

**Actual behavior**
Failed to parse docker-compose.yml

**Output**

```SH
$ podman-compose version
using podman version: 3.3.1
podman-composer version  0.1.9
podman --version 
podman version 3.3.1

$ podman-compose up -d
...
['podman', '--version', '']
using podman version: 3.3.1
Traceback (most recent call last):
  File "/home/bl/.local/bin/podman-compose", line 1790, in <module>
    main()
  File "/home/bl/.local/bin/podman-compose", line 1787, in main
    podman_compose.run()
  File "/home/bl/.local/bin/podman-compose", line 1047, in run
    self._parse_compose_file()
  File "/home/bl/.local/bin/podman-compose", line 1141, in _parse_compose_file
    flat_deps(services, with_extends=True)
  File "/home/bl/.local/bin/podman-compose", line 861, in flat_deps
    deps.update(deps_ls)
TypeError: unhashable type: 'dict'
```

**Environment:**
 - OS: Rocky Linux 8.5
 - podman version: 3.3.1

**Additional context**

It succelfully parses the compose file if i chance format of depends_on to not include the condition:
```YML
version: '2.2'
services:
    sharelatex:
        ...
        depends_on:
            - mongo
            - redis
        ...
```
 But is not optimal.

**Comment by muayyad-alsadi** [comment]
fixed as part of #368, please test latest devel
