### ISSUE TITLE
podman-compose fails with "AttributeError: 'str' object has no attribute 'get'" when doing Nextcloud up

### ISSUE THREAD

**Issue by ozoned** [containers/podman-compose#365]
**Describe the bug**
Latest Fedora 35 podman-compose crashes when attempting to do a podman-compose on Nextcloud's compose.

Failing version: podman-compose-0.1.7-8.git20211114.fc35.noarch
Rolled back to last working version: podman-compose-0.1.7-6.git20210129.fc35.noarch

**To Reproduce**
1. Get Nextcloud Compose
2. /usr/bin/podman-compose -f /home/desktop/Nextcloud/container-compose.yml up

**Expected behavior**
Runs the compose and starts up all containers

**Actual behavior**
Crashes with a backtrace at:

  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 150, in fix_mount_dict
    name = vol.get('name', None) 
AttributeError: 'str' object has no attribute 'get'

**Output**

$ /usr/bin/podman-compose -f /home/desktop/Nextcloud/container-compose.yml up
['podman', '--version', '']
using podman version: 3.4.2
podman pod create --name=nextcloud --share net --infra-name=nextcloud_infra -p 8080:80
428c3caf62302f6ffb0f8b230510f600ab62bd24e73dca707ce0c2ac81283280
0
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==0.1.7.dev0', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1727, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1031, in run
    cmd(self, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1263, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1419, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 710, in container_to_args
    podman_args.extend(get_mount_args(compose, cnt, volume))
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 517, in get_mount_args
    assert_volume(compose, fix_mount_dict(compose, volume, proj_name, srv_name))
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 150, in fix_mount_dict
    name = vol.get('name', None) 
AttributeError: 'str' object has no attribute 'get'

**Environment:**
 - OS: Linux Fedora 35
 - podman-compose version failing: podman-compose-0.1.7-8.git20211114.fc35.noarch

**Comment by muayyad-alsadi** [comment]
would you please try latest version of 1.x or 0.1.x (that is for now 0.1.9)

if you know the maintainer tell him/her to upgrade.

you can get it from pip using

```
pip3 install --user podman-compose
```

**Comment by muayyad-alsadi** [comment]
@ozoned  please test latest code.

**Comment by ozoned** [comment]
Thanks.  Sorry for the delay.  Got distracted.  I'll check it out.  Appreciate it.

**Comment by Zerwin** [comment]
For me I get 
``` AttributeError: 'Namespace' object has no attribute 'volumes' ```
with the command 
`sudo podman-compose -f docker-compose.yml up -d --force-recreate`

I'm currently running podman-compose 0.1.10
