### ISSUE TITLE
podman-compose fail to start : File "/usr/local/bin/podman-compose", line 1790, in <module> on Debian WSL2

### ISSUE THREAD

**Issue by Helltoril** [containers/podman-compose#367]
**Describe the bug**
With podman-compose version 1.9.0, podman-compose fail to start with docker-compose file in Debian WSL2 and Ubuntu WSL2

Failing version: 1.9.0

**To Reproduce**
Install Podman on WSL2 Debian
Install Podman-compose with devel branch
Exec command : podman-compose up -d docker-compose.yaml with any file docker-compose.yaml

**Expected behavior**
Runs the compose and starts up all containers

**Actual behavior**
Crashes with a backtrace at:
['podman', '--version', '']
using podman version: 3.4.2
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 1790, in <module>
    main()

**Output**

```
['podman', '--version', '']
using podman version: 3.4.2
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 1790, in <module>
    main()
  File "/usr/local/bin/podman-compose", line 1787, in main
    podman_compose.run()
  File "/usr/local/bin/podman-compose", line 1049, in run
    cmd(self, args)
  File "/usr/local/bin/podman-compose", line 1281, in wrapped
    return func(*args, **kw)
  File "/usr/local/bin/podman-compose", line 1428, in compose_up
    excluded = get_excluded(compose, args)
  File "/usr/local/bin/podman-compose", line 1421, in get_excluded
    excluded-= compose.services[service]['_deps']
KeyError: 'docker-compose.yaml'

```

**Environment:**
 - OS:  WSL2 Debian and Ubuntu
 - podman version: 3.4.2
 - podman compose version: 0.1.9

**Additional context**

podman-compose start with version 0.1.7dev
I replace podman-compose file in version 0.1.9 with fil in version 0.1.7dev in directory /usr/local/bin/

**Comment by muayyad-alsadi** [comment]
this is not the proper way to pass docker-compose.yaml file

here is the output from `docker-compose --help` and `docker-compose up --help`

```
Usage:
  docker-compose [-f <arg>...] [--profile <name>...] [options] [--] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
....
Usage: up [options] [--scale SERVICE=NUM...] [--] [SERVICE...]
```

to pass the file use -f or leave it as default

```
podman-compose -f docker-compose.yaml up -d 
podman-compose up -d 
```
