### ISSUE TITLE
quotes in .env are not handled

### ISSUE THREAD

**Issue by martinetd** [containers/podman-compose#370]
**Describe the bug**
quotes for variables in .env are properly handled by docker, in particular, this as a .env file:
```
FOO="example string" # some comment
```
will expand as `example string` without quotes nor the comment when used as ${FOO} in docker-compose.yml

**To Reproduce**
1.
```
$ echo 'FOO="example string" # some comment' > .env
$ cat > docker-compose.yml <<'EOF'
version: '3'
services:
  busybox:
    image: "docker.io/busybox"
    environment:
      test: "${FOO}"
    command: "/bin/sh -c 'echo $$test'"
EOF
```
2. run with podman-compose up or docker-compose up:
```
$ ~/code/podman-compose/podman_compose.py up
['podman', '--version', '']
using podman version: 3.4.1
considering ['FOO', '"example string" # some comment']
** excluding:  set()
podman pod create --name=comp --share net --infra-name=comp_infra
Error: error adding pod to state: name "comp" is in use: pod already exists
exit code: 125
podman create --name=comp_busybox_1 --pod=comp --label io.podman.compose.config-hash=123 --label io.podman.compose.project=comp --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=comp --label com.docker.compose.project.working_dir=/tmp/comp --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=busybox -e test="example string" # some comment --add-host busybox:127.0.0.1 --add-host comp_busybox_1:127.0.0.1 docker.io/busybox /bin/sh -c echo $test
787393065b4d46aac205f0987a778dbffb0db08c37fd5ce5eeeca8dcc4701bc8
exit code: 0
podman start -a comp_busybox_1
"example string" # some comment
exit code: 0
$ docker-compose up
Creating network "comp_default" with the default driver
Pulling busybox (docker.io/busybox:)...
latest: Pulling from library/busybox
3aab638df1a9: Pull complete
Digest: sha256:52817dece4cfe26f581c834d27a8e1bcc82194f914afe6d50afad5a101234ef1
Status: Downloaded newer image for busybox:latest
Creating comp_busybox_1 ... done
Attaching to comp_busybox_1
busybox_1  | example string
comp_busybox_1 exited with code 0
```

**Expected behavior**
podman-compose should print 'example string' without quote and comment like docker-compose did

**Actual behavior**
it didn't

**Output**

```
$ podman-compose version
~/code/podman-compose/podman_compose.py --version
['podman', '--version', '']
using podman version: 3.4.1
podman-composer version  0.1.9
podman --version 
podman version 3.4.1
exit code: 0
```

**Environment:**
 - OS: Linux
 - podman version:  3.4.1
 - podman compose version: 749d188321c4662e98de84b8c1449d10b8b2d647

**Additional context**

If you're ok with ugly, this appears to work:
```diff
diff --git a/podman_compose.py b/podman_compose.py
index e99523939833..9f1b4eaa6f62 100755
--- a/podman_compose.py
+++ b/podman_compose.py
@@ -992,6 +992,13 @@ def resolve_extends(services, service_names, environ):
         new_service = rec_merge({}, from_service, service)
         services[name] = new_service
 
+def env_trim_quotes(env):
+    [k, v] = env
+    if v.startswith('"'):
+        end = v.find('"', 1)
+        if end > 1:
+            return [k, v[1:end]]
+    return env
 
 class PodmanCompose:
     def __init__(self):
@@ -1107,7 +1114,7 @@ def _parse_compose_file(self):
         if os.path.isfile(dotenv_path):
             with open(dotenv_path, 'r') as f:
                 dotenv_ls = [l.strip() for l in f if l.strip() and not l.startswith('#')]
-                self.environ.update(dict([l.split("=", 1) for l in dotenv_ls if "=" in l]))
+                self.environ.update(dict([env_trim_quotes(l.split("=", 1)) for l in dotenv_ls if "=" in l]))
         # TODO: should read and respect those env variables
         # see: https://docs.docker.com/compose/reference/envvars/
         # see: https://docs.docker.com/compose/env-file/
```
but there are probably other quoting styles that docker-compose handles

**Comment by muayyad-alsadi** [comment]
but the documentation clearly say:

> There is no special handling of quotation marks. This means that they are part of the VAL.


https://docs.docker.com/compose/env-file/#syntax-rules
https://docs.docker.com/compose/environment-variables/#the-env-file

**Comment by muayyad-alsadi** [comment]
@martinetd 
I've tested on both python's docker-compose and compose 2.x and they both process the quotes despite the documentation stating otherwise.

I'll consider it as "bug for bug compatibility" and fix this issue soon.

**Comment by martinetd** [comment]
Thanks!
I wonder why they wrote that in the documentation, but it's definitely appreciable to be able to use the same env file :)

**Comment by muayyad-alsadi** [comment]
we can use library [python-dotenv](https://github.com/theskumar/python-dotenv), like this

```python
from dotenv import dotenv_values
# ...
self.environ.update(dotenv_values(dotenv_path))
```

it seems that docker-compose until 1.25.x did not process dotenv quotes

https://github.com/docker/compose/blob/1.25.x/compose/config/environment.py

and starting from 1.26 to the latest version 1.29.2 they start using dotenv

https://github.com/docker/compose/blob/1.26.x/compose/config/environment.py
https://github.com/docker/compose/blob/1.29.2/compose/config/environment.py


```python
def env_vars_from_file(filename, interpolate=True):
    """
    Read in a line delimited file of environment variables.
    """
    if not os.path.exists(filename):
        raise EnvFileNotFound("Couldn't find env file: {}".format(filename))
    elif not os.path.isfile(filename):
        raise EnvFileNotFound("{} is not a file.".format(filename))

    env = dotenv.dotenv_values(dotenv_path=filename, encoding='utf-8-sig', interpolate=interpolate)
    for k, v in env.items():
        env[k] = v if interpolate else v.replace('$', '$$')
    return env
```

**Comment by azuwey** [comment]
This is issue is till present in the podman version: 4.1.1 and podman-composer version 1.0.3, removing quotes from the environment variable solves the problem.

**Comment by Jonamaita** [comment]
I have podman version 3.4.2 and `podman-compose` version 1.0.3 and this issue is still present.

**Comment by mboyea** [comment]
I have podman version 5.2.3 and this issue is still present.

The `.env` file contains:

```sh
USER_PASS_PAIRS="user1:password user2:password user3:password"
```

I run: `podman container run --tty --interactive --env-file .env --entrypoint sh docker.io/busybox`

Then in the container I run: `echo "$USER_PASS_PAIRS"`

It outputs: "user1:password user2:password user3:password"

As you can see, quotes are not sanitized.

**Comment by andrewschmidgit** [comment]
still broken

`DB_CONN="server=something;user=something"` gets passed in with quotes
