### ISSUE TITLE
dns name are not set. getaddrinfo ENOTFOUND as result.

### ISSUE THREAD

**Issue by korjavin** [containers/podman-compose#383]
**Describe the bug**
DNS are not set.

**To Reproduce**
1. I uploaded my single.yml file
[compose.yml.zip](https://github.com/containers/podman-compose/files/7775028/compose.yml.zip)
2. start it as `docker-compose -f single.yml up`

**Expected behavior**
Elasticsearch DNS will be set

**Actual behavior**
getaddrinfo ENOTFOUND elasticsearch

**Output**

**Environment:**
 - OS: Linux 
 - podman version: 3.3.1
 - podman compose version: (git hex)

**Comment by muayyad-alsadi** [comment]
quote from readme

> podman dnsname plugin (Optional requirement. If necessary, the containers be able to resolve each other if they are on the same CNI network. In distributions, it is usually found in the podman-plugins package)
