### ISSUE TITLE
top-level volumes key is not mandated for shared named volumes

### ISSUE THREAD

**Issue by bam80** [containers/podman-compose#386]
It's required by Spec to list such volumes under top-level volumes key:
> To reuse a volume across multiple services, a named volume MUST be declared in the top-level volumes key.

https://github.com/compose-spec/compose-spec/blob/master/spec.md#volumes

Docker Compose V1/2 produce a error if they are not.

The problem:
Podman-compose doesn't mandate it and allows to continue gracefully even if there is no top-level volumes section.

**Comment by muayyad-alsadi** [comment]
@bam80  please test
