### ISSUE TITLE
"podman-compose run" always builds dependent images unconditionally

### ISSUE THREAD

**Issue by bam80** [containers/podman-compose#388]
It shouldn't build them if the needed tags are already in place, which corresponds to `docker compose` behavior.

**Comment by muayyad-alsadi** [comment]
it's not unconditionally, as you can see we pass `if_not_exists` around 1400

```
    if not args.no_build:
        # `podman build` does not cache, so don't always build
        build_args = argparse.Namespace(
            if_not_exists=(not args.build),
            **args.__dict__)
        compose.commands['build'](compose, build_args)
```

NOTE: docker prefers remote over local which is a security hole, I'm not going to implement it

**Comment by muayyad-alsadi** [comment]
check this discussion for context

https://github.com/containers/podman-compose/issues/265


but I've just noticed that you are talking about run not up

```
up_args = argparse.Namespace(**dict(args.__dict__,
               detach=True, services=deps,
               # defaults
               no_build=False, build=True, force_recreate=False, no_start=False, no_cache=False, build_arg=[],
               )
        )
```

I'll fix that
