### ISSUE TITLE
Rewrite this tool in go

### ISSUE THREAD

**Issue by colben** [containers/podman-compose#396]
Is there any plan to rewrite this tool in go?
Python is hard to deploy.

**Comment by muayyad-alsadi** [comment]
I'm not planning to do that in near future.
Specially I'm focused on developer experience (because on production one would be running OKD/kubernetes/...etc.)


> Python is hard to deploy.

it does not seem to be hard to me

```
pip3 install --user podman-compose
```

**Comment by nitram509** [comment]
👍  for this proposal.

Having multiple python environments on my development machine with multiple virtual environments makes managing site-packages a repetitive task to me. Also, I fear some other dependent libraries might interfere in the future. To be fair, that's not yet the case for me, but a well-known issue for me as an application developer having multiple python envs on my machine.

@muayyad-alsadi I appreciate your focus on quickly shipping features to us users. But let me please echo and emphasize the wish for a zero-dependency fat binary as well. I would be willing to support as well :)

**Comment by muayyad-alsadi** [comment]
Currently this project has only two python dependencies that is python yaml and python-dotenv
I'm not aware of any concern of potential conflict between their versions

Typically I don't use venv, I just use `pip3 install --user ...`
