### ISSUE TITLE
building with Dockerfiles in subdirectories break

### ISSUE THREAD

**Issue by flashpixx** [containers/podman-compose#400]
**Describe the bug**

Path resolution for Dockerfile with a build context add the subdirectory twice. So the name of the subdirectory where the Dockerfile is located will be added again to the path, so the Dockerfile cannot be found:
`Error: stat /var/tmp/libpod_builder375969945/build/deploy/deploy/myservice.Dockerfile: no such file or directory`

**To Reproduce**

See given Zip file [path-error.zip](https://github.com/containers/podman-compose/files/7820965/path-error.zip) with Dockerfile and Docker-Compose and this directory structure. Run `podman-compose build`

**Expected behavior**
Remove duplicated path to build and working with Dockerfiles which are stored within a subdirectory

**Environment:**
 - OS: Mac
 - podman version: 3.4.4
 - podman-composer version  1.0.3
 - podman version 3.4.4

**Comment by muayyad-alsadi** [comment]
strange it worked for me
I've extracted your file and just fixed the typo in the dockerfile `FROM alpine:latest`

```
$ /path/to/podman_compose.py up
['podman', '--version', '']
using podman version: 3.4.2
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'path-error_myservice']
Error: error inspecting object: path-error_myservice: image not known
podman build -t path-error_myservice -f ./deploy/myservice.Dockerfile .
STEP 1/1: FROM alpine:latest
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 59bf1c3509f3 done  
Copying config c059bfaa84 done  
Writing manifest to image destination
Storing signatures
COMMIT path-error_myservice
--> c059bfaa849
Successfully tagged localhost/path-error_myservice:latest
Successfully tagged docker.io/library/alpine:latest
c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18
exit code: 0
['podman', 'network', 'exists', 'path-error_default']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=path-error', '--label', 'com.docker.compose.project=path-error', 'path-error_default']
['podman', 'network', 'exists', 'path-error_default']
podman create --name=path-error_myservice_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=path-error --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=path-error --label com.docker.compose.project.working_dir=/home/alsadi/proj/podman-compose/tests/path-error --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=myservice --net path-error_default --network-alias myservice path-error_myservice
01ea650fbf52e4be3bbc8ffacf277cb37c58844d69824a5594e2b27f17e75610
exit code: 0
podman start -a path-error_myservice_1
exit code: 0
```

did you pass something to `podman-compose up` or set an environment variable

**Comment by muayyad-alsadi** [comment]
I've just noted that you are using MacOS, could this be the reason?

**Comment by flashpixx** [comment]
Yes I'm using OSX Big Sur with Python 3.8, but I don't think that is could be the problem, because Python should work on all OS equal. I have forked your project and try to figure out where the problem inside the code comes in (on the current devel version the problem exists too).

**Comment by flashpixx** [comment]
It seems that the duplicated path will generated by podman itself, so I close the issue here

**Comment by flashpixx** [comment]
see podman issue https://github.com/containers/podman/issues/12763

**Comment by jedahan** [comment]
I think I found a workaround, that I think is podman-compose specific.

If you specify `build.dockerfile`, instead of having podman(-compose?) fill it in for you, it will be found correctly.

```
# this works:
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
```

```
# this doesn't work
services:
  api:
    build: ./api
```
