### ISSUE TITLE
podman-compose up run failure！I need some help!

### ISSUE THREAD

**Issue by JohyC** [containers/podman-compose#401]
**Describe the bug**

Please make sure it's not a bug in podman (in that case report it to podman)
or your understanding of docker-compose or how rootless containers work (for example, it's normal for rootless container not to be able to listen for port less than 1024 like 80)

please try to reproduce the bug in latest devel branch

**To Reproduce**
1. what is the content of the current working directory (ex. `docker-compose.yml`, `.env`, `Dockerfile`, ...etc.)

I used [https://github.com/containers/podman-compose/blob/devel/examples/busybox/docker-compose.yaml](podman-compose/examples/busybox)

2. what is the sequence of commands you typed

Just use `podman-compose up`

please use [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for example give me a small busybox-based compose yaml

**Expected behavior**

**Actual behavior**
What is the behavior you actually got and that should not happen.

**Output**

```
$ podman-compose --version

['podman', '--version', '']
using podman version: 3.0.1
podman-composer version  1.0.3
podman --version
podman version 3.0.1
exit code: 0

```
$ podman-compose up

[error.txt](https://github.com/containers/podman-compose/files/7822057/error.txt)

```

**Environment:**
 - OS: Linux 5.10.28-aml-s812 armv7l 
 - podman version: 3.0.1
 - podman compose version: (git hex) 1.0.3

**Additional context**

![image](https://user-images.githubusercontent.com/38210128/148389566-366fa0ea-110c-4e79-8ab1-6edf4ce5c66f.png)

**Comment by muayyad-alsadi** [comment]
```
Error: unrecognized command `podman network exists`
```


from the [readme](https://github.com/containers/podman-compose#versions)

```
If you have legacy version of podman (before 3.1.0) you might need to stick with legacy podman-compose 0.1.x branch. The legacy branch 0.1.x uses mappings and workarounds to compensate for rootless limitations.

Modern podman versions (>=3.4) do not have those limitations and thus you can use latest and stable 1.x branch.
```

either upgrade to podman >= 3.1.0
or use 0.1.x branch of podman-compose

**Comment by JohyC** [comment]
> ```
> Error: unrecognized command `podman network exists`
> ```
> 
> from the [readme](https://github.com/containers/podman-compose#versions)
> 
> ```
> If you have legacy version of podman (before 3.1.0) you might need to stick with legacy podman-compose 0.1.x branch. The legacy branch 0.1.x uses mappings and workarounds to compensate for rootless limitations.
> 
> Modern podman versions (>=3.4) do not have those limitations and thus you can use latest and stable 1.x branch.
> ```
> 
> either upgrade to podman >= 3.1.0 or use 0.1.x branch of podman-compose

Ok! I got it.thanks man!
