### ISSUE TITLE
no pod generated

### ISSUE THREAD

**Issue by frostbane** [containers/podman-compose#404]
podman-compose used to create an extra *-infra container and a pod that contains all the containers described in the docker-compose.yml

After an update with my package manager, no more pods got generated.

```
$ podman-compose version
using podman version: 3.4.2
podman-composer version  1.0.3
podman --version 
podman version 3.4.2
```

**Environment:**
 - OS: Fedora Linux
 - podman version: 3.4.2 
 - podman compose version: 1.0.3

**Comment by palko444** [comment]
Hi,

same issue 

> podman-compose version
> ['podman', '--version', '']
> using podman version: 3.4.4
> podman-composer version  1.0.3
> podman --version 
> podman version 3.4.4
> exit code: 0

OS: Fedora 34/35

**Comment by developedsoftware** [comment]
Same issue here too!

**Comment by muayyad-alsadi** [comment]
please read comments here #379

https://github.com/containers/podman-compose/issues/379
