### ISSUE TITLE
Add project to Ubuntu repositories

### ISSUE THREAD

**Issue by svdHero** [containers/podman-compose#405]
Thank you for your amazing work in creating a real alternative to docker-compose.

For convenience, I'd like to install podman-compose via `apt-install` similar to podman. Any chance that this project is added to Ubuntu repositories any time soon?

**Comment by muayyad-alsadi** [comment]
I would be please if this happen, but it's not my responsibility to package it for every distro. please contact the package maintainer.

https://packages.ubuntu.com/impish/podman

```
Maintainer:
Ubuntu MOTU Developers (Mail Archive)
Please consider filing a bug or asking a question via Launchpad before contacting the maintainer directly.

Original Maintainers (usually from Debian):
Debian Go Packaging Team (Mail Archive)
Dmitry Smirnov
Reinhard Tartler

```
