### ISSUE TITLE
network_mode=host is not working as expected

### ISSUE THREAD

**Issue by palko444** [containers/podman-compose#406]
**Describe the bug**
it seems after upgrade to new version of podman-compose **network_mode=host** is not working as expected
Its working ok with older version of podman-compose. All i did to fix issue, was ```dnf downgrade podman-compose```

**old version - working**
```
using podman version: podman version 3.4.2
podman-composer version  0.1.7dev
podman --version
podman version 3.4.2
```

**new version - not working** 
```
['podman', '--version', '']
using podman version: 3.4.4
podman-composer version  1.0.3
podman --version 
podman version 3.4.4
exit code: 0
```

**To Reproduce**
Use new version of docker-compose mentioned up, with this compose file

> version: "3.7"
> services:
>   node_exporter:
>     image: quay.io/prometheus/node-exporter:v1.3.1
>     container_name: node_exporter1
>     command:
>       - '--path.rootfs=/host'
>     network_mode: host
>     pid: host
>     restart: unless-stopped
>     volumes:
>       - '/:/host:ro,rslave'

**Expected behavior**
I would expect node_exporter port 9100 would be accessible from host network.

**Actual behavior**
port is not accesible

**Output**

```
$ podman-compose version
using podman version: 3.4.0
podman-composer version  0.1.7dev
podman --version 
podman version 3.4.0

$ podman-compose up
...

```

**Environment:**
 - OS: fedora 34/35

**Additional context**
It seems also **infra container** is missing in output of ```podman ps -a```, it could be related to issue #404 

Thank you in advance
Br Palo

**Comment by muayyad-alsadi** [comment]
this was fixed in #397

15e0ab92618b0d5b9c7974ceb7910caeb13542bd

```
commit 15e0ab92618b0d5b9c7974ceb7910caeb13542bd
Author: Muayyad alsadi <alsadi@gmail.com>
Date:   Wed Jan 12 15:44:47 2022 +0200

    FIXES #397: support host network mode
```

please use latest devel until we make a new release

```
pip3 install --user https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by casavaca** [comment]
> this was fixed in #397
> 
> [15e0ab9](https://github.com/containers/podman-compose/commit/15e0ab92618b0d5b9c7974ceb7910caeb13542bd)
> 
> ```
> commit 15e0ab92618b0d5b9c7974ceb7910caeb13542bd
> Author: Muayyad alsadi <alsadi@gmail.com>
> Date:   Wed Jan 12 15:44:47 2022 +0200
> 
>     FIXES #397: support host network mode
> ```
> 
> please use latest devel until we make a new release
> 
> ```
> pip3 install --user https://github.com/containers/podman-compose/archive/devel.tar.gz
> ```

It seems that your recent commit re-introduced this bug? https://github.com/containers/podman-compose/commit/9eda56caf9973d1cc38b80dafc8ed196ecada217?diff=split?diff=split

**Comment by muayyad-alsadi** [comment]
it was introduced when trying to have both network mode and network options slirp4netns

**Comment by henriquemattos** [comment]
Wasn't there any release since July 2022?
