### ISSUE TITLE
podman-compose run swallows exit code

### ISSUE THREAD

**Issue by dwt** [containers/podman-compose#408]
**Describe the bug**
When I run a command like this: `podman-compose run some_image /bin/sh -c "exit 1" || echo failed` then this does not output `failed`, even though I see the exit code of `/bin/sh` printed on the console.

This works as expected using `docker-compose`

As far as I read the source code, that means that the `run()` method of Podman needs to `sys.exit()` if the podman command it runs fails somewhere.

**Expected behavior**
Podman-compose run should return a non zero exit code if the command run fails.

**Actual behavior**
podman-compose returns a zero exit code.

**Output**

```
podman-compose 0.1.5 - but also inspected devel branch
podman version 1.6.4
```

**Environment:**
 - OS: CentOS 7.6
 - podman version: 1.6.4
 - podman compose version: 0.1.5

**Comment by brandoncazander** [comment]
I'm also encountering this issue—I have to process stdout for the 'exit code: 1' message but would greatly prefer if podman-compose exited with the same code as the exec'd command.

**Comment by muayyad-alsadi** [comment]
yes you are right, I'll fix this ASAP

**Comment by muayyad-alsadi** [comment]
please test latest devel branch

**Comment by dwt** [comment]
LGTM

**Comment by brandoncazander** [comment]
Thanks for this!
