### ISSUE TITLE
Transform docker-compose `depends_on` into `podman create --requires`

### ISSUE THREAD

**Issue by szpak** [containers/podman-compose#425]
**Describe the solution you'd like**
`podman-compose` could transform `depends_on:` from `docker-compose.yml` into a `--requires` switch (podman [3.2.0+](https://github.com/containers/podman/pull/9754)) in the `podman create` call. Thanks to that it would be easier to start the group of containers without `podman-compose` (if needed) after it's initial usage (in the previous versions `pod` could be used for that, but currently a pod is no longer needed/created).

**Additional context**
I'm really glad to see the increasing support for docker-compose features in podman-compose. In 2020, it was even problematic to do some tricks with volumes, but currently my `docker-compose.yml` files are running up out of the box. Thanks!

**Comment by muayyad-alsadi** [comment]
please test

**Comment by szpak** [comment]
Just tested and it works as expected. Thanks for your quick implementation!
