### ISSUE TITLE
Add --profile NAME option to support selectively enabling services

### ISSUE THREAD

**Issue by redsaz** [containers/podman-compose#430]
docker-compose supports selectively enabling services through specifying [profiles](https://docs.docker.com/compose/profiles/) in the docker-compose.yaml file, and then running those service with `docker-compose --profile NAME`.

This option would be nice to have in podman-compose as well, as I have times where some services don't need started, like when I'm writing changes for an app, but still need the other services up to test against.

A workaround I'm using now is to specify different compose config files, which works, but is less convenient than having one file with the entirety of the config.

**Comment by dixonwhitmire** [comment]
I have the bandwidth to work on this issue (but I'm not a maintainer). Would a reasonable "first pass" include support for both `--profile` and the `COMPOSE_PROFILES` env variable?

Based on what I've read in the documentation these would be evaluated for the `up` and `run` commands. If anyone has a link which states which commands evaluate `--profile` I will be happy to review it.

**Comment by dixonwhitmire** [comment]
This to-do list may change a bit as I start working on the feature but here is what I think I will need to do from a high level. I'll update this comment as items are completed:


- [ ] Test cases to include a use-case with 1 profile and multiple profiles using --profile arg and COMPOSE_PROFILES environment variable
- [ ] parse_compose_file to ensure that that profiles are parsed from the YAML compose file and COMPOSE_PROFILES environment variable is evaluated and cached in self.environ
- [ ] compose_run_parse and compose_run
- [ ] compose_up_parse and compose_up
- [ ] _parse_args ?

**Comment by Arano-kai** [comment]
> I have the bandwidth to work on this issue (but I'm not a maintainer). Would a reasonable "first pass" include support for both `--profile` and the `COMPOSE_PROFILES` env variable?
> 
> Based on what I've read in the documentation these would be evaluated for the `up` and `run` commands. If anyone has a link which states which commands evaluate `--profile` I will be happy to review it.

As I recall `--profile` also applies to `config`, `down` and `stop`.
If it helps: For the docker-compose-plugin `--profile` is valid immediately after `compose`, but throws errors after `run` and others, which may indicate an application to any command that manipulates containers.

**Comment by dixonwhitmire** [comment]
> > I have the bandwidth to work on this issue (but I'm not a maintainer). Would a reasonable "first pass" include support for both `--profile` and the `COMPOSE_PROFILES` env variable?
> > Based on what I've read in the documentation these would be evaluated for the `up` and `run` commands. If anyone has a link which states which commands evaluate `--profile` I will be happy to review it.
> 
> As I recall `--profile` also applies to `config`, `down` and `stop`. If it helps: For the docker-compose-plugin `--profile` is valid immediately after `compose`, but throws errors after `run` and others, which may indicate an application to any command that manipulates containers.

@Arano-kai - thanks for the feedback. I'll see if I can get compose up and running again on my laptop so that I can test a bit before embarking down the podman path. 

I do recognize that `--profile` is a global option of sorts. What I will also need to do is see if I can filter the services in podman compose prior to invoking the associated command, so that I don't have to update "N" number of command implementations.

**Comment by dixonwhitmire** [comment]
And here's the [official doc](https://github.com/docker/docs/blob/main/compose/profiles.md). The sections on auto-enablement and dependency resolution are helpful. 

Although for this first PR I think it may be helpful to have a narrower scope and start out with the changes required to support `--profile` and `COMPOSE_PROFILES`. I'm concerned that "doing more" will significantly increase the "time to deliver" and will also change quite a bit.

**Comment by Hubbitus** [comment]
Hello. Sorry, what is the version of podman-compose supporting `--profile` option?

**Comment by hedayat** [comment]
I also like this feature, and it's sad that it just got merged a day after releasing 1.0.6. I'd say this change by itself justified having another 1.0.7 release :D :P 

Anyway, hope it'll be release soon. thanks for your work :)

**Comment by dottorblaster** [comment]
Same :smiling_face_with_tear:

**Comment by brunomcuesta** [comment]
Any updates on this feature?

**Comment by rnestler** [comment]
Judging from the release notes it looks like this is included in 1.1.0: https://github.com/containers/podman-compose/releases/tag/v1.1.0
> Added support for profile argument.

**Comment by piotr-dobrogost** [comment]
> Profile aware commands:
> 
> convert/config (convert is an alias for config)
> down
> kill
> restart
> stop
> start
> up
> pause
> unpause

This list is missing `config --profiles` (plural) to list all profiles which should be treated as an integral part of profile support.
I raised this problem as https://github.com/containers/podman-compose/issues/1052

**Comment by ch-reck** [comment]
podman-compose.py is still ignoring the `COMPOSE_PROFILES` setting in `.env`
See issue that solved this for docker compose: https://github.com/docker-archive/compose-cli/issues/1492
