### ISSUE TITLE
Weird behaviour with secrets

### ISSUE THREAD

**Issue by IAoVI** [containers/podman-compose#440]
I recently migrated a container (based on this image: https://hub.docker.com/r/felddy/foundryvtt) from docker-compose to podman-compose.

The original docker-compose.yml looked like this:
``` version: "3.8"

 secrets:
   config_json:
     file: secrets.json
     
 services:
   foundry:
     image: felddy/foundryvtt:release
     hostname: my_foundry_host
     container_name: foundry
     init: true
     restart: "unless-stopped"
     environment:
        - FOUNDRY_MINIFY_STATIC_FILES=true
     volumes:
       - type: bind
         source: ./data
         target: /data
     ports:
       - target: 30000
         published: 30000
         protocol: tcp
     secrets:
       - source: config_json
         target: config.json
```

To make SELinux happy I had to change the volumes to:
```     volumes:
       - type: bind
         source: ./data
         target: /data:z
```

podman-compose up leads to the following error:
`Error: invalid container path "s/run/secrets/config.json", must be an absolute path`

I have no idea where the "s" in the beginning of the path comes from.

I tried changing the secrets target to
`target: /run/secrets/config.json`

The error then reads:

```Error: unable to start container 3211d4a1271b48f53257ecc1283005786f1471aedd94bbd441defbd9c1175817: error stat'ing file `/home/dwalter/.local/share/containers/storage/volumes/secrets.json/_data`: No such file or directory: OCI runtime attempted to invoke a command that was not found```

So apparently now a folder is created instead of the json file.

Am I missing something obvious or is the behaviour regarding secrets different from docker-compose in a way that is not documented?

**Comment by muayyad-alsadi** [comment]
we had a test for this

https://github.com/containers/podman-compose/tree/devel/tests/secrets

it used to work but yes it's failing (I don't know since when)

I'll fix it
