### ISSUE TITLE
External named volume created even if not existing

### ISSUE THREAD

**Issue by ohxodi** [containers/podman-compose#441]
**Describe the bug**
When a non-existing volume is declared as `external` in the top-level volumes section, podman-compose creates this volume and launches the container without error.

As mentioned in [compose specs](https://github.com/compose-spec/compose-spec/blob/master/spec.md#external-1), `Compose implementations MUST NOT attempt to create these volumes, and MUST return an error if they do not exist.`

**To Reproduce**
Tested on latest devel branch with this docker-compose.yml file :
```yaml
version: '3.1'

services:
  app:
    image: busybox
    volumes:
      - external_vol:/mnt

volumes:
  external_vol:
    external: true
```

**Expected behavior**
When running `podman-compose up`, podman-compose shouldn't create the volume and should return an error.

**Actual behavior**
When running `podman-compose up`, podman-compose creates the volume and launches the container without error.

**Comment by muayyad-alsadi** [comment]
this was supposed to be handled
the code in line ~300 should detect if it's external and not creating it

```python
if mount_dict["type"] != "volume" or not vol or vol.get("external", None) or not vol.get("name", None):
    return
``

the problem, it should have throw an exception if it does not exist
because podman seems to create it when passed `podman run ... -v extvol_external_vol:/mnt ...`

I'll address this ASAP.

**Comment by Ram-Z** [comment]
Furthermore, the [spec says](https://github.com/compose-spec/compose-spec/blob/master/spec.md#external-1)

> In the example below, instead of attempting to create a volume called {project_name}_db-data, Compose looks for an existing volume simply called db-data and mounts it into the backend service's containers.
> ```
> services:
>   backend:
>     image: awesome/database
>     volumes:
>       - db-data:/etc/data
> 
> volumes:
>   db-data:
>     external: true
> ```

The current behaviour seems to create the volume `{project_name}_db-data` even though `db-data` exists as an external volume.

```
using podman version: 4.0.1
podman-composer version  1.0.3
podman --version 
podman version 4.0.1
```

**Comment by ohxodi** [comment]
I've made a PR to fix these issues.
For the first issue, I used the same syntax than the one used to deal with an exernal network :
https://github.com/containers/podman-compose/blob/9c29c8914f741b778060dedb15d1751755f91de8/podman_compose.py#L694-L698
For the second one, it only seems to be a wrong string format at line 195 (`{source}` instead of `{proj_name}_{source}` ):
https://github.com/containers/podman-compose/blob/9c29c8914f741b778060dedb15d1751755f91de8/podman_compose.py#L195
I've tested it locally and everything works fine on my side. 
I hope this could help.

**Comment by muayyad-alsadi** [comment]
I believe you still need something like

```
default_net_name = net if is_ext else f"{proj_name}_{net}"
```

You removed `{proj_name}_{source}` I believe it still needed for some cases just like network

**Comment by ohxodi** [comment]
I guess you're right, my second modification was not taking into account the simplest use-case :
```yaml
services:
  backend:
    image: awesome/database
    volumes:
      - db-data:/etc/data

volumes:
  db-data:
```
Even if I can't find the exact assertion describing it in the specs, docker-compose creates a volume with {proj_name}_{source} in such case.

I will update my PR ASAP.

**Comment by ohxodi** [comment]
I've updated PR #487.
Three cases are taken into account for volume name management :
- If an external volume with a specific name is defined -> take this name for `vol['name']`
- If an external volume is only defined with `true` -> take `{source}` for `vol['name']`
- If the volume is not external and no name is defined -> take `{proj_name}_{source}` for `vol['name']`

It works fine locally. I hope every use-cases are taken into account.
