### ISSUE TITLE
Support creating pods with `--infra=true`

### ISSUE THREAD

**Issue by jayache80** [containers/podman-compose#442]
**Is your feature request related to a problem? Please describe.**

When creating a pod, `podman-compose` is currently hard-coded to pass `--infra=false`. However, if it is desired to generate systemd service units from a pod, the `podman` will not do so unless the pod was created with `--infra=true`

**Describe the solution you'd like**

Provide a command line argument such that, if a pod is being created, allow the user to choose whether `--infra=true` or `--infra=false` is passed to the `podman pod create` command.

**Comment by muayyad-alsadi** [comment]
I've just pushed a fix, you can pass whatever pod creation arguments you want. the current default is `--infra=false --share=` you can make it `--infra=true --share=` or whatever you like

it's used like this

```
podman-compose --no-pod up -d
```

or

```
podman-compose --pod-args='--infra=true --share=''' up -d
```

**Comment by florinandone** [comment]
Looking at https://github.com/containers/podman-compose/tags there is no tag after December 2021, and this was implemented in March  2022 .

Is there any plan for a new release?
Can someone help with that?
Otherwise, what is the easiest way to take this?

**Comment by muayyad-alsadi** [comment]
we have release podman 1.0.6 with `--in-pod=0` or `--in-pod=1`
