### ISSUE TITLE
Should port allowed to be integer? Spec is not clear

### ISSUE THREAD

**Issue by sarim** [containers/podman-compose#449]
**Describe the bug**
Spec for ports: https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports

> Either specify both ports (HOST:CONTAINER), or just the container port. In the latter case, the Compose implementation SHOULD automatically allocate any unassigned host port.
> 
> HOST:CONTAINER SHOULD always be specified as a (quoted) string, to avoid conflicts with [yaml base-60 float](https://yaml.org/type/float.html).

When specifying just the container port, it is not explicitly told be make it a quoted string. A unquoted port number becomes integer. Which makes podman-compose error with: `TypeError("port should be either string or dict")`

**To Reproduce**
1. what is the content of the current working directory (ex. `docker-compose.yml`, `.env`, `Dockerfile`, ...etc.)
docker-compose.override.yml
```
version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
```

2. what is the sequence of commands you typed
```
podman-compose up -d
```

**Expected behavior**
To run without error.

**Actual behavior**
```
Traceback (most recent call last):
  File "/home/mcm/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/mcm/.local/lib/python3.8/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/home/mcm/.local/lib/python3.8/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/home/mcm/.local/lib/python3.8/site-packages/podman_compose.py", line 1169, in _parse_compose_file
    cnt["ports"] = norm_ports(cnt.get("ports", None))
  File "/home/mcm/.local/lib/python3.8/site-packages/podman_compose.py", line 545, in norm_ports
    raise TypeError("port should be either string or dict")
TypeError: port should be either string or dict
```

**Output**

```
$ podman-compose version
using podman version: 3.4.2
podman-composer version  1.0.3
podman --version
podman version 3.4.2
exit code: 0
```

**Environment:**
 - OS: Linux / WSL2
 - podman version: 3.4.2
 - podman compose version: (git hex) 3.4.2

**Additional context**

I didn't try the dev/git master version because the code is same https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L657 .

ref: https://github.com/symfony/recipes/pull/1068

**Comment by muayyad-alsadi** [comment]
I've just pushed a fix
