### ISSUE TITLE
rootless service docker-compose.override.yml not load 

### ISSUE THREAD

**Issue by eliteaz** [containers/podman-compose#450]
**Describe the bug**
systemd rootless `podman-compose` service not load docker-compose.override.yml
systemd unit file:
```
# /etc/systemd/system/podman.service
[Unit]
Description=Podman containers is controlled by a systemd service
After=network-online.target

[Service]
User=podman
Group=podman
ExecStart=/usr/bin/podman-compose -f "/home/podman/dockerfiles/podman/docker-compose.yaml" up
ExecStop=/usr/bin/podman-compose -f "/home/podman/dockerfiles/podman/docker-compose.yaml" down -v
LimitNOFILE=8192
Type=simple

[Install]
WantedBy=multi-user.target
```
after command `# systemctl start podman.service`  podman run containers properly but don't take environment variables from `docker-compose.override.yml`

when i run command `$ podman-compose up -d` being rootless under `podman` user containers runs properly and loads required variables from `docker-compose.override.yml`

Maybe there is some misconfiguration at systemd unit file ?

**Comment by muayyad-alsadi** [comment]
@eliteaz this is not a bug, you need to set `WorkingDirectory` in your systemd type `man 5 systemd.exec` for details.

you might want to try our new systemd unit in the latest devel branch we we are about to release

```
pip3 install --upgrade  https://github.com/containers/podman-compose/archive/devel.tar.gz
```

in that release we have good systemd integration

```
sudo loginctl enable-linger $USER
sudo podman-compose systemd --action create-unit
```

this will create a unit file with `@` magic like this `podman-compose@<PROJECT>`

to register a service for your compose stack, cd into that directory and type

```
podman-compose systemd --action register
```

now you can use systemd like this

```
systemctl --user enable --now 'podman-compose@{PROJ}'
systemctl --user start 'podman-compose@{PROJ}'
systemctl --user stop 'podman-compose@{PROJ}'
systemctl --user status 'podman-compose@{PROJ}'
journalctl --user -xeu 'podman-compose@{PROJ}'
```

it works like this

```
# /usr/lib/systemd/user/podman-compose@.service

[Unit]
Description=%i rootless pod (podman-compose)

[Service]
Type=simple
EnvironmentFile=%h/.config/containers/compose/projects/%i.env
ExecStartPre=-/home/alsadi/proj/podman-compose/podman_compose.py up --no-start
ExecStartPre=/usr/bin/podman pod start pod_%i
ExecStart=/home/alsadi/proj/podman-compose/podman_compose.py wait
ExecStop=/usr/bin/podman pod stop pod_%i

[Install]
WantedBy=default.target
```

the register command publish the env files in your home `EnvironmentFile=%h/.config/containers/compose/projects/%i.env`
which is used to create the pod without starting the containers, then it's started and waited

**Comment by eliteaz** [comment]
Thanks,
it perfectly works with `WorkingDirectory=` systemd unit setting
