### ISSUE TITLE
`.env` file entries not added to env vars of the running container.

### ISSUE THREAD

**Issue by typekpb** [containers/podman-compose#458]
`.env` file entries not added to env vars of the running container.

**To Reproduce**

Having the following docker-compose.yml:
```
version: "2.2"

services:
  example:
    image: ubuntu
    command: >
      bash -c '
        set | grep FOO
      '
```
and `.env` file with contents:
```
FOO=BAR
```

Once running `podman-compose up` there is no FOO=BAR printed.

**Expected behavior**
`.env` file loaded environment variables would be available in the container.

**Actual behavior**
`.env` file loaded environment variables are not available in the container.

**Output**

```
$ podman-compose version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.0.2
podman-composer version 1.0.4
podman --version
podman version 4.0.2
exit code: 0
```

**Environment:**
 - OS:  Mac
 - podman version: 4.0.2
 - podman compose version: `ebb3dfe6344a0f4938d0b4fa09d4dc33accc9d03`
  
  **Additional context**
  
Original motivation for running this is the ELK in podman-compose.yml use-case, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file. Therefor issue: https://github.com/containers/podman-compose/issues/424 could be closed once there would be no additional blockers.

**Comment by muayyad-alsadi** [comment]
this is not a bug

kindly use busybox or alpine (not ubuntu nor elastic ..etc) to save my laptop storage

I've just tested it on docker 

```
$ docker info | grep "Server Version"
 Server Version: 20.10.12
$ docker-compose -v
docker-compose version 1.27.4, build unknown
```

the following 

```yaml
---
version: "2.2"
services:
  example:
    image: busybox
    command: >
      sh -c '
        set | grep FOO
      '
```

```
$ echo 'FOO=BAR' > .env
$ docker-compose up
Starting envtest_example_1 ... done
Attaching to envtest_example_1
envtest_example_1 exited with code 1
```

the env is not set on docker too. we match the behavior

if you want to load it you need to define it in your docker-compose file or docker-compose.override.yaml ..etc.

like this 

```
---
version: "2.2"
services:
  example:
    image: busybox
    env_file: .env
    command: >
      sh -c '
        set | grep FOO
      '
```

or this

```
---
version: "2.2"
services:
  example:
    image: busybox
    environment:
    - FOO
    command: >
      sh -c '
        set | grep FOO
      '
```


```
---
version: "2.2"
services:
  example:
    image: busybox
    environment:
    - FOO=${FOO}
    command: >
      sh -c '
        set | grep FOO
      '
```

...etc.

this is how both docker-compose and podman-compose work

**Comment by muayyad-alsadi** [comment]
if your problem is related to resolving hosts please make sure to install podman dns plugin

**Comment by Elkasitu** [comment]
That is very weird, according to the docs it's supposed to work [implicitly](https://docs.docker.com/compose/environment-variables/) (see third paragraph), I can't test it right now so I'll do that whenever I can.

@muayyad-alsadi alternatively, would you be opposed to `podman-compose` supporting an `--env-file` option? I see that `podman` supports it so there would be very little logic implemented in `podman-compose`.
