### ISSUE TITLE
"podman-compose -t identity -p somename up" does not work anymore

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#459]
**Describe the bug**
According to my doc I used to run `podman-compose -t identity -p somename up` and it works. It does not work anymore now for some reason…

I wanted to run this in identity network mode, so no isolation is done.

**To Reproduce**
```bash
$ podman-compose -t identity -p somename up
usage: podman-compose [-h] [-v] [-f file] [-p PROJECT_NAME] [--podman-path PODMAN_PATH] [--podman-args args] [--podman-pull-args args] [--podman-push-args args] [--podman-build-args args]
                      [--podman-inspect-args args] [--podman-run-args args] [--podman-start-args args] [--podman-stop-args args] [--podman-rm-args args] [--podman-volume-args args]
                      [--no-ansi] [--no-cleanup] [--dry-run]
                      {help,version,pull,push,build,up,down,ps,run,exec,start,stop,restart,logs} ...
podman-compose: error: argument command: invalid choice: 'identity' (choose from 'help', 'version', 'pull', 'push', 'build', 'up', 'down', 'ps', 'run', 'exec', 'start', 'stop', 'restart', 'logs')
```

I also tried this considering I may have mixed up the order of the arguments:
```bash
$ podman-compose up -t identity -p somename
usage: podman-compose up [-h] [-d] [--no-color] [--quiet-pull] [--no-deps] [--force-recreate] [--always-recreate-deps] [--no-recreate] [--no-build] [--no-start] [--build]
                         [--abort-on-container-exit] [-t TIMEOUT] [-V] [--remove-orphans] [--scale SERVICE=NUM] [--exit-code-from SERVICE] [--pull] [--pull-always] [--build-arg key=val]
                         [--no-cache]
                         [services ...]
podman-compose up: error: argument -t/--timeout: invalid float value: 'identity'
```

**Expected behavior**
Start pod/container.

I also know the doc https://github.com/containers/podman-compose/blob/devel/docs/Mappings.md that documents the value I want to use, however, it does _not_ actually document what switch I need to use for that… :upside_down_face: 

**Actual behavior**
see above

**Output**

```
$ podman-compose version
podman-compose version
['podman', '--version', '']
using podman version: 3.4.4
podman-composer version  1.0.3
podman --version 
podman version 3.4.4
exit code: 0

# (that works of course)
$ podman-compose up
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
['podman', 'network', 'exists', '****default']
podman create --name=***_*****_1
...

```

**Environment:**
 - OS: Linux / Fedora x86_64 CoreOS 35.20220227.3.0
 - podman version: 3.4.4
 - podman compose version: (git hex) N/A

**Additional context**

I also obviously checked `podman-compose --help` and `podman-compose up --help` and see the `-t` parameter is now some timeout thiny, however, I also don't see the parameter I want being listed there…

**Comment by muayyad-alsadi** [comment]
Identity is the new default. You don't need to pass it.

Podman v3 supports podman network create and it has dns plugin, please make sure to install it.

**Comment by muayyad-alsadi** [comment]
This is documented in versions section of readme

https://github.com/containers/podman-compose#versions

**Comment by rugk** [comment]
> Identity is the new default. You don't need to pass it.

Ah okay, great Though then the question stands how does one use another mode, because the CLi always gave me syntax errors…

> Podman v3 supports podman network create and it has dns plugin, please make sure to install it.

Hmm, AFAIK this is only required for resolving namespaces in the container? Do I really need that and how is it related to this issue?
Also, how can I check whether it is already installed or not? Maybe `podman-compose` could display a warning (for anything i6t does) when one uses podman >= 3 and it is not installed? Or shall I open a new issue for that?

**Comment by rugk** [comment]
BTW I guess for me it is preinstalled in Fedora CoreOS or given as a dependency for `podman-compose`, so no need to install separately, apparently:
```
$ sudo rpm-ostree install podman-plugins
[sudo] password for admrugk: 
error: "podman-plugins" is already provided by: podman-plugins-3:3.4.4-1.fc35.x86_64. Use --allow-inactive to explicitly require it.
```

**Comment by rugk** [comment]
So [I asked my distro community what is uphere](https://discussion.fedoraproject.org/t/podman-dns-plugin-in-wrong-version-in-fedora-coreos-36-podman-plugins-podman-dnsname/39493?u=rugk). I have `podman-plugins` installed, and don't know whether there is still sth. to configure (see link), but (new) podman-compose containers still cannot resolve anything here.

**Comment by rugk** [comment]
I've summarized my problem and the solution now here [in this post in the Fedora Discussion forum](https://discussion.fedoraproject.org/t/how-to-get-podman-dns-plugin-container-name-resolution-to-work-in-fedora-coreos-36-podman-plugins-podman-dnsname/39493/6?u=rugk).
