### ISSUE TITLE
[docs] add man page

### ISSUE THREAD

**Issue by heitorPB** [containers/podman-compose#460]
**Is your feature request related to a problem? Please describe.**
There are many man pages for Podman, but `podman-compose` is lacking one.

**Describe the solution you'd like**

`man 1 podman-compose`

**Describe alternatives you've considered**
`podman-compose --help` exists and is helpful, but man pages usually are more complete and contain examples.

**Additional context**

[Debian policy manual](https://www.debian.org/doc/debian-policy/ch-docs.html) asks for man pages for all packages.

**Comment by muayyad-alsadi** [comment]
When I took part in some debian packaging we had some sort of help to man pages

I can't remember the tool name.

**Comment by heitorPB** [comment]
I know Pandoc can generate man pages from markdown and other formats, and Sphinx can also generate them. Was it one of these?

**Comment by muayyad-alsadi** [comment]
help2man

> [You can use the help2man command to generate a man page out of the --help and --version output of each program, too. ]()[[56]](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#ftn.idm2409)

https://www.debian.org/doc/manuals/maint-guide/dother.en.html

**Comment by heitorPB** [comment]
Do you think this should be done when packaging instead?

**Comment by muayyad-alsadi** [comment]
for now at least
