### ISSUE TITLE
Mounting /var/run/docker.sock created by podman-mac-helper

### ISSUE THREAD

**Issue by shoeffner** [containers/podman-compose#486]
**Describe the bug**

`/var/run/docker.sock` is not mounted correctly on macOS.
`/var/run/docker.sock` is a link created by podman-mac-helper using `sudo /opt/homebrew/Cellar/podman/4.0.3/bin/podman-mac-helper install` and points to `/Users/shoeffner/.local/share/containers/podman/machine/podman.sock` which in turns points to `/Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock`.
The docker.sock has root:daemon ownership, the podman.sock link and podman.sock shoeffner:staff.

When mounting `/var/run/docker.sock`, the link is resolved and `/Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock` is mounted instead. This results in:
Error: statfs /Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock: network dropped connection on reset

However, when I create the container manually and mount the non-resolved link, it works (see below).

**To Reproduce**
Run this docker-compose yaml:

```yaml
version: "3.4"

services:
  app:
    image: docker:dind
    command: docker run busybox echo hi 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    privileged: true
```

```console
$ docker-compose up
```

**Expected behavior**
```log
['podman', '--version', '']
using podman version: 4.0.3
** excluding:  set()
['podman', 'network', 'exists', 'test_default']
podman create --name=test_app_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=test --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=test --label com.docker.compose.project.working_dir=/Users/shoeffner/Projects/test --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=app -v /var/run/docker.sock:/var/run/docker.sock:rw --net test_default --network-alias app --privileged docker:dind docker run busybox echo hi
e78337b61279521ddc0897f97780736b903f9c1091ee4838deb26596506ef4c2
exit code: 0
podman start -a test_app_1
hi
exit code: 0
```

**Actual behavior**

Container is not starting:

```
['podman', '--version', '']
using podman version: 4.0.3
** excluding:  set()
['podman', 'network', 'exists', 'test_default']
podman create --name=test_app_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=test --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=test --label com.docker.compose.project.working_dir=/Users/shoeffner/Projects/test --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=app -v /Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock:/var/run/docker.sock:rw --net test_default --network-alias app --privileged docker:dind docker run busybox echo hi
Error: statfs /Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock: network dropped connection on reset
exit code: 125
podman start -a test_app_1
Error: no container with name or ID "test_app_1" found: no such container
exit code: 125
```

**Output**

```
$ podman-compose version
['podman', '--version', '']
using podman version: 4.0.3
podman-composer version  1.0.3
podman --version 
podman version 4.0.3
exit code: 0

$ podman-compose up
['podman', '--version', '']
using podman version: 4.0.3
** excluding:  set()
['podman', 'network', 'exists', 'test_default']
podman create --name=test_app_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=test --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=test --label com.docker.compose.project.working_dir=/Users/shoeffner/Projects/test --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=app -v /Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock:/var/run/docker.sock:rw --net test_default --network-alias app --privileged docker:dind docker run busybox echo hi
Error: statfs /Users/shoeffner/.local/share/containers/podman/machine/podman-machine-default/podman.sock: network dropped connection on reset
exit code: 125
podman start -a test_app_1
Error: no container with name or ID "test_app_1" found: no such container
exit code: 125
```

**Environment:**
 - OS: Mac M1, macOS 12.3.1
 - podman version: 4.0.3
 - podman compose version: unsure, installed via pipx

**Additional context**

The "problem" seems to be the `os.path.realpath` in 
https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L133-L135
I fixed my local copy to simply not use `os.path.realpath` if the source name is `/var/run/docker.sock`, but I am not sure what the correct way is. Maybe sockets should be left as is, but files/directories etc. resolved?

**Comment by muayyad-alsadi** [comment]
please note that podman-compose is design to be daemon-less. this is the key value of using it against `docker-compose` along with being rootless. that is podman-compose just call podman which just create the containers with the current user. no socket is involved.

> I fixed my local copy to simply not use os.path.realpath if the source name is /var/run/docker.sock, but I am not sure what the correct way is. Maybe sockets should be left as is, but files/directories etc. resolved?

it seems that you don't want the file to be resolved, so that it would inside the VM (podman machine)
before I remove `os.path.realpath`  I need to make sure it won't break things.

**Comment by shoeffner** [comment]
It is quite common to mount /var/run/docker.sock if the containers are supposed to do some work with docker itself (e.g., docker-in-docker as shown here, portainer, or other container management tools built around docker).

So while podman does not use any sockets, the docker command inside the container uses the compatibility docker.sock to control podman on the host system.

Again, I am not sure myself if not using `os.path.realpath` is the way to go here, as I expect it to work better/less surprising when resolving the links, but in this case it bit me (and I actually do not know why exactly mounting the podman.sock as `/var/run/docker.sock` does not work. 
Maybe this is fighting symptoms instead of tackling the root problem, that it is not possible to mount podman.sock (which in turn might not be related to podman-compose, but a podman issue, now that I think about it).

**Comment by muayyad-alsadi** [comment]
> and I actually do not know why exactly mounting the podman.sock as /var/run/docker.sock does not work

Because your docker.sock points to two different locations one inside your mac and the other inside the VM (Podman machine). Podman compose which is running inside your mac interpret it differently than podman inside the vm.

**Comment by shoeffner** [comment]
Thanks for the explanation! I will stick to my workaround when I need it for now, it's not important to solve it soon, I guess :)

**Comment by muayyad-alsadi** [comment]
please test.

**Comment by shoeffner** [comment]
Works well, thank you!
