### ISSUE TITLE
Is it compatible with podman 4?

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#495]
Podman v4 has been release including breaking changes: https://podman.io/releases/2022/02/22/podman-release-v4.0.0.html

Is podman-compose already compatible with it?

**Comment by mluhmann** [comment]
I am working with it since some weeks and didn't had any problems. But I didn't test anything specific, I just changed podman-compose to the current devl branch and continued my work. A release/tag or update of the stable with 1.0.4 would be nice.

**Comment by rugk** [comment]
So the released version may actually _not_ be compatible yet then… :upside_down_face:

**Comment by muayyad-alsadi** [comment]
Both are compatible. But the devel branch has more features.

**Comment by stanfieldr** [comment]
On Fedora 36 it's tricky. I had to install `containernetworking-plugins` package to make podman-compose work.

This is basically the problem I had. The first ls works great, but as soon as I run podman-compose up it creates, if I understand correctly, an old network stack config file.

Not sure if this is expected behavior or not, but something to be aware of...

```
[robert@fedora thumbstopper]$ podman network ls
NETWORK ID    NAME        DRIVER
2f259bab93aa  podman      bridge
[robert@fedora thumbstopper]$ podman-compose up -d
['podman', '--version', '']
using podman version: 4.1.0
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'thumbstopper_curator']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'thumbstopper_lister']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'thumbstopper_main']
['podman', 'network', 'exists', 'thumbstopper_thumbstopper']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=thumbstopper', '--label', 'com.docker.compose.project=thumbstopper', 'thumbstopper_thumbstopper']
['podman', 'network', 'exists', 'thumbstopper_thumbstopper']
WARN[0000] Error validating CNI config file /var/home/robert/.config/cni/net.d/thumbstopper_thumbstopper.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 562, in assert_cnt_nets
    try: compose.podman.output([], "network", ["exists", net_name])
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 819, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'thumbstopper_thumbstopper']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1023, in run
    cmd(self, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1247, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1414, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 644, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 579, in assert_cnt_nets
    compose.podman.output([], "network", ["exists", net_name])
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 819, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'thumbstopper_thumbstopper']' returned non-zero exit status 1.
[robert@fedora thumbstopper]$ podman network ls
WARN[0000] Error validating CNI config file /var/home/robert/.config/cni/net.d/thumbstopper_thumbstopper.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
NETWORK ID    NAME        DRIVER
2f259bab93aa  podman      bridge
[robert@fedora thumbstopper]$
```

**Comment by muayyad-alsadi** [comment]
maybe `podman system reset -f` or something like it

**Comment by rugk** [comment]
@stanfieldr So maybe this is the same problem I have? See https://github.com/containers/podman-compose/issues/459 and https://github.com/containers/podman-compose/issues/500 and links. 

So if you have any idea or the issue is the same, feel free to answer/comment it [on this forum thread](https://discussion.fedoraproject.org/t/podman-dns-plugin-in-wrong-version-in-fedora-coreos-36-podman-plugins-podman-dnsname/39493?u=rugk), especially.

**Comment by muayyad-alsadi** [comment]
according to [this article](https://www.redhat.com/sysadmin/podman-new-network-stack)
you need to install aardvark-dns as part of netavark and configure it in  `containers.conf` file as `network_backend` field.

I hope this is useful

**Comment by rugk** [comment]
Hmm, it seems Netavark/Aardvark can be used as an altername to the dnsname plugin/CNI that podman uses by default.
However, I personally would be fine with CNI if that works.

**Comment by muayyad-alsadi** [comment]
I've just tried fresh installation of fedora 36 workstation (not upgrade), and it works fine

it got `containers-common` which pulls `container-network-stack` which installs `netavark`
the config file is found on `/usr/share/containers/containers.conf`

```
# rpm -qR containers-common
(container-selinux >= 2:2.162.1 if selinux-policy)
config(containers-common) = 4:1-53.fc36
container-network-stack

# rpm -q --whatprovides container-network-stack
netavark-1.0.2-1.fc36.x86_64
# rpm -qa '*aardvark*'
aardvark-dns-1.0.2-1.fc36.x86_64
# rpm -qf  /usr/share/containers/containers.conf 
containers-common-1-53.fc36.noarch
# podman info | grep -i -A3 net
  networkBackend: netavark
```

**Comment by muayyad-alsadi** [comment]
Try to remove containernetworking-plugins so that you only have  netavark
And then have `podman info | grep -i -A3 net` it instead of cni
Because this is the default setup

**Comment by rugk** [comment]
I just overwrote/configured my `/etc/containers/containers.conf` to use netavark instead of CNI and got it working.
The package you mentioned was not layered by me (explicitly at least), so it would actually not be the default if I remove it from the base system now.

**Comment by rugk** [comment]
>A release/tag or update of the stable with 1.0.4 would be nice.

I totally agree! I just stumbled upon [the issue that 1.0.3](
https://github.com/containers/podman-compose/issues/504#issuecomment-1152717780) does not generate a pod anymore and only not yet released 1.0.4 can. So yeah, that's what you meant with new features…

As such, I agree a release would be very nice!

**Comment by muayyad-alsadi** [comment]
it seems that in your case `containernetworking-plugins-1.1.0-1.fc36.x86_64` is carried from an upgrade not from the default.
the default silverblue 36 and the default workstation 36 have only one network stack that is `netavark` and since it's only one, it uses it instead of the CNI.

the default fedora 36 is both workstation and silverblue works fine.

**Comment by rugk** [comment]
The package is not a problem, the thing is just podman will always choose legacy CNI unless you have a fresh installation/fresh podman setup, basically, [as the docs explain](https://github.com/containers/common/blob/main/docs/containers.conf.5.md#network-table):
> The default value is empty which means that it will automatically choose CNI or netavark. If there are already containers/images or CNI networks preset it will choose CNI.

I've summarized this now here [in this post in the Fedora Discussion forum](https://discussion.fedoraproject.org/t/how-to-get-podman-dns-plugin-container-name-resolution-to-work-in-fedora-coreos-36-podman-plugins-podman-dnsname/39493/6?u=rugk).

---

Anyway, I guess this question was answered, so I'll close this issue.
