### ISSUE TITLE
How to use the old networking behaviour? (with --add-host and without --net/--network-alias)

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#500]
**Describe the bug**
New podman-compose versions do not add`--add-host` anymore and seem to have changed all networking stuff.-

Why does not it do `--add-host` anymore?
Also the new version seems to some `--net […] --network-alias […]` out of my network directive in docker-compose. 

**To Reproduce**
In the old systemd service I saw commands like this being passed/added to podman like this:
```
--add-host nc:127.0.0.1 --add-host nextcloud_nc_1:127.0.0.1 […}
```

And I can still start these services and they work properly.

The new one now does this:
```
--net […] --network-alias […]
```

None of the command lines (nether old nor new behaviour) here needed/used podman's `--network` parameter, even though I tried changing it to 

As the [`-t` parameter](https://github.com/containers/podman-compose/issues/459) also does not work and I found no replacement in `podman-compose --help` or `podman-compose up --help`  about how I am supposed to revert to the old behaviour now?

**Expected behavior**
A way to revert to `1podfw` or other [mappings](https://github.com/containers/podman-compose/blob/d38aeaa7130cfd7f93341a09460fba9ac7e4c2a5/docs/Mappings.md).

**Actual behavior**
No way found.

**Output**

```
$ podman-compose version
['podman', '--version', '']
using podman version: 4.0.2
podman-composer version  1.0.3
podman --version 
podman version 4.0.2
exit code: 0
```

**Environment:**
 - OS: Linux
 - podman version: 4.0.2
 - podman compose version: N/A

**Additional context**

I tried `podman-compose --podman-run-args '--add-host nc:127.0.0.1 --add-host […]' -p nextcloud up`, which obviously properly added the missing directives, but I guess I have no way of _removing_ the directives manually that were too much. Also, that would be an ugly workaround of course.

I also tried passing `1podfw` as `network_mode` in my docker-compose file, but this ended in an error that obviously shows this is the wrong place for that:
> Error: unable to find network with name or ID 1podfw: network not found

The reason is podman-compose tries to pass it as ` --network 1podfw` instead of changing it's internal way of working.

Even with `host` BTW it does not work yet again, because:
> Error: cannot set multiple networks without bridge network mode, selected mode host: invalid argument

(Because I have set multiple networks in `network`.)

**Comment by muayyad-alsadi** [comment]
Please make sure you have dns plugin installed as in the readme because --add-host workaround is no longer needed. It's handled by the dns.

**Comment by muayyad-alsadi** [comment]
Let's try the following

1. Remove all containers
2. Reset settings
3. Try a simple yaml with a single network like those in examples or tests directories

**Comment by rugk** [comment]
It's installed, [see here](https://github.com/containers/podman-compose/issues/459#issuecomment-1079497215).

> because --add-host workaround is no longer needed

Well… as for this issue, it would have been great if I was able to still use it, because it actually does not work for me. I keep referring to https://github.com/containers/podman-compose/issues/459.

> Try a simple yaml with a single network like those in examples or tests directories

Tried that:
https://github.com/containers/podman-compose/tree/2c60516f77b79371634b9ac573a1ec4238a53422/tests/nets_test1

And it worked:
```
$ podman-compose up
['podman', '--version', '']
using podman version: 4.0.2
** excluding:  set()
['podman', 'network', 'exists', 'nets_test1_default']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=nets_test1', '--label', 'com.docker.compose.project=nets_test1', 'nets_test1_default']
['podman', 'network', 'exists', 'nets_test1_default']
podman create --name=nets_test1_web1_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=nets_test1 --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=nets_test1 --label com.docker.compose.project.working_dir=/var/home/admrugk/podman-test/nets_test1 --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web1 -v /var/home/admrugk/podman-test/nets_test1/test1.txt:/var/www/html/index.txt:z,ro --net nets_test1_default --network-alias web1 -p 8001:8001 -w /var/www/html --hostname web1 busybox /bin/busybox httpd -f -h /var/www/html -p 8001
Resolved "busybox" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/busybox:latest...
Getting image source signatures
Copying blob 462eb288b104 done  
Copying config 3fb5cabb64 done  
Writing manifest to image destination
Storing signatures
c085b230bcd57fa892012070545ac729b816266d78c4b2b81cd6a193b8708385
exit code: 0
['podman', 'network', 'exists', 'nets_test1_default']
podman create --name=nets_test1_web2_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=nets_test1 --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=nets_test1 --label com.docker.compose.project.working_dir=/var/home/admrugk/podman-test/nets_test1 --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web2 -v /var/home/admrugk/podman-test/nets_test1/test2.txt:/var/www/html/index.txt:z,ro --net nets_test1_default --network-alias web2 -p 8002:8001 -w /var/www/html --hostname web2 busybox /bin/busybox httpd -f -h /var/www/html -p 8001
a5da3515de9781fc0973b507f18ad790cd9fcf913d8445b00dca6defb7980804
exit code: 0
podman start -a nets_test1_web1_1
podman start -a nets_test1_web2_1
```

In another shell:
```
$ curl localhost:8001/index.txt
test1
$ curl localhost:8002/index.txt
test2
```

**Comment by rugk** [comment]
Okay but that  example has no network connectivity between the containers, so no dnsname resolving involved.

I tried [this here now](https://github.com/containers/podman-compose/tree/4557279930927149e8d9a1d601ef0cd49e252452/tests/nets_test3):
```
$ podman-compose up
['podman', '--version', '']
using podman version: 4.0.2
** excluding:  set()
['podman', 'network', 'exists', 'nets_test3_net1']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=nets_test3', '--label', 'com.docker.compose.project=nets_test3', 'nets_test3_net1']
['podman', 'network', 'exists', 'nets_test3_net1']
podman create --name=nets_test3_web1_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=nets_test3 --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=nets_test3 --label com.docker.compose.project.working_dir=/var/home/admrugk/podman-test/nets_test3 --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web1 -v /var/home/admrugk/podman-test/nets_test3/test1.txt:/var/www/html/index.txt:z,ro --net nets_test3_net1 --network-alias web1 -p 8001:8001 -w /var/www/html --hostname web1 busybox /bin/busybox httpd -f -h /var/www/html -p 8001
21b90b12afa94684838953e01f90d48383add889860411bb9eb253623790220d
exit code: 0
['podman', 'network', 'exists', 'nets_test3_net1']
['podman', 'network', 'exists', 'nets_test3_net2']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=nets_test3', '--label', 'com.docker.compose.project=nets_test3', 'nets_test3_net2']
['podman', 'network', 'exists', 'nets_test3_net2']
podman create --name=nets_test3_web2_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=nets_test3 --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=nets_test3 --label com.docker.compose.project.working_dir=/var/home/admrugk/podman-test/nets_test3 --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web2 -v /var/home/admrugk/podman-test/nets_test3/test2.txt:/var/www/html/index.txt:z,ro --net nets_test3_net1,nets_test3_net2 --network-alias web2 -p 8002:8001 -w /var/www/html --hostname web2 busybox /bin/busybox httpd -f -h /var/www/html -p 8001
a1478b1b754be140a868f6170c914eecfdb49f8f9d66fae898b0b46f8823de61
exit code: 0
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1023, in run
    cmd(self, args)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1247, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 1414, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 644, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/usr/lib/python3.10/site-packages/podman_compose.py", line 557, in assert_cnt_nets
    net_desc = nets[net] or {}
KeyError: "net1={'aliases': ['alias11', 'alias12']}"

```

**Comment by rugk** [comment]
Also in the [`nets_test1`](https://github.com/containers/podman-compose/tree/2c60516f77b79371634b9ac573a1ec4238a53422/tests/nets_test1) example again:

If I do `podman exec -it nets_test1_web1_1 /bin/sh` and try to connect to the other container, that fails:
```
/var/www/html # wget web1
Connecting to web1 (10.89.0.4:80)
wget: can't connect to remote host (10.89.0.4): Connection refused
/var/www/html # wget web2
Connecting to web2 (10.89.0.5:80)
wget: can't connect to remote host (10.89.0.5): Connection refused
```

Of course, and AFAIK, that's to be expected, this also does not work:
```
# wget localhost:8002/index.txt
Connecting to localhost:8002 (127.0.0.1:8002)
wget: can't connect to remote host (127.0.0.1): Connection refused
# wget localhost:8001/index.txt
Connecting to localhost:8001 (127.0.0.1:8001)
wget: can't open 'index.txt': File exists
```

(The last error is also expected, I am literally connecting to my own localhost web server and the file exists already, so not a problem here.)

Well… okay, they are also not linked in the docker-compose? Or not, because in the default network each container should be able to speak to each other?

**Comment by muayyad-alsadi** [comment]
> Okay but that example has no network connectivity between the containers, so no dnsname resolving involved.

it has the default network, look closely and you see

```
['podman', 'network', 'create', '--label', 'io.podman.compose.project=nets_test1', '--label', 'com.docker.compose.project=nets_test1', 'nets_test1_default']

podman create --name=nets_test1_web1_1 .... --net nets_test1_default --network-alias web1 ...
```

the `--network-alias web1` should tell the dns to resolve this container as web1

you can try the following from inside the container (NOTE: 8001 because both containers use that port, not to be confused with host port)

```
wget -O - http://web1:8001/index.txt
wget -O - http://web2:8001/index.txt
```

**Comment by rugk** [comment]
I've summarized my problem and the solution now here [in this post in the Fedora Discussion forum](https://discussion.fedoraproject.org/t/how-to-get-podman-dns-plugin-container-name-resolution-to-work-in-fedora-coreos-36-podman-plugins-podman-dnsname/39493/6?u=rugk).

**Comment by munterfi** [comment]
Unfortunately the proposed solution with **podman-compose** and **netavark** as network backend did not solve the issue of connecting between containers in the same network on RHEL 8.6 (Ootpa) with the versions:

```txt
aardvark-dns-1.0.1
netavark-1.0.1
podman-4.1.1
podman-compose-1.0.4
podman-plugins-4.1.1
```

Setting CNI as the network backend again and resetting podman worked for rootless mode:

1. Stop and remove all pods / containers: `podman-compose down` and verify `podman ps -a`
2. Install or upgrade to versions:

    ```txt
    podman-4.1.1
    podman-compose-1.0.4
    podman-plugins-4.1.1
    ```

    Since podman-compose-1.0.4 is not yet released, install the latest development version from GitHub:

    ```sh
    pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
    ```

3. Set network backend to CNI in `$HOME/.config/containers/containers.conf` as the user for rootless mode:

    ```ìni
    [network]
    network_backend = "cni"
    ```

4. Delete eventually existing network configuration files for CNI backend in `$HOME/.config/cni/net.d`.
5. Reset podman `podman system reset` (removes all pods, containers, images, networks and volumes, and machines).
6. Restart: `podman-compose up -d`

Now it should be possible to access containers from another container in same network using the service name and exposed port from the `docker-compose.yaml`, e.g. in a `nginx.conf`:

```txt
events { }
http {
    ...
    server {
        ...
        location / {
            proxy_pass http://<SERVICE_NAME>:<PORT>;
            proxy_redirect http://<SERVICE_NAME>:<PORT>/ $scheme://$http_host/;
            ...
        }
    }
}
```

**Comment by auqf** [comment]
I use the podman-compose to run multi containers,but the containers cannot comminicate by the service name

![image](https://github.com/containers/podman-compose/assets/8895540/dc8283db-198d-423e-a54e-a98289345924)
![image](https://github.com/containers/podman-compose/assets/8895540/59bcd241-fa1f-4f79-845f-0343a817708b)
