### ISSUE TITLE
podman-compose doesn't work

### ISSUE THREAD

**Issue by k19810703** [containers/podman-compose#508]
**Describe the bug**

I installed podman-compose using below command.
```
curl -o /usr/local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/devel/podman_compose.py
chmod +x /usr/local/bin/podman-compose
```

but podman-compose doesn't work on my MAC

**Output**

```
$ podman-compose --version
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 36, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Environment:**
 - OS:Mac
 - podman version: 4.1.1

Please advice how to fix it.

**Comment by muayyad-alsadi** [comment]
install it via pip as mentioned in the README

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by Mist-Hunter** [comment]
> install it via pip as mentioned in the README
> 
> ```
> pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
> ```

I'm new to podman-compose and followed your README. Thanks for the reply here directing users to install via pip3 which I will do. Should your REAME be updated to not include the 'or' [examples](https://github.com/containers/podman-compose#installation), which do seem broken? I get the same error as the [OP](https://github.com/containers/podman-compose/issues/508#issue-1278535081)

```
curl -o /usr/local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/devel/podman_compose.py
chmod +x /usr/local/bin/podman-compose
```
