### ISSUE TITLE
Killing container with ctrl+c 

### ISSUE THREAD

**Issue by supermar1010** [containers/podman-compose#51]
Hi,
I just switched from docker and docker-compose to podman and podman-compose :)
With docker-compose if you started the container with `docker-compose up` and then press Ctrl+C the container will be stopped the same happens in podman-compose. But if I try to restart the container via `podman-compose up` an error message occurs that the container is already existent. Then I have to manually do `podman-compose down'. 
Do you think it would be possible to mimic the docker-compose behaviour?

With best regards and thanks for podman-compose 
Mario

**Comment by muayyad-alsadi** [comment]
> But if I try to restart the container via podman-compose up an error message occurs that the container is already existent. 

I guess that error is just a warning
It's supposed to work.

I actually don't do any check
I create it, then attach to it.
if it's already exist, it should just work.

**Comment by supermar1010** [comment]
No its not restarted at least in my tests. If I p-c up and then ctrl+c and p-c up again, it still has the same log messages as before, so you it seems like you attach to the old container, but you are not actually starting it again, because it is still running? I'm not entirely sure but thats what it seems to do.

**Comment by muayyad-alsadi** [comment]
got it, thank you, I'll fix that soon

**Comment by muayyad-alsadi** [comment]
it seems that every thing is working fine, for example

while standing on devel branch

```
$ cd tests/simple
$ ../../podman_compose.py up
....
CTRL+C
$ podman stop -t=1 simple_web_1
$ ../../podman_compose.py up
```

as you can see it called

```
podman start -a simple_web_1
```

the code already does what you asked for
https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L999

```
        thread = Thread(target=compose.podman.run, args=[['start', '-a', cnt['name']]], daemon=True)
```

please make sure you are using latest devel branch

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by supermar1010** [comment]
Ok now it works, thank you :)
