### ISSUE TITLE
Parsing host environment variables to the yaml.

### ISSUE THREAD

**Issue by idrisFoughali** [containers/podman-compose#515]
**Describe the solution you'd like**
Prior to starting my migrations to podman and podman-compose, I was able to do the following:
```yaml
---
version: '3.7'
services:
  test:
    image: rocky:$VERSION
    container_name: $CONTAINER_NAME
````

on my host, I would set my variables:
```console
VERSION=8
CONTAINER_NAME=my container
````

then by doing:
```console
docker-compose up
```
My variables will build the container with those variables.

This unfortunately fails to work with podman-compose, the variables appear to be blank:
After running:
```console
podman-compose up
```
The result of ```console podman-compose config``` is:
```console
services:
  test:
    image: ''
    container_name: ''
```

**Describe alternatives you've considered**
The alternatives would be to manually write the values for each automated build...
Or, sed the values.

**Comment by muayyad-alsadi** [comment]
Are you sure you did not forget your .env file

**Comment by idrisFoughali** [comment]
the env file should only provision the container itself.

during build time though, the container is still non-existent, therefore the environment variables are still unused.

In the example that I have provided, the goal was to be able to build a specific image tag, or pull a specific image tag with the use of a variable inside the compose file instead of a static value.

the alternative would've been:

```console
services:
  test:
    image: rocky:8
```

but in my example scenario, I'm provide the value 8 as my env variable ``` VERSION ```, this variable is in the namespace of my host, the build will fail if the value is not set, or at least that would be the normal behaviour in docker-compose.

But with podman-compose, it seems that variables don't even get parsed.

**Comment by muayyad-alsadi** [comment]
passing envs is implemented in podman-compose and is tested here

https://github.com/containers/podman-compose/tree/devel/tests/interpolation

please double check your setup

**Comment by idrisFoughali** [comment]
Again, the variables on the examples you linked are env variables for the container.

From your example, if you replace for example:

```yaml
version: "3.7"
services:
    variables:
        image: busybox
```

By the following:
```yaml
version: $MY_YAML_VERSION
services:
    variables:
        image: $MY_IMAGE
```

upon running podman-compose on the following file, the build fails.


These variables should be set within the host, the container's build itself can't be executed, thus .env file is not the solution here, but the way the podman-compose interprets the yaml file, which as it seems for now, it excludes reading env variables that have been set from the host.

**Comment by idrisFoughali** [comment]
again I'm not talking about the container's environment...

I welcome you to read my example again and try to reproduce it.

another example:
``yaml
services:
  my_service:
    container_name: $FOO
    image: $IMAGE
```

This is my test scenario, runing docker-compose on this works, here's the output from my build using docker-compose:

```yaml
services:
  my_service:
    container_name: bar
    image: busybox
```

on my host, the result of printenv contains:

```yaml
IMAGE=busybox
FOO=bar
```

Again, I'm not talking about the container's namespace variables. But the variables describing the container's namespace; such as the image tag, mounting volume dynamically using variables instead of statically on the docker-compose file, etc.

You're example are limited to the env file of the container.

**Comment by idrisFoughali** [comment]
After some further tests on both macos and linux (rocky 8), it seems that the issue is completely unrelated to ```podman-compose```, I finally got it working.


All I had to do was source my bash script which builds the podman-compose file and export my variables from the script, unlike on linux where the export was only optional, as long as the variables were set.

**Comment by kuanyui** [comment]
@ifoughal 
On Linux, I still cannot get env var of host inside `compose.yml`... Donno why:

```yml
services:
  myservice:
    build:     # https://docs.docker.com/compose/compose-file/build/
      context: ./container
      dockerfile: Dockerfile
      args:
        - HOST_UID=${UID}
        - HOST_GID=${GID}
```

And in Dockerfile:
```dockerfile
FROM debian:bookworm

ARG HOST_UID
ENV HOST_UID ${HOST_UID}

ARG HOST_GID
ENV HOST_GID ${HOST_GID}

RUN useradd --create-home --shell /bin/bash --gid $HOST_GID --uid $HOST_UID user
```

..........

> All I had to do was source my bash script which builds the podman-compose file and export my variables from the script, unlike on linux where the export was only optional, as long as the variables were set.

At last, after some experiments, I found `export VAR=$VAR` is also required on Linux. Totally don't understand what this behavior is.
