### ISSUE TITLE
podman-compose with network_mode: "container:X" not working

### ISSUE THREAD

**Issue by alant54** [containers/podman-compose#522]
**Describe the bug**
So basically i try to use "network_mode: "container:gluetun"" in my yaml file like in docker but this is not working with podman-compose.
i know that it is not a problem with podman because when i try to create it with "podman create ... --network container:gluetun " this is working but with podman compose he is adding "--network container:gluetun" but  "--net name_default --network-alias name" too.

**To Reproduce**
create a container gluetun in my case (no matter which one for testing)

start the container that you create

try to create another container (no matter which one for testing) with "network_mode: "container: container_name"" 

my example :

`version: "3"
services:
 qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Europe/Zurich
      - WEBUI_PORT=8080
    volumes:
      - /PATH/config/temp:/config
      - /PATH/config/temp/data:/data/torrents
    restart: unless-stopped`

`podman-compose up`

**Expected behavior**
Creating the container without error

**Actual behavior**
Container not creating error :
`Error: cannot set multiple networks without bridge network mode, selected mode container: invalid argument
exit code: 125`

**Output**
`podman create --name=qbittorrent --label io.podman.compose.config-hash=123 --label io.podman.compose.project=temp --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=temp --label com.docker.compose.project.working_dir=/srv/dev-disk-by-uuid-369e2c8a-350a-4877-9478-380702409f48/Home/user-podman/yaml/temp --label com.docker.compose.project.config_files=compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=qbittorrent --network container:gluetun -e PUID=0 -e PGID=0 -e UMASK=022 -e TZ=Europe/Zurich -e WEBUI_PORT=8080 -v /PATH/config/temp:/config -v /PATH/config/temp/data:/data/torrents --net temp_default --network-alias qbittorrent --restart unless-stopped lscr.io/linuxserver/qbittorrent:latest
Error: cannot set multiple networks without bridge network mode, selected mode container: invalid argument
exit code: 125
`
but if I do this manually
removing this part "--net temp_default --network-alias qbittorrent"
it is working the container is created without error and all my traffic goes into gluetun container

`podman create --name=qbittorrent --label io.podman.compose.config-hash=123 --label io.podman.compose.project=temp --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=temp --label com.docker.compose.project.working_dir=PATH/yaml/temp --label com.docker.compose.project.config_files=compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=qbittorrent --network container:gluetun -e PUID=0 -e PGID=0 -e UMASK=022 -e TZ=Europe/Zurich -e WEBUI_PORT=8080 -v /PATH/config/temp:/config -v /PATH/config/temp/data:/data/torrents  --restart unless-stopped lscr.io/linuxserver/qbittorrent:latest`

**Environment:**
 - OS: debian 11
 - podman version: 4.1.1
 - podman compose version: 1.0.3

**Comment by muayyad-alsadi** [comment]
please test with latest podman-compose 
because we have fixed that

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

**Comment by alant54** [comment]
Thanks for the quick answer the upgrade to the 1.0.4 version fix this bug !
