### ISSUE TITLE
Support for Podman 4.1.x

### ISSUE THREAD

**Issue by neufeind** [containers/podman-compose#535]
Upgrading from podman 4.0.x to 4.1.1 we stumbled across problems pointing towards "add-hosts"-functionality. And it turned out that in the changes for 4.1.0 there seems to have been quite some changes.
Does the 4.1-strep maybe require adjustments from podman-compose-side?

https://github.com/containers/podman/releases/tag/v4.1.0

**Comment by muayyad-alsadi** [comment]
most likely this is the change you are talking about

> The --net=container: option to podman run, podman create, and podman pod create now conflicts with the --add-host option.

**Comment by ktp242** [comment]
Ran into the same issue from the post here,
https://discourse.pi-hole.net/t/problem-after-update-rhel8-6-podman-to-version-4-1-1/56883
Will podman-compose address the issue and adjust the codebase?

**Comment by muayyad-alsadi** [comment]
I'm using podman 4.1 and I have no issue

I've just tested [nets_test2 stack](https://github.com/containers/podman-compose/blob/devel/tests/nets_test2/docker-compose.yml) with the latest devel branch

```
$ rpm -q podman
podman-4.1.1-3.fc36.x86_64
$ podman-compose up -d
$ podman-compose ps
podman ps -a --filter label=io.podman.compose.project=nets_test2
CONTAINER ID  IMAGE                             COMMAND               CREATED        STATUS            PORTS                   NAMES
f6fb23e940e0  docker.io/library/busybox:latest  /bin/busybox http...  2 minutes ago  Up 2 minutes ago  0.0.0.0:8001->8001/tcp  nets_test2_web1_1
ad23d3cfdba5  docker.io/library/busybox:latest  /bin/busybox http...  2 minutes ago  Up 2 minutes ago  0.0.0.0:8002->8001/tcp  nets_test2_web2_1
```

to install the latest devel branch


```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

In the given output I see `--label io.podman.compose.config-hash=123` and `--label io.podman.compose.version=0.0.1`

the latest podman does not do that, it sets version to be 1.0.4 and proper hash like this

```
podman run --name=nets_test2_web2_1 -d --pod=pod_nets_test2 --label io.podman.compose.config-hash=b7bfacd6997a3e922a4e9896bdccfca6234434cebbca90b4cdfe9b17fd3e49e6 --label io.podman.compose.project=nets_test2 --label io.podman.compose.version=1.0.4 ...
```

please make sure you use the latest code.
