### ISSUE TITLE
Remove dependency on dotenv

### ISSUE THREAD

**Issue by Dragas** [containers/podman-compose#567]
**Describe the bug**
Current installation process suggests using `curl` to download podman-compose off particular tag/branch from this repository. Doing so on an out of the box ubuntu server 22.04 as of time of writing requires an additional step to install dotenv module globally.

**To Reproduce**
1. install ubuntu server 22.04 (and podman, via apt)
2. in shell:
  a. mkdir ~/.local/bin
  b. curl -o ~/.local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/v1.0.3/podman_c
ompose.py
  c. chmod +x ~/.local/bin/podman-compose

**Expected behavior**
Podman compose produces the following output, and does not require installing additional any additional modules.
```
dragas@dvm:~/.local/bin$ podman-compose
usage: podman-compose [-h] [-v] [-f file] [-p PROJECT_NAME] [--podman-path PODMAN_PATH] [--podman-args args]
                      [--podman-pull-args args] [--podman-push-args args] [--podman-build-args args]
                      [--podman-inspect-args args] [--podman-run-args args] [--podman-start-args args]
                      [--podman-stop-args args] [--podman-rm-args args] [--podman-volume-args args] [--no-ansi]
                      [--no-cleanup] [--dry-run]
                      {help,version,pull,push,build,up,down,ps,run,exec,start,stop,restart,logs} ...
options:
  -h, --help            show this help message and exit
  -v, --version         show version
  -f file, --file file  Specify an alternate compose file (default: docker-compose.yml)
  -p PROJECT_NAME, --project-name PROJECT_NAME
                        Specify an alternate project name (default: directory name)
  --podman-path PODMAN_PATH
                        Specify an alternate path to podman (default: use location in $PATH variable)
  --podman-args args    custom global arguments to be passed to `podman`
  --podman-pull-args args
                        custom arguments to be passed to `podman pull`
  --podman-push-args args
                        custom arguments to be passed to `podman push`
  --podman-build-args args
                        custom arguments to be passed to `podman build`
  --podman-inspect-args args
                        custom arguments to be passed to `podman inspect`
  --podman-run-args args
                        custom arguments to be passed to `podman run`
  --podman-start-args args
                        custom arguments to be passed to `podman start`
  --podman-stop-args args
                        custom arguments to be passed to `podman stop`
  --podman-rm-args args
                        custom arguments to be passed to `podman rm`
  --podman-volume-args args
                        custom arguments to be passed to `podman volume`
  --no-ansi             Do not print ANSI control characters
  --no-cleanup          Do not stop and remove existing pod & containers
  --dry-run             No action; perform a simulation of commands

command:
  {help,version,pull,push,build,up,down,ps,run,exec,start,stop,restart,logs}
    help                show help
    version             show version
    pull                pull stack images
    push                push stack images
    build               build stack images
    up                  Create and start the entire stack or some of its services
    down                tear down entire stack
    ps                  show status of containers
    run                 create a container similar to a service to run a one-off command
    exec                execute a command in a running container
    start               start specific services
    stop                stop specific services
    restart             restart specific services
    logs                show logs from services
```

**Actual behavior**
Podman compose produces the following output instead
```
dragas@dvm:~/.local/bin$ podman-compose
Traceback (most recent call last):
  File "/home/dragas/.local/bin/podman-compose", line 36, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
```

**Output**
See actual behavior

**Environment:**
 - OS: Linux Ubuntu server 22.04
 - podman version: 3.4.4
 - podman compose version: tag v1.0.3

**Additional context**

None.

**Comment by benyaminl** [comment]
I think you can't remove dotenv, but you can use the pip3 install, as it's the basis of all .env renderer I think this should be README Update... rather than bugs... it's not that good to remove dotenv and write it on scratch and it will be reinventing the wheels.

**Comment by kklem0** [comment]
@benyaminl One of the problem when facing this So the problem is running podman-compose in a rootless environment like SteamOS, the system is on read only mode and we'll have to install it in home folder.

I made it work by `python -m venv podman-compose-venv`, `. ./podman-compose-venv/bin/activate`, `pip install python-dotenv pyyaml`, changed the first line from `#! /usr/bin/python3` to `#!/usr/bin/env python3`, then it works.

So my request is to change `#! /usr/bin/python3` to `#!/usr/bin/env python3` so we can run it under venv.

**Comment by muayyad-alsadi** [comment]
You can just pass --user to pip3

Like this

```
pip3 install --user 
https://github.com/containers/podman-compose/archive/devel.tar.gz

# or

pip3 install --user podman-compose
```

This will work for read-only rootfs as it installs in home of the current user.

**Comment by muayyad-alsadi** [comment]
> I am not convinced using a venv is a good solution.

I totally agree, `venv` is a developer thing, someone who work on two projects one of them django version and another depends on another version.

> pip3 install python-dotenv did the trick.

here are the dependencies in [requirements.txt](https://github.com/containers/podman-compose/blob/devel/requirements.txt)

```
curl -sSLO https://raw.githubusercontent.com/containers/podman-compose/devel/requirements.txt
pip3 install -r requirements.txt
```

if your venv is active you can also type this

```
python3 -m pip --help
python3 -m pip install python-dotenv

# or

python3 -m pip install -r requirements.txt
```

**Comment by zeddee** [comment]
this looks resolved?

i see the readme no longer has instructions to `curl` the `podman-compose.py` file directly, and instead instructs users to pip install the built package(s), which makes sure that deps such as `python-dotenv` are taken care of

also if it was not already clear, `podman-compose` depends on `python-dotenv` to allow the `--env-file` cli flag to work, so we can't remove it as per original scope of the ticket

![Screenshot 2023-05-14 at 10 06 47](https://github.com/containers/podman-compose/assets/6762123/92cffb5b-d468-4025-829e-1a6a633a59be)

**Comment by RickMeijer** [comment]
It seems to have reappeared a year later. Trying to get podman-compose to work on a naked ubuntu server, and running into this exact issue, due to the manual step.

**Comment by nunesgh** [comment]
Indeed, I have also run into this issue when following the [manual installation](https://github.com/containers/podman-compose#manual). I had to install `python3-dotenv` via `apt`.
