### ISSUE TITLE
Network mode slirp4netns not supported in podman-compose

### ISSUE THREAD

**Issue by DCsunset** [containers/podman-compose#577]
**Describe the bug**

Network mode slirp4netns not supported in podman-compose.

**To Reproduce**
1. what is the content of the current working directory (ex. docker-compose.yml, .env, Dockerfile, ...etc.)

`docker-compose.yml` shown as below:
```yml
version: '3'

services:
  app:
    image: alpine
    networks:
      "slirp4netns:outbound_addr=wlan0"
```
2. what is the sequence of commands you typed

```
podman-compose up
```

**Expected behavior**
A container with network mode slirp4netns set up correctly

**Actual behavior**

**Output**

```
$ podman-compose version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.2.1
podman-compose version 1.0.4
podman --version
podman version 4.2.1
exit code: 0

$ podman-compose up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.2.1
Traceback (most recent call last):
  File "~/podman-compose/podman_compose.py", line 2862, in <module>
    main()
  File "~/podman-compose/podman_compose.py", line 2858, in main
    podman_compose.run()
  File "~/podman-compose/podman_compose.py", line 1383, in run
    self._parse_compose_file()
  File "~/podman-compose/podman_compose.py", line 1530, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: slirp4netns:outbound_addr=wlan0
```

**Environment:**
 - OS: Linux
 - podman version: 4.2.1
 - podman compose version: 801faea

**Additional context**

See `--network` section of [podman-create](https://docs.podman.io/en/latest/markdown/podman-create.1.html)

**Comment by DCsunset** [comment]
It seems that `network_mode` should be used in `docker-compose.yml` instead of `networks`, although the podman uses the same option name `--network`.

**Comment by leiless** [comment]
I was able to produce the same error using the `docker-compose.yml` in the link https://docs.docker.com/compose/compose-file/compose-file-v3/#ipv4_address-ipv6_address

```yaml
version: "3.9"

services:
  app:
    image: nginx:alpine
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
```

```
$ podman-compose up
['podman', '--version', '']
using podman version: 3.4.2
Traceback (most recent call last):
  File "/home/lei/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/lei/.local/lib/python3.8/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/home/lei/.local/lib/python3.8/site-packages/podman_compose.py", line 1022, in run
    self._parse_compose_file()
  File "/home/lei/.local/lib/python3.8/site-packages/podman_compose.py", line 1128, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: app_net
```

If I replace the `services.app.networks` with `services.app.network_mode`, it works fine!

**Comment by DCsunset** [comment]
@leiless Maybe you can open a new issue since it's slightly different from the current issue title. But I think you are right: the network_app seems to be more powerful.

**Comment by leiless** [comment]
> @leiless Maybe you can open a new issue since it's slightly different from the current issue title. But I think you are right: the network_app seems to be more powerful.

https://github.com/containers/podman-compose/issues/579

**Comment by DCsunset** [comment]
Oh I just tried your example. It doesn't work for 1.0.3, but it does for 1.0.4. So I think they've fixed it already, although not published yet.
