### ISSUE TITLE
Next release plan

### ISSUE THREAD

**Issue by xmnlab** [containers/podman-compose#578]
Hi everyone!

I would like to know if there is any plan for the next release.

it is already 10 months since the last release and I guess that there are a tons of new nice features to be released :)
btw, I am interested in the --env-file feature that was already merged.

thanks!

**Comment by xmnlab** [comment]
btw, I am pushing a nightly version of the conda package, in the case someone else is interested in: https://anaconda.org/opensciencelabs/podman-compose

**Comment by jedahan** [comment]
Would also like to see a 1.0.4 release cut - spent a few days trying to figure out why volumes were working fine on my machine but not on a friends.

**Comment by benyaminl** [comment]
Ping @muayyad-alsadi is that possible sir?

**Comment by jonorozcoc** [comment]
Any update on this?

**Comment by henriquemattos** [comment]
Well, it's been over a year without release. Maybe building it ourselves is the best solution. Anyone has built it so far?

**Comment by xmnlab** [comment]
just for conda: https://anaconda.org/opensciencelabs/podman-compose
It seems it has the last version from podman-compose main branch
this is my recipe: https://github.com/osl-package-recipes/podman-compose-feedstock-nightly

**Comment by muayyad-alsadi** [comment]
I've just made a release, please note in the release `--in-pod=0` by default so that I don't break running systems.

**Comment by xmnlab** [comment]
Awesome! Thank you so much
