### ISSUE TITLE
podman-compose build swallows exit code

### ISSUE THREAD

**Issue by skateman** [containers/podman-compose#586]
**Describe the bug**
When the `podman-compose build` command is running the underlying `podman build`, it does not return with its proper exit code if the build process fails.

**To Reproduce**
```bash
# cat Dockerfile
Hello World!

# cat docker-compose.yml
version: '3'
services:
    test:
        build:
            context: .

# podman-compose build
['podman', '--version', '']
using podman version: 4.2.1
podman build -t repro_test -f ./Dockerfile .
Error: no FROM statement found
exit code: 125

# echo $?
0
```

**Expected behavior**
Exit code should be taken over from the underlying command.

**Actual behavior**
Exit code 0 is being returned.

**Output**

```bash
$ podman-compose version
['podman', '--version', '']
using podman version: 4.2.1
podman-composer version  1.0.3
podman --version 
podman version 4.2.1
exit code: 0

```

**Environment:**
 - OS: Linux (Fedora 36)
 - podman version: 4.2.1

**Additional context**
Probably the same issue as it was with [`podman run`](https://github.com/containers/podman-compose/issues/408)

**Comment by chris-ds-dk** [comment]
Any chance of a new release soon? We would appreciate the fix in [commit 9a08f85](https://github.com/containers/podman-compose/commit/9a08f85ffd08d84796af5e9d104c0b83c5490d81). Our attempts to implement workarounds in our Jenkins pipeline has so far been unsuccesful.
