### ISSUE TITLE
Unable to create volume

### ISSUE THREAD

**Issue by etmatrix** [containers/podman-compose#61]
I trying docker-compose from codelibs/docker-fess. My environment is Centos 8 and latest git commit of podman-compose.
I run it with:

    podman_compose.py -p fess up

but I receive an error when it create volume.

	# podman_compose.py -p fess up
	podman pod create --name=fess --share net -p 9200:9200 -p 8080:8080 -p 9201:9200 -p 5601:5601
	e0171b13537adf8fbfce95cf90574c5c916e96612939074721d97bba24b421d9
	0
	podman volume inspect fess_esdata01 || podman volume create fess_esdata01
	ERRO[0000] "unable to find volume fess_esdata01: volume with name fess_esdata01 not found: no such volume" 
	Traceback (most recent call last):
	  File "/usr/bin/podman_compose.py", line 1264, in <module>
	    main()
	  File "/usr/bin/podman_compose.py", line 1261, in main
	    podman_compose.run()
	  File "/usr/bin/podman_compose.py", line 750, in run
	    cmd(self, args)
	  File "/usr/bin/podman_compose.py", line 933, in wrapped
	    return func(*args, **kw)
	  File "/usr/bin/podman_compose.py", line 1054, in compose_up
	    detached=args.detach, podman_command=podman_command)
	  File "/usr/bin/podman_compose.py", line 482, in container_to_args
	    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
	  File "/usr/bin/podman_compose.py", line 409, in mount_desc_to_args
	    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
	  File "/usr/bin/podman_compose.py", line 385, in mount_dict_vol_to_bind
	    src = json.loads(out)[0]["mountPoint"]
	TypeError: 'NoneType' object is not subscriptable

this is the file docker-compose.yml

	version: "3"
	services:
	  fess01:
	    image: codelibs/fess:13.4.0
	    container_name: fess01
	    ports:
	      - "8080:8080"
	    depends_on:
	      - es01
	      - es02
	    environment:
	      - RUN_ELASTICSEARCH=false
	      - "ES_HTTP_URL=http://es01:9200"
	      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
	    networks:
	      - esnet
	
	  es01:
	    image: codelibs/fess-elasticsearch:7.4.0
	    container_name: es01
	    environment:
	      - node.name=es01
	      - discovery.seed_hosts=es02
	      - cluster.initial_master_nodes=es01,es02
	      - cluster.name=fess-es
	      - bootstrap.memory_lock=true
	      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
	      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
	    ulimits:
	      memlock:
	        soft: -1
	        hard: -1
	    volumes:
	      - esdata01:/usr/share/elasticsearch/data
	      - esdictionary01:/usr/share/elasticsearch/config/dictionary
	    ports:
	      - 9200:9200
	    networks:
	      - esnet
	
	  es02:
	    image: codelibs/fess-elasticsearch:7.4.0
	    container_name: es02
	    environment:
	      - node.name=es02
	      - discovery.seed_hosts=es01
	      - cluster.initial_master_nodes=es01,es02
	      - cluster.name=fess-es
	      - bootstrap.memory_lock=true
	      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
	      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
	    ulimits:
	      memlock:
	        soft: -1
	        hard: -1
	    volumes:
	      - esdata02:/usr/share/elasticsearch/data
	      - esdictionary02:/usr/share/elasticsearch/config/dictionary
	    ports:
	      - 9201:9200
	    networks:
	      - esnet
	
	  kibana:
	    image: docker.elastic.co/kibana/kibana:7.4.0
	    container_name: kibana
	    depends_on:
	      - es01
	      - es02
	    environment:
	      - "ELASTICSEARCH_HOSTS=http://es01:9200"
	    ports:
	      - 5601:5601
	    networks:
	      - esnet
	
	volumes:
	  esdata01:
	    driver: local
	  esdictionary01:
	    driver: local
	  esdata02:
	    driver: local
	  esdictionary02:
	    driver: local
	
	networks:
	  esnet:
	    driver: bridge

My workaround is make the volume before with the same command used by podman_compose.
Is it normal? Is a my issue? Could you resolve it?

**Comment by muayyad-alsadi** [comment]
Try using devel branch as in README.md

**Comment by etmatrix** [comment]
I have the same issue with devel and stable version. I installed with all methods, pip3, cp and so on... I got always the same issue. I understand the issue is not in podman-compose but in podman.

	# podman volume inspect fess_esdata01
	ERRO[0000] "unable to find volume fess_esdata01: volume with name fess_esdata01 not found: no such volume" 
	null
	
	[root@centos8 compose]# echo $?
	0

podman volume inspect return 0 also when the command fails. So for podman-compose is impossible to understand if the volume exist, maybe is better use another method.
In centos8 there is the version:

	# rpm -qi podman
	Name        : podman
	Version     : 1.0.5
	Release     : 1.gitf604175.module_el8.0.0+194+ac560166
	Architecture: x86_64
	Install Date: Thu Oct 17 07:49:05 2019

**Comment by rhatdan** [comment]
You probably need a newer version of podman.  Which should ship next month for rhel8.1.

**Comment by etmatrix** [comment]
I tested on Fedora 30 and works (podman 1.6.1). It's an issue only with old versions of podman.

**Comment by TomHutter** [comment]
I have a similar issue on Ubuntu 20.04 with podman 2.0.6 and podman-compose 0.1.5 

```
Traceback (most recent call last):
  File "/home/tom/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 1095, in main
    podman_compose.run()
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 627, in run
    cmd(self, args)
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 784, in wrapped
    return func(*args, **kw)
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 899, in compose_up
    podman_args = container_to_args(compose, cnt,
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 459, in container_to_args
    mount_args = mount_desc_to_args(compose, volume, cnt['_service'], cnt['name'])
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 388, in mount_desc_to_args
    mount_desc = mount_dict_vol_to_bind(compose, fix_mount_dict(mount_desc, proj_name, srv_name))
  File "/home/tom/.local/lib/python3.8/site-packages/podman_compose.py", line 368, in mount_dict_vol_to_bind
    src = json.loads(out)[0]["mountPoint"]
KeyError: 'mountPoint'
```

The reason here lies in line 366 `src = json.loads(out)[0]["mountPoint"]` where podman-compose tries to get the volume mount point.

At least on my system podman inspect volume shows the mount point as `Mountpoint`. Changing line 366 in podman-compose to `src = json.loads(out)[0]["Mountpoint"]` solves the issue.

```
podman volume inspect blubb
[
     {
          "Name": "blubb",
          "Driver": "local",
          "Mountpoint": "/home/tom/.local/share/containers/storage/volumes/blubb/_data",
          "CreatedAt": "2020-09-10T08:26:28.01718523+02:00",
          "Labels": {
               
          },
          "Scope": "local",
          "Options": {
               
          },
          "UID": 0,
          "GID": 0,
          "Anonymous": false
     }
]
```

**Comment by edeediong** [comment]
@TomHutter thanks a lot! This helped me... I'm using CentOS 8 and podman 2.1.1 with podman-compose 0.15. Thanks again
