### ISSUE TITLE
When running podman-compose it hangs with no error

### ISSUE THREAD

**Issue by NikitaPoly** [containers/podman-compose#614]
**Describe the bug**
I installed podman desktop onto windows. Initiated the podman. Next I ran `podman-compose --env-file ..\.env-test build`. This is the output:
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman build -f .\./bin/psql_proxy/Dockerfile -t <name of container> .

After this it hangs and no more output is shown.

**To Reproduce**
1. install podman desktop for windows
2. run podman compose on a docker-compose.yaml

**Expected behavior**
Builds the containers from docker-compose.yaml

**Actual behavior**
Gets stuck on first container build

**Output**
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman build -f .\./bin/psql_proxy/Dockerfile -t <name of container> .

```
$ podman-compose version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.4
podman --version
podman version 4.3.1
exit code: 0

$ podman-compose up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
no compose.yaml, docker-compose.yml or container-compose.yml file found, pass files with -f


**Environment:**
 - OS: windows 10
 - podman version: 
 - Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.5
Git Commit:   814b7b003cc630bf6ab188274706c383f9fb9915
Built:        Thu Nov 10 06:18:45 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 07:24:13 2022
OS/Arch:      linux/amd64
 - podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.3.1
podman-compose version 1.0.4
podman --version
podman version 4.3.1
exit code: 0

**Additional context**

Add any other context about the problem here.

**Comment by muayyad-alsadi** [comment]
```
no compose.yaml, docker-compose.yml or container-compose.yml file found, pass files with -f
```

It seems that you run it in the wrong directory where the yaml file is not there use `ls` command to see

**Comment by NikitaPoly** [comment]
It seems to be working now it is just very slow. I had to wait a while for it to start the actual building. So I guess this is no issue?
