### ISSUE TITLE
Is podman-compose project actively maintained?

### ISSUE THREAD

**Issue by palashkulsh** [containers/podman-compose#629]
First of all kudos and thanks to podman-compose team for making such great tool. Its very good.

Just wanted to know if podman-compose is actively maintained ?

as last release is of dec 2021 . And many bug fixes have gone after that release.

**Comment by goldmann** [comment]
See #276.

**Comment by xmnlab** [comment]
last comment on #276 is from [Nov 18, 2021](https://github.com/containers/podman-compose/issues/276#issuecomment-973054886) 

and last commit was [on Oct 27, 2022](https://github.com/containers/podman-compose/commit/08ffcf6126a3ae4016e3d81e963a3629e4b75986)

also it seems that there is no plan for a release: https://github.com/containers/podman-compose/issues/578

so it looks like it is not maintained ...

**Comment by palashkulsh** [comment]
i eventually installed the repo directly via pip and its working fine with latest code in repo

**Comment by muayyad-alsadi** [comment]
I've just made a release
