### ISSUE TITLE
Container egress fails intermitently when there is more than 40 running containers

### ISSUE THREAD

**Issue by vpavlin** [containers/podman-compose#672]
**Describe the bug**
We are using compose to test nwaku nodes (https://github.com/alrevuelta/nwaku-simulator) - nwaku is peer-to-peer messaging protocol - and we are getting into trouble when we run "too many" containers. When it is below 40, everything works as expected, but once we get into higher numbers, the contrainers start to lose access to internet and we get errors like

```
$ podman exec -it nwaku-simulator_nwaku-80_1 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Invalid argument
```

similarly grafana fails to download plugins due to network failures.

Weirdly enough when I run the bootstrap node, prometheus and grafana via podman-compose and then spin up 100 containers directly via `podman-run`, everything works just fine. See (https://github.com/vpavlin/nwaku-simulator/blob/run-stop-bash/run.sh)

I tried to use `macvlan` for the network driver and change the `subnet` just to make sure there is no conflict. 

It also happens in both docker-compose and podman-compose, so it might not be a podman-compose issue per se, but the case where it works when I run it without compose, directly through podman makes me think there is something happening differently wrt networking between podman and podman-compose 

**To Reproduce**
1. `git clone https://github.com/alrevuelta/nwaku-simulator.git`
2. `git checkout 200-nodes`
3. 
  ```
  export BOOTSTRAP_ENR=enr:-JK4QHFki86UtnTNDC_MBpgMb5aqz5YjbjUY1emBBYFMYqtLMSRcqfQFxSrT5FVYCceWnSJKrI9GowK7jmvGw7y85W0BgmlkgnY0gmlwhKwUAP6Jc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC6mCDdWRwgiMohXdha3UyAQ
export NWAKU_IMAGE=statusteam/nim-waku:v0.15.0
  ```
 4. `podman compose up -d`
 5. `podman exec -it nwaku-simulator_nwaku-80_1 ping 8.8.8.8`
 
 You may see standard ping output or `ping: sendto: Invalid argument` - but you should see the errors most of the time

**Expected behavior**
Internet is accessible from the containers all the time

**Actual behavior**
Internet is inaccasible most of the time

**Output**

```
$ podman-compose version
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.4.4
podman-compose version 1.0.6
podman --version 
podman version 4.4.4

```

**Environment:**
 - OS: Linux 
 - podman version: 4.4.4
 - podman compose version: 1.0.6 (fromy PyPi)

**Additional context**

**Comment by vpavlin** [comment]
@baude @mheon Hi guys! Mr. McCarty suggested your names when I asked about networking and podman, so it would be awesome if you could take a look and hopefully provide some pointers.

**Comment by mheon** [comment]
When you verified that `podman run` did not have the same symptoms, did you do so with root or rootless Podman?

**Comment by muayyad-alsadi** [comment]
I've ready your report quickly, please confirm it's related to `podman-compose` not `podman`?

to make things clear there are some limitations for user containers (as opposed to root containers ex. docker)
since we run using the current user directly not pass request to a daemon running as root.
part of those documented limitations you can't open privileged ports (ex. port 80) 

ping is a privileged tool, it requires some sort of root access  even if you don't type sudo
ping is either a SUID binary or a capability or sysctl indicates non-root can ping

https://unix.stackexchange.com/questions/592911/how-does-ping-work-on-fedora-without-setuid-and-capabilities

on my machine non-root container can't ping

```
$ podman run --rm -ti busybox 
/ # ping google.com
PING google.com (142.250.180.174): 56 data bytes
ping: permission denied (are you root?)
```

```
$ sysctl net.ipv4.ping_group_range 
net.ipv4.ping_group_range = 0	2147483647
```

**Comment by muayyad-alsadi** [comment]
if you just want to check connectivity try any website that log ip

```
$ podman run --rm -ti busybox 
/ # wget -qO - ifconfig.me; echo
82.212.85.210
/ # 
```

**Comment by vpavlin** [comment]
@mheon I ran `podman run` as an ordinary user, so I'd say rootless, but since I am able to execute ping, that would suggest I run them as root? Yet, I see all the containers under `podman ps` without using `sudo`

@muayyad-alsadi I am not sure how to confirm whether it is related to podman or podman-compose. When I run those 100 containers via podman directly things kinda work, but the network is failing as well, when I run through podman-compose networking fails significantly more.

I get the same permission denied and range as you do when I execute the commands. When I run a container using the command from the `run.sh` script (https://github.com/vpavlin/nwaku-simulator/blob/run-stop-bash/run.sh), I am able to execute ping without problems.

That said, this is not about ping per se, this is about failing network - e.g. grafana container not being able to download plugins.

**Comment by mheon** [comment]
Ping as non-root has worked for a long while so long as sysctls are set appropriately, so you are definitely rootless.

If podman-run works, it's probably something related to how compose is configuring networking?

**Comment by vpavlin** [comment]
Well..it "works better" as in it does not completely fail:D

```
$ podman exec -it nwaku-simulator_nwaku-80_1 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Invalid argument
$ podman exec -it nwaku-simulator_nwaku-80_1 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Invalid argument
$ podman exec -it nwaku-simulator_nwaku-80_1 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Invalid argument
$ podman exec -it nwaku-simulator_nwaku-80_1 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=42 time=30.382 ms
^[[A64 bytes from 8.8.8.8: seq=1 ttl=42 time=20.148 ms
64 bytes from 8.8.8.8: seq=2 ttl=42 time=23.908 ms
````

But the networking is definitely not working properly. I would love to provide more information if you lead me to what information that would be and where to find it

**Comment by vpavlin** [comment]
Hi all, we did a bit more investigation 

1. Tried both root and rootless containers - same result
2. Tried on subscribed RHEL 9 to make sure this is not something related to some Fedora specific Kernel issue
3. Tried different configuration of the nwaku node in the containers - we basically create a mesh of every node being connected to every other node, so to limit that I changed the configuration to let each node only connect to up to 10 other nodes, but the issue persisted
4. Running the compose somehow disrupts networking on the machine - cannot ping localhost - get 100 % packet loss

I have it running on a RHEL VM in AWS is anyone would be willing to poke around.

It just feels like the system cannot handle the network load somehow, but I am not expert enough to understand if that is the case or if there is anything I can do about it.

**Comment by vpavlin** [comment]
One more thing - someone mentioned to me that the issue might be due to us assigning IPs staticly, so I rewrote the compose to not hardcode the IPs, but the results are still the same.

Also, I should mention I do not believe this is podman-compose issue specifically anymore. So I am not sure if I should file a new issue elsewhere?

**Comment by vpavlin** [comment]
So after all the problem was arp table overflowing

Kudos to @msekletar for finding the problem and solution.

It seems like each netns has it's own arp table, but the gc_thresh is global, so with 100 containers caching 100 entries in arp table it got overloaded and kernel could not handle it.

Increasing net.ipv4.neigh.default.gc_thresh3 helped and now everything is working as expected.
