### ISSUE TITLE
Ignore `COPY --link` in the latest Dockerfiles.

### ISSUE THREAD

**Issue by veritas9872** [containers/podman-compose#674]
**Is your feature request related to a problem? Please describe.**

THe Docker BuildKit syntax recently introduced a `--link` flag to the `COPY` command. This currently raises an error when using Podman Compose.

**Describe the solution you'd like**

I think that simply ignoring the flag would make for a good solution.

**Describe alternatives you've considered**

Perhaps implement the `--link` functionality in Podman Compose. However, this would be a lot of work.

**Additional context**

The `--link` flag was introduced in Docker BuildKit 1.4, whereas the current latest version is 1.5. As many projects are moving on to the latest BuildKit specification, making Podman Compose compatible would be beneficial.

**Comment by muayyad-alsadi** [comment]
This is a ticket for buildah

https://github.com/containers/buildah
