### ISSUE TITLE
Support for Pasta

### ISSUE THREAD

**Issue by 53c70r** [containers/podman-compose#690]
Please support "network_mode: pasta" since this seams to be the only solution to fully support ipv4, ipv6 and real source IP signalling.

**Comment by Pamalosebi** [comment]
See also: https://github.com/containers/podman/issues/8193#issuecomment-1458161803 and https://github.com/containers/podman/issues/8193#issuecomment-1458202993

**Comment by Akruidenberg** [comment]
+1 for me!

**Comment by muayyad-alsadi** [comment]
please provide me with minimal podman cli command do run two busybox http containers in pasta mode?

is this is the same as `podman network create -o mode=passthru mynet1`

https://docs.podman.io/en/latest/markdown/podman-network-create.1.html

> mode: This option sets the specified ip/macvlan mode on the interface. Supported values for macvlan are bridge, private, vepa, passthru. Defaults to bridge.

here I see it in `podman run ...`
but I need it as `podman network create` if possible

https://docs.podman.io/en/latest/markdown/podman-run.1.html#network-mode-net

**Comment by p12tic** [comment]
Fixed in https://github.com/containers/podman-compose/pull/867.
