### ISSUE TITLE
podman-compose PRs are not merged - shortterm version available

### ISSUE THREAD

**Issue by maurerle** [containers/podman-compose#742]
**Is your feature request related to a problem? Please describe.**
Somehow it is frustrating, that a lot Pull-Requests of podman-compose are not merged without comments, even though they provide additional value.
I do know that open-source can be hard, peoples life changes or people lose interest in things they used to maintain.
So we should always be respectful with that!

**Describe the solution you'd like**
I would like to have a version in the `containers` org which addresses the fixes provided by the community or gives responses what has to be changed for them to be integrated.

**Describe alternatives you've considered**
Until this happens, I merged pull requests which are not deprecated or break the single file installation into my devel branch:
https://github.com/maurerle/podman-compose

I would not like to keep maintaining this, but for now, this is a working solution which might be interesting for others in need as well.
To install, run:
`curl -o /usr/local/bin/podman-compose https://raw.githubusercontent.com/maurerle/podman-compose/devel/podman_compose.py && chmod +x /usr/local/bin/podman-compose`

**Additional context**
@muayyad-alsadi  Thank you for this tool, which makes migrating to podman quite easy on typical development installations!

**Comment by maurerle** [comment]
Hello @muayyad-alsadi - I understand, that PRs which are against the philosophy of this project (single process, single file) do not get merged.
However, improvements, adjustments to podman/docker features are needed and are often just small fixes.
The situation somehow did not improve at all.
I updated my devel branch to include useful fixes from latest PRs:
https://github.com/containers/podman-compose/compare/devel...maurerle:podman-compose:devel
(mostly using wget to download a patchset and apply it using `git am --3way file.patch`)

Issues and PRs are created for the same things, as some small issues do not get merged (see #771 and #761).

And the PR to reduce logging output #741 did not get any feedback yet.

I really would not like if it is needed to create a maintained fork of this project.

**Comment by p12tic** [comment]
Pull requests are now merged to podman, we can close this issue.

**Comment by maurerle** [comment]
Thank you very much for taking care of this @p12tic !
