### ISSUE TITLE
Support enable_ipv6 for networks

### ISSUE THREAD

**Issue by maxi0604** [containers/podman-compose#751]
**Is your feature request related to a problem? Please describe.**
I cannot automatically create networks with dual-stack support with `podman-compose up` so I have to edit the network json manually. This is also in the compose spec [1] and supported by `docker compose`
**Describe the solution you'd like**
When `enable_ipv6: true` is given for a network, the `--ipv6` flag is passed to `podman network create`
**Describe alternatives you've considered**
This can currently be done by creating the network manually or editing the network's json file.
**Additional context**
I've opened #749 which implements this.

[1] https://github.com/compose-spec/compose-spec/blob/master/06-networks.md#enable_ipv6

**Comment by sgryphon** [comment]
Yes please
