### ISSUE TITLE
Support `additional_contexts`

### ISSUE THREAD

**Issue by otto-liljalaakso-nt** [containers/podman-compose#762]
**Is your feature request related to a problem? Please describe.**
I have a project that is split to multiple sub-projects that share a common set of data.
Each sub-project includes a `docker-compose.yml` for setting things up.
To include the shared data, I would like to do this in `docker-compose.yml`:

```
services:
  myservice:
    build:
      context: .
      additional_contexts:
        data: ../data
```

And then in `Dockerfile` for `myservice`:

```
COPY --from=data somedata.json /data/somedata.json
```

But, when I run `podman-compose`, I see this:

```
[4/4] STEP 4/8: COPY --from=data somedata.json /data/somedata.json
? Please select an image: 
  ▸ registry.fedoraproject.org/data:latest
    registry.access.redhat.com/data:latest
    docker.io/library/data:latest
    quay.io/data:latest
```

**Describe the solution you'd like**
Implement [additional_contexts] from the Compose Specification.

[additional_contexts]: https://github.com/compose-spec/compose-spec/blob/master/build.md#additional_contexts

**Describe alternatives you've considered**
1. Use Docker Compose instead, which [implements that feature](https://github.com/docker/compose/pull/10369).
1. Restructure my project so that each subproject contains a copy of the data directory,
or copy the data to sub-projects folder in a preparatory build step.
This would work, but requires restructuring the project even though `additional_contexts` is part of the Compose Specification.

**Additional context**
Yes, please! 😁

**Comment by theyoyojo** [comment]
👍 I'm using this commit in my fork
