### ISSUE TITLE
add support for `http-proxy` option

### ISSUE THREAD

**Issue by ChuJiani** [containers/podman-compose#782]
**Is your feature request related to a problem? Please describe.**
By default proxy environment variables are passed into the container if set for the Podman process. This can be disabled by setting the `http-proxy` value to **false**(defaults to **true**) with `--http-proxy=false`. Currently podman-compose does not support this feature.

**Describe the solution you'd like**
If the yaml file contains `http-proxy: false`, then add  `--http-proxy=false` to args.

**Comment by NerdToMars** [comment]
I tot this can be achieve with env environment already?

**Comment by NerdToMars** [comment]
does docker-compose has this feature also?

**Comment by ChuJiani** [comment]
No, because `docker run` hasn't `http-proxy` option either, and this can only be set in configuration files like `~/.docker/config.json`.
