### ISSUE TITLE
Defaulting to --pod on breaks compose file with --userns

### ISSUE THREAD

**Issue by deliciouslytyped** [containers/podman-compose#795]
https://github.com/containers/podman-compose/commit/7f5ce26b1b8103f48d5702dce7d52afe8b76daa5 breaks one of my compose files because `Error: --userns and --pod cannot be set together`.  Passing --in-pod=False or something, would presumably fix this, but 

Is there a way to disable --pod in the yaml? If not, can there be a way added to do it from here on out, or can this somehow be fixed?

I tried looking at the source but couldn't figure out if there is an existing way to do it.

**Comment by MrSSvard** [comment]
I think the check needs to be updated too. The only way to have it not be in a pod that I figured out is --in-pod ""
This worked before when the default was False as any "--in-pod" argument meant you wanted a pod. 

A completely new argument probably needs to be created unless we either revert the default or occupy a special pod name "False" that means no pod will be used.

**Comment by uosis** [comment]
`podman compose --in-pod= up` works, but this change of behavior is not great. Why is it desirable to default to running in pod? It seems like a needless deviation from `docker compose` behavior.

**Comment by camporter** [comment]
Same issue here, strange that the default behavior is to break userns options, which is incredibly necessary when dealing with a mix of rootful and rootless containers under podman.

**Comment by schugabe** [comment]
Same issue here that change and breaks pretty much all my projects.

**Comment by mokibit** [comment]
@deliciouslytyped  thanks for opening an issue.
The issue was fixed in https://github.com/containers/podman-compose/pull/964 by adding a custom section in the compose file so the user can set the preferred value for `--in-pod`.
@p12tic the problem can be closed.

**Comment by Ep0chalypse** [comment]
Using x-podman in-pod: false does not seem to work on latest version of podman-compose
```
podman-compose --version
podman-compose version 1.4.0  
podman version 5.2.2
```

I put this in my compose file
```
x-podman:
  in-pod: false
*SNIP*
userns_mode: "keep-id"
```

When I go to start the containers it says:
```
podman-compose up
1e91fa55041e3e5089c7d0d663a72d561e521a657ef3e77999e1eb0ce98828d1
Error: --userns and --pod cannot be set together
Error: --userns and --pod cannot be set together
[mariadb]    | Error: no container with name or ID "mariadb" found: no such container
```

**Comment by p12tic** [comment]
@Ep0chalypse could you copy your comment to a new bug?

**Comment by guesant** [comment]
> Using x-podman in-pod: false does not seem to work on latest version of podman-compose
> 
> ```
> podman-compose --version
> podman-compose version 1.4.0  
> podman version 5.2.2
> ```
> 
> I put this in my compose file
> 
> ```
> x-podman:
>   in-pod: false
> *SNIP*
> userns_mode: "keep-id"
> ```
> 
> When I go to start the containers it says:
> 
> ```
> podman-compose up
> 1e91fa55041e3e5089c7d0d663a72d561e521a657ef3e77999e1eb0ce98828d1
> Error: --userns and --pod cannot be set together
> Error: --userns and --pod cannot be set together
> [mariadb]    | Error: no container with name or ID "mariadb" found: no such container
> ```

same here
