### ISSUE TITLE
Podman compose setup fails with error **Failed Downloading Compose**  Try Again.  

### ISSUE THREAD

**Issue by CarlosOnline** [containers/podman-compose#812]
**Describe the bug**
Podman compose setup fails with error **Failed Downloading Compose**  Try Again.  
Is there a log that shows what the error is?

**To Reproduce**
Follow instructions from https://podman-desktop.io/docs/compose

**Expected behavior**
Podman compose to be installed.

**Actual behavior**
Failed Downloading Compose

**Output**
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAX8AAAB8CAYAAACBp7B9AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAB8tSURBVHhe7d0LVBRHvj/wb4yCiYxrwL8ymJVZVzhZw3oRdkHjgxwTPDG4WXE1eP+K3pUkXjGur0R0A4kJGo1GRY2oNxLXEHMcdWXjinoEcy7GrOgJ6CXjY4G4wN9l0BuI65Ao+Mi/qroGesYZHjOAA/37HEdmarqnp6urf11dVd3zUETE6B9BiIcIDR2K999fhQMHDuDVV1/FpEmTMH36dCxevBjFxcXYtm0brl69ipUrV2LkyJFYunQp1q9fj7Nnz+LTTz+Fr68fXn/9j/j222r5ia03YEAAPvwwHX/+834kJSUhPDwcqampePfdd3Ho0CFs2bIFPXr0wCuvvIJRo0Zh7dq12LVrF7788kusXr0aQ4f+G3vvVVRXu/4dCGlv3eRfQjzCnTt38eOPP8Lb2xsPPfQQjh07hmXLluEf//gH6uvr2YHhfWRkZMBiseD06dMs0L+OkydPonfv3mKee/fu4e7du/LTXHPnzh32OXfFZ3bv3h0FBQVYuHAh8vPzxfubNm1CWlqaeF5UVCTeO3jwoPjejzzyiPh7+3a9eJ8QT0XBn3iUf/3rX6zWXoNf//rX4vH999/j73//u3ivV69eKC8vh9lsho+PDwuwt3Hx4kU8/PDDGD9+PH72s5+xs4L/ZZ9xQ0zvquvXr4vPeeqppzBixAgRzM+fP49bt26J5f7zn/9ERUWFeM4PNiaTSbwXERGBIUOGsHmv4cYNi/w0QjwTNfsQj8Jr7//+71MQHz+NHQT+VwR6HmCb0rNnTxH4eVNPWtoHrKZ+Vr7juueeG4fExFfYWcQdXLlyRRxomsKbgQYOHMgOFMC2bTtw9Ogx+Q4hnomCP/E4P/nJT/DMM08jJmY8BgzQo1u3h+U79+O1cl7rvnTp79i/Pwtnz/6PaLZxF2++GTlyBGJjfwODIZAFdy/5jmP19XUoLb2Mzz47hPz8M7h586Z8hxDPRMGfEEI0iNr8CSFEgyj4E0KIBlHwJ4QQDaLgTwghGkTBnxBCNIiCPyGEaBAFf0II0SAK/oQQokGdM/jrQxGX9BbS0pYhWiZ1FH30bKSs2Yj0lLEyhbSWPmwyklLXIq1T5aE/ohOXYU36RqR0dKEjpB204grfyUjP/QPCdfJli1hQsD4GiUb5spX0cRuRsWgY/KrPYn3CfBjN8g2WnsvSdRaW/ixLl8kdIS49G4tYJlgKNuHZxP0ytSnN51tdnQXVJeeQc2An0rNLZWrX1fo89ATW7WhfpiOQYlyJCQag7NAbiEs9I9M7j6CY2Xh50liEBflC5+0tU1m5tFTDXHwGB3bshLGwSqaSrsK1mn9dHfvXkkct6t24s+2YqMHw40/8hmBcV6htOcwjfjMzHQJCRmPmmx8h1/gWYvVyetIJPIMQAw+Y3jCEjceTSmLnoH8BqcZsfPLmNESF6JXAby2X7G1vnR8M4eOxaOteHM6Yh2gql12KS8G/LCcaY8a05BGHBVlyJhecyCuF+DmM6gs4liOSOjXH+TYGkdPfxa68cnaeBOgMz2BpZgaShivzEE93HKYyHirrUFZ4BOeVRM83fDEyM1/DOAM/JbWgLG833pnOyqK1XEaOwfT523DIZBYHAr+QKViRsREzgsTcpAvw6DZ/s3E+nmeFMPJ5VZNPV1RyFOlL4vHs/H0wiSNAECat2Ig4qml1AmeQGheNyMjoztPko5+M9BW/RTCP+9VnsWV6DOKWbEd2ifK2VUn+p0hNiENc8nGI4xs7A4+dQX1dXQWN9vEk+ZuRkHxE2dF0w/ByymQlnZA244+Fa2YrfVC8zyxhPj62C/r2zDlvs4PDERSc2o7ElM9lKunsKPh7mvxVWJBVIk61deFTkBqmJBPSJmIWIzqY91FYUPBhK86oWblMXLAfXfkEXGs6LvgHPYfENVuRlZuDE6dP4LR8nMg1IiP1BThsSuSjevh0uRsRJ5NaKih2GdKN2apl5SDXuBYLo/3lFM7dP282DmeuRGIL5m0L5g37UCg6O/QImRoq0u43GDFJa2Fk+WnNS2UdNyIldrCcppE+KUOZJnOeTFELxZos5TOMKQ7WMWwlsvi8h9ciRibZb5vhM1bafBexXZNeYGvgitatmw1XylmDwYhN2Wi73NwsZLKaclOdnSlGZVpjikyQbNL1LyApw6jkmXjw9VmJGc317ejHsvXJwOFc63x8Xdh3EuuyDEaRlgm7RTs1Y1KoMoii+HOkttkwOde2l03+BCmdzw3bjG2v9IVjG8sPy4eFaZnIPaH+fLY/O8w/23wJin0LmYez5XzscSIbxvRliG1B/0UQO1im2cQCnv+ZSE9pqiz5I3qhg/zI2orUuNAm9wl34lZrdUzw54Hikz9iZtSTCNB5w9tmRAELcONeQ4ZxGdqmj9MfcWlZyFg6HuEGHbzZUpRleUNniMTUFRnITIqQ09qzn5cPfuDz6+AXPBozV2zFpA5phz+KnGIR/REQOP7+wsICyRpWkN6cFAkDy0/e2ci/Jx9xojMMw4SlLPilTbaZz/xxBSr5k8AhSBQpKvrxCAxQnhqCpyhP1KL8wd+uM5ciW0mxEZCSiTVzR7PvouQXJ7brpNeQmW77PZrlwro1cKec6Scj7fBWLJ0wzGa5dTo/BEdNw4qM37ZuPdS8JiM98zVMCtHDS3wnnsjXZzTmrmEBylnBF52yy9n6BMGPN9PI9eGjcILFugwBT265yRgeyNeNxX7T7rapxbuzvax4/myVnc98HXka217hU5cjg5cfvm0ylmHqiEC2vur8Y/tzU/nH6FjZzFj6DIJZBortqRQGMYppaUYmUp0GVX/ErmEVhjd/ixHqWMD+eusCET6B5X/WWgf9ciyGpG/FiqkyP8Qy+Xzs+wY8iXGLNsGYtdLBgceduOWajgn+xiMoLCtHwaFtmG8zouBFJO85L0a5eBvGYu5C949uw1PWYu4IP5ZlFpgOvIvpkdZlzcLqPD5yQYfgSW8h3cGpROO8dags2IfkiWMaRuRMTN6NU5U+MAS0bndzVXZ5jfLEzx9jlGdSBFLS5iEqgBcsM/LW/wET5TpGTvwD1ot19EbAiNlIS1EVFvMXKOfHE29/BNsPm506GAb51NHBITFkoPhbbtou/trQDUFstA9Me5arvsdy7BE917zpajZWzBBPW8DFdbNyuZzx5c7GCD9luQWqdRHz7jqNSp9AdkCRk7eSPmo2gquPYzX7TuIzWXmavvoLVIpIEogJSW/hvtY9daespRzHVs9qWJ9IXpYPlaDWEKjU4ltK/yT0Yh3MMOe0xbh9N7eXxPPHUK7a39j6bTlVzeZlxT98Gtas+T1GeJViT/KLMg/s8m/uYicHl0BETfCF+dgmzFHty9Pf+QwmsS8EYlzKSix0MDOPBQuj9EosyFPNz8rDnPXKsr0DIjE3za4ywc4UZoazrcLzQ7XNlPmOwMRm9PYbiBC7DedO3HKVS8HfEM1OqU84eWQullOpHcWSuHgkpn6KfJvOpSrkbJiDDWxDs6xEcJiDWmdr6OdhbnSg2GCmXQlIeO8oGhdXiqwlcVhyjNd3dKxWYbfDqeblF+vEJm5GjqpqZM7ZjgWxc7CnmJe4DlBZK4IVdL4IFgkK/cLZiObjyuvKcYivj/FcYw3OfA5GnnaonK2FN9tOs1UF+3OcKuOf6IfAMbbBTwnuZph4wPZmBdOmgI1FsJ4tj71ftkdJsVUP05Y5SNzwuep7fI4NCW8jT5xqeCMk2lFT0/1cXzcr18qZ/XJt1oXPm/46YhP2weVNz/IjOe5tZKm+U0nWG0hkByTxkQGhmGF3QI5JmtbYKRsfj5Qs9cV/rCynsvKd/IUyFLqlxvjKM4V6WArFE7e4v72k8oNISFDvb6X4eMHbyCnjz9lZTmANDiWz7ac6YNnkX3AoXhKp9vgFeQmIS9mPwsYNipLsdWx5m1AgagNBiLEfWGEfC5ao569CoZGnKQMz7qtMhPmLA7LFtA9LbLYZn28VEmLjMX/JOqTmy2TOnbjlBtdq/t7slNrZw6vpH7p2JPtUhRLovHzEa1fpX4qA6MsqPorkdMc1m/yUnRAxwG6Ha5i38gw2OB2yV4pKixtXrbnNHy8ND2KFhH3NPLsCpJKfuk4JvKxgj0ls7DMwlih5EmBQB7/JCOFNAdUV2FNQwYofOyUeoRrOpx+NQF6a2fsnVDtQA0sp8oyO8prlY2G58pTVdJq/Rs+9dWsJx+VMtdz8zU6XixIzXN30ZtMqOPpYc/pxZWgvCxd+ISJJmowYUTVkweDAKqedsuYcWUF4INpue5mLN6sOtlbnkGqS5YeVvWwHn29OP4cSEf19oXdYI66B2WHZZMz7kfjhWZF/uvDxWKikCo2x4CTecxYL8lfhPVYjZyuG4DGzWxGQq5Cff04+V7gTt9zhUvAvO8ROqfn4e0ePuFVyKjui42orjIez5VlCNrIyNyI1UdWp46apwYHib2VZU+2ZRx3WgBvmLdnncEftcAE+Si3NUoNikcBNQbBonzGzmo9tAbJ1DukmJQcCgseLv8KeUojKlH5wYwd6NG+bZIspO81quBfAdze/wGcaC/PUgaK9X7yvpLSYubhGBlsvtns2x811s2p1OVMtd09Hj9PfD7Osutscj+Q2QV0pCpwEA5eckNsDXtC5XX1so+3VFGv50fk46VytRp07dTHjFygWC/BHkOrg0RgLPkNTJ0iFbH8RJ7cBgxsHQmRfEPuYLvz3MKYtxowxTXfwcu7ELXd0TJt/Q8fVkzD46eRZgo4VhmEYN3M5jC8Plqej7vGRJx0B4/aqetnvf/D7ynA6v1HiL6fMa4G5oKmC3HFiAmW4ZMH/hPKM8WG7LWOpQkEzp+1mU1VD4G0ofOYjKOelVTcQI2TtISx6ICtOdSg38Xvs7EMxL7kBAxEjZ4oLUgqauaS978Hj5rpxLpWzli+3w/h6Kd+pugpuXCB/P/N5mEXG6aF3e/RIG2yvB8568OUDOkSC0OJY0JCfbHtZV6xwFZK3nEZlHT+D/i3mrt2Ev7CY01gJee6+A5k7ccsdHRD8Q5GapOq42vIapsuzhOnz38euY+dR7dUWoV/F2sPezMPizo2H2tVziA5WeoR47cN5baAF2Do2zn8Op0Rp9YN+ON/5QxEbxEttBUzp/P0qZJfzqQMRPJW/HitGOoCdDxQ7bO9/wGzW7QGUs05nP/LLlY6L4JBpHR+IbbZXV1KPetWKlXz8OmLHvIg57+zGobyzrEJlZlN4yUrIH5Fx2NEoIcZBjHL0aKu41f7BP2wKQsQwwhIc4B1XH59p6MwoyT+I9JQ5iN2itL25q1bmSXGW7Clv5hG74KAyA6PMq4M+vHXtyO1Bv3AKwkTsN8O0R137qGWFiNH5I6SZPVcf4q/UcutrxWurLBNv15dDOvXjEcy3TVkprLG9MKdCdCIGhsxm70dCz79HZQWy232vdXPdXC5njcsNb6ueNHfVsGDC//r5I1YktJ2PD5xTOomDxyLFrZEj7pfFB2+yUr5ZqahubFttjAXsezepYfRUPcsNe1UozN6O1CXzER8Xh2dZvImc/j7yxGifSMxMek5OZ12ea3HLHe0f/INk2zULIB+3cwDZY1J29+AwZ0O/nNtTrHQuBQRNaaPrDVw0fBnSYpWONEvBPqTYnFLLZhm2diFNdnaGIlHukWXF+8TfBrJdX7T7yyGeleVHGmtkOafBmxa9A4c0vG8xn22y7bNtuLluLpezxuUGTW3bcdQuk9sA3oMRntg27bsNstchRwxb0iH85VbcP0r/AmJj1d+lDcrigxY3WjlTZIG6RHXBW0MsYBWgpuoDYYlDRH+YuvLUpJKDWLLngqiA+OmHKWmMO3HLHe0f/BtqMQMx1cma6QNk+6GbzO8dh4mX6+DnmhxX7Ih5xxllKF9ABBY6ndcfAbq2+KZODJ+HjBXjIe4QbDmLD1Pt29mrsCNPGd4WELXY6cUtw1MWI4qXyroS5O+w7zDchzLR7u+PCWF8iGc1ynPUZxf7YeJNA7qB7H2+s1v7A9qbm+vmcjljy81XbqcRwPLf6QVDej3ac9Pb2o9sZSA6QiYtcxqg9dHygNcqVdiwZLsyzFE3DItacqfOoP+LtIx5WLp0K9LjrAeAtiiL7Y2PAnJy8OTXUbw8TOSfpeAINiipgnnHSSWOBIxCkrNYwCppSVF8w9ShOH+nqjkrArFxzgex6A33bzN34pY72j/45xyHuFjVOwix6XZXtvFf5ErNROZUpabrvk+RLO6L4w3DhJXISrO7LF9c+s8vEXdwVaB5M7bkyDHJbN7D6bb3L+e/PpVqzMBUMSarjVm/18YpCBGlsQQHkh3fd8Wcvh05YoBxICasyLS9XFzm54oJcoxyznZsuO8zqnBCXO2lRzBfF0sFTtkN40k3VbD//dj7/MtUoUz0B7Q/t9bNjXJm3qBa7pos29sKsAN+WNxbMGZOUYbjdZDs93Y3BuhMlhc2t0ngt1PYiIyU0WwruYAPc0z+TBnp4jcMcz/JhnHNbMSIg30jfZgsl5/8p3IBnKUG5eWNAdz9stje2NnNogwYUycjTLUv81s2ZGTIH1iqO48D9pUs83ZVLGDb3mZ+WR5kJa2u7HNs2WDNE39Er1mMpYuWw5i1EUkx6pE+fL6VSI9RCmaZ6Yj4q3AjbrnBpV/y4kM941JlckuwlT48lxVUufPwTguOj8ZgJQqmvCoERgVBV3bEdqios1/scpYuDU/KwIpJ7PPka2V5fOSH8pofrSuPrUNsylH52opfYr1VXmmnsJm3zgyT2QchBhd/yYt32CiJKurvxXKj7Di2JNteEHQf/Vikpi3DOHGKwPGOIGt+Kq8r8zYjcclBxx1s1vxjT+tMuzEmwe7KXf0yGP/CCjd/XvkF5sS+cX+zTzPbQHAyTZO/5OXOurlazjhxCwF5la+gLJdvHJ5SV3keZt2TMNz3S17KPWqUX/Ky3S+cpas1OQ0fvWS9ypezlh/5nSwFZ2EJH4YAlONQZDycLMI5/Qssr2fLe/pL1mU4KpcLWLm0z3Q3tlez+dNsGbPuW/bbhN/bh5ffahQXe8lKDF81sUEb10tcnMbyzeHYbhbIU9ciZRw/eCnE/DLvxWu2b2xIfMMmT4JmrMWalyLBL3pW2JYjzlL8GZLj1903pNz1uOWaDhjtwxjfQELqPjFOVckHZYX42PE9yQlIKGjbjqD89xIQn7wbeawqaBHbS2ZgnQVl7BRv/Zx4JxlYBeOCWCSs5rVI9XflHULHsTohDsdEb5mLxGfZP/hGtqDS9AV2vTMLz9pdCeqQ+XOkxMUjec9plLHvqRQQsYIyT9n6OQv8nLG04T2Ht2ywDgllqsuPd0B7v4o76+ZOOWO14QXPz8HqYyWo5oVGLtfbwgLIsfeREHtc6SjtSPnrEB+/HHtOlYtyzFdG5IWlHKf2LEd8YpXS1OUq80GW1zHi1iV5JjNbhthZlPXm5ZKtu7K/vKiUS0eZ7m5ZbFe1KI5PUL4by0Dreok4cGofktn3dnpRH4sFOSnxiEvm5YnFEZYi5md/62T+x7FKkX2eiJE+ccuxK+88KtXliD2zzhfvIPBzrsct17Si5k8I8SzWGq6LNf8ui/KlJTqm5k8IaXt6eTEYIS6g4E9IJxX20mBlqGF1lWfckoR0KhT8CfFUMWtx+LSjkTj8x0K2ipE0XKVpX6vvu0QItfkT4qFi07KwdIRqMGed7Wgfrq7sCJbEOb5rqHZRm39LUM2fEA+VtSAW09/ZjWMF5coIJDH6o3HkSMGh95FAgZ+4iGr+hBCiQVTzJ4QQDaLgTwghGkTBnxBCNIiCPyGEaBAFf0II0SAK/oQQokEU/AkhRIMo+BNCiAZR8CeEEA2i4E8IIRpEwZ8QQjSIgj8hhGgQBX9CCNEgCv6EEKJBFPwJIUSDKPgTQogGUfAnhBANouBPCCEaRMGfEEI0iII/IYRoEAV/QgjRIAr+hBCiQRT8CSFEgyj4E0KIBlHwJ4QQDaLgTwghGkTBnxBCNIiCPyGEaBAFf0II0aCHIiJG/yifE43p6xWKx3o8gV7dH4f3w71lKuns6u7ewPd3ruC725fwbf05mUqILQr+GuTVrQ8G9XoBP+kxWKaQrupft0tx+fuDqL93XaYQoqBmHw36ea/fUeDXCL6dB/v8Tr4ipBEFf435P95h6N0jUL4iWqDrHii2OyFqFPw1xtcrRD4jWkLbndij4K8xvR7uL58RLaHtTuxR8NeYHt108hnREtruxB4Ff0II0SAK/oQQokEU/AkhRIMo+BNCiAZR8CeEEA2i2ztoTKTvO/JZ+4h6bxR+N7S7fNWM2uv485RzyJMvu4rBiyIwJ/pR3PzbJSSnVsnUB+90zZvyGSEU/DWnvYO/7y/7wvCY7Qll2KwhGNr/FopWXUahTBNu16Ps1HXUyJddxeClw/GHqJ74oagUS5OuyNQHj4I/UaPgrzHtHfwdmfZfTyPypz/g9Pgz2C3TuroBv+yDm1971oGNgj9RozZ/QtrBPz0s8BNij2r+GuNxNf+JoVg9uw8sOUW42D8YI4f2RA+waT+6g7BZvXHzqwtITrkmJ7YaiEWfDYKhtgafTCvCGZmqNuD5JzBpoi8G9PfCo15K2u3aH1C0swi7Dt9SEqz69cOkxYMQwZb9KH9dfwdXi6pw0csfTw+tb/zebLrfzH4cYUN94Ocj601s2upLVdibVIqLSopqnf4bK9crSSIPHruOP2+uxdBZAQjqr8z/w9XrOLP5HA4UiJftimr+RI1q/sQjPDKUBf7+9Sjaexk5Od+iZF8lSljVufcgf0TIaRpM6YsBLKBXf13hMPADPTHy+X4w9OJ9ClXI2XwZJ/92HTdYaA+fF4qXwuVkXL/HMW/LEBbkvXDz4rc4+VExcvJu4PagAJZm13E91B+RTz2KO5drUJB9Gca9Vbjw/+6h99DH8dL6QfCVkznl5YPoeX3R45sqHPyoEkUXb6FH/z54emkoouQkhHQUCv7EI/RmoXnHfxRi184K/HX9ZRbUq3Dmcj3g2xuRE+VEQk+8GNWbnR3U4uJHzn6g5Bb2vnoCi6d9hW2rL+GvhyuwN/Uc3l79LVtKTxgm9pPTAVGLDQjyuYOS7Wfw9iIT9rKDzl/XF2HNNBNOssBuI7cIyeNPYmWSCbs+qMCXOy9h26uF+PKbe+jxC188LSdzyostZ3U+1qcWI3dfMXYsyseOv7GzEJ8+iHxFTkNIB6HgTzzC1aILjc0mUuHe66hGdxjGDJQpTD8WrH8O3L54DXvtW4OaU3AdV2uB7l6yHQiDEP4Eq91/cw27/2LXFIQaXP3OLvg7dAsHLvN5u+ERJcG52lsos2veufiXWraO7OD308YDEiEdgYI/8VxfX8bFb4AeP++LZ2XS4Fl90B/1KGG1+aYMmBKCN/Y9jU1HrI9ReOu9PrYBeowPfNlx4Orl4pZ1zvbrhxfXP4V1DZ/5NNbti8BM2X7vkq/v4A7703hAIqRjUPAnHuwWci+xqrqXD4b+nr/uh2d/2ZNF6+vIzRUTODYxFPNm9YVvfS2K9hbjT6su4GD2ddQ81geP+8hpVLp7sc9sVh9MW/EERv2iG24UVeEg+8w/ba5A4aV7CHqiJfMT4lko+BOPVvPBNZTVd4MhfDDwrD8e9wWufHUZpfJ9R0aO8MGjqMXphV9hx85KFJ64htwPTNj8ShlK2LGkwYla1NQDfo8PbL6zFv4w/JQF/q9K8XbSJeSyzyw8fBm7U75Cct4PchpCOg8K/sTDVaDom3vAz/tg3vN90Lv+Bgo/sG+fb6F+3dBDPlVcRsGlO+yz+2HaRPvauw/8erVs9xjgRbsR6Xyo1BKPl3uYD9P0QZBocqlEUy0+3Jc5N8T0o7ZE4D8XDcLIKcGYmforrPjQgAF2zT556/jZQHcEzY7AW+tD8OKUAPxm0VAs2R2Gkaym36gMF9lBqPevglXThWDef43CohHUXk86Hwr+xPPlVuGK6JGtx5WcFtwoLbcIWzdfw1X0xJDogYibFYChg4CS7ZdRpm724a5dwea5xSj45g4e+UVfjJoVjGg+lPTrUhzhZwUNbuHAO5fw30X1jdNFszORq1XYkefimQghDxBd4asxD+IKX/fJK3q/u4ZN/3Ghyfb+tqTcoVR1hW8nR1f4EjWq+ROP5/tqPxi8mu/obVu+COrfHaitR5lMIaQroZq/xnSmmn/E8wPRo39vPP18X/RHe9373xcz/xSC8F63UFJUi6uXruPmT1ngH+oLQ3/gao4JK9d3jVu0Uc2fqFHNn3isoImDEPciD/w/oGDnpXb60Zca5O69hpLvumPAr/rJtvy+GNCrHiVZl7C1iwR+QuxRzV9jOmebP2kLVPMnalTzJ4QQDaLgTwghGkTBnxBCNIiCv8bcvmeRz4iW0HYn9ij4a8z3d6/KZ0RLaLsTexT8NebaLcc/fEi6NtruxB4Ff4357vYlXL/dcdfJkgevpu6S2O6EqFHw16CKHw7j3o/qm5aRruruj/Uov3lIviKkEV3kpWF9vULxWI8n0Kv74/B+uLdMJZ1d3d0b+P7OFVHb/7b+nEwlxBYFf0II0SBq9iGEEA2i4E8IIRpEwZ8QQjSIgj8hhGgQBX9CCNEgCv6EEKJBFPwJIUSDKPgTQogGUfAnhBANouBPCCEaRMGfEEI0iII/IYRoDvD/ASzBaDwt9618AAAAAElFTkSuQmCC" alt="image" iscopyblocked="false">

**Comment by BrianHotopp** [comment]
Same

**Comment by muayyad-alsadi** [comment]
please file an issue [here](https://github.com/containers/podman-desktop)
because they have built-in support for compose not this project.
