### ISSUE TITLE
Help needed: -- on running podman-compose getting this error -- AttributeError: module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by joshi-mohit** [containers/podman-compose#862]
**Describe the bug**
I get the error on running a compose file

Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==1.0.7', 'console_scripts', 'podman-compose')()
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 3246, in main
    asyncio.run(async_main())
AttributeError: module 'asyncio' has no attribute 'run'

version: '3.3'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    expose:
      - 2181
    volumes:
      - /data/zookeeper_data:/bitnami:z
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      ingestion:
        aliases:
          - zookeeper
    hostname: zookeeper
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: journald
      options:
        tag: docker-zookeeper
.....

[azureuser@MJ-RedHat-SaaS-PodMan pre-requisites]$ podman --version
podman version 4.2.0

[azureuser@MJ-RedHat-SaaS-PodMan pre-requisites]$ python3 --version
Python 3.6.8

installed podman-compose 
 sudo pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz

**To Reproduce**

even running 
podman-compose --version is returing same error

**Expected behavior**
supposed to run

**Actual behavior**
What is the behavior you actually got and that should not happen.

**Output**

```
$ podman-compose version
using podman version: 3.4.0
podman-compose version  0.1.7dev
podman --version 
podman version 3.4.0

$ podman-compose up
...

```

**Environment:**
 - OS: Linux / WSL / Mac
 - podman version: 
 - podman compose version: (git hex)

**Additional context**

**Comment by joshi-mohit** [comment]
Possibly becasue of python3 pointing to python3.6 --> will recheck and reopen if needed

**Comment by jsayer101** [comment]
Hi, got the same error here on RHEL8X
Is python 3.6.8 not supported anymore ? We got VMs that run Python 3.0.6 and Podman Compose 1.0.6 without any problems.
I tried to follow the same installation that we did on our older VMs and we got this error.
