### ISSUE TITLE
pytest unit test are currently failing

### ISSUE THREAD

**Issue by MikeKlem** [containers/podman-compose#868]
I've started getting GitLab CI running over here:
https://gitlab.com/mikeklem/python-podman-compose/

_Originally posted by @MikeKlem in https://github.com/containers/podman-compose/issues/437#issuecomment-1983691694_

**Comment by p12tic** [comment]
Pytest unit tests have been fixed as of today.

**Comment by MikeKlem** [comment]
I see that tests have been added, but they're not all currently passing on the dockerhub alpine image:

https://gitlab.com/mikeklem/python-podman-compose/-/jobs/6433511211

**Comment by MikeKlem** [comment]
All failed tests:
https://gitlab.com/mikeklem/python-podman-compose/-/pipelines/1220197801/test_report#
