### ISSUE TITLE
Multi-line environment files are not correctly processed

### ISSUE THREAD

**Issue by hedayat** [containers/podman-compose#908]
**Describe the bug**
For environment files, podman-compose passes them to `podman` with its `--env-file` option. However, `podman/docker` and `docker-compose` process environment files differently: `podman/docker` doesn't support multi-line environment files, while docker compose supports them (https://github.com/containers/podman/issues/18724#issuecomment-1757162444). 

**Expected behavior**
Properly support multi-line env files

**Actual behavior**
Just passes env-files to podman, which doesn't support multi-line env vars, as apparently docker also doesn't support them too.

** Implementation **
I found that it can be easily implemented (parse env file with dotenv, and pass variables to podman), and I'll open a PR to fix it too.

**Comment by mokibit** [comment]
Fixed in https://github.com/containers/podman-compose/pull/949.
