### ISSUE TITLE
bump podman-compose version to 1.1.1 or 1.2.0

### ISSUE THREAD

**Issue by x3ccd4828** [containers/podman-compose#927]
**Describe the bug**
v1.1.0 release is has a major problem when it can't register the systemd unit. However that is fixed in main branch already in this commit (https://github.com/containers/podman-compose/commit/d31a8b124dba896fc683f755fa5895feee334059). 

Would it be possible to bump the version such that fedora iot/silverblue can pick up the fix without having to install it from source?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Actual behavior**
N/A

**Output**
N/A

**Environment:**
N/A

**Additional context**

**Comment by p12tic** [comment]
podman-compose 1.2.0 has been released: https://github.com/containers/podman-compose/releases/tag/v1.2.0
