### ISSUE TITLE
Upgrade `podman-compose` to the latest version in pip and Homebrew

### ISSUE THREAD

**Issue by kijart** [containers/podman-compose#934]
Hello! I'm interested in using some of the latest features that were added in `v1.1.0`. However, I've noticed that the latest stable version is not available in either Homebrew or pip.

```sh
❯ pip3 show podman-compose
Name: podman-compose
Version: 1.0.6
Summary: A script to run docker-compose.yml using podman
Home-page: https://github.com/containers/podman-compose
Author: Muayyad Alsadi
Author-email: alsadi@gmail.com
License: GPL-2.0-only
Location: /Users/***/.pyenv/versions/3.10.14/lib/python3.10/site-packages
Requires: python-dotenv, pyyaml
Required-by:

❯ brew info podman-compose
==> podman-compose: stable 1.0.6 (bottled)
Alternative to docker-compose using podman
https://github.com/containers/podman-compose
Installed
/opt/homebrew/Cellar/podman-compose/1.0.6 (88 files, 1MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-04-02 at 15:59:58
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/podman-compose.rb
License: GPL-2.0-only
==> Dependencies
Required: libyaml ✔, podman ✔, python@3.12 ✔
==> Analytics
install: 810 (30 days), 2,447 (90 days), 9,458 (365 days)
install-on-request: 810 (30 days), 2,447 (90 days), 9,457 (365 days)
build-error: 0 (30 days)
```

What is the reason for this, and what is the process to get it updated?

**Comment by kijart** [comment]
I just checked and noticed that the latest version considered `latest` in the repository is also not available in `pip`.
I update the issue title and description to cover both cases.

**Comment by SohanTirpude** [comment]
One quick update. In pip the version got updated now to `1.1.0` but still in Ubuntu, I am seeing the older version i.e. `1.0.6`.

**Comment by p12tic** [comment]
Thanks for the bug report. New versions of podman compose have been uploaded to pip. As for Homebrew and Ubuntu, we have no control on when podman-compose will be upgraded there.

I'm closing the bug report, please reopen if you have any further questions.
