### ISSUE TITLE
podman-compose 1.1.0 no longer loads env file in the same directory with compose.yaml when using `-f`

### ISSUE THREAD

**Issue by Genzer** [containers/podman-compose#937]
**Describe the bug**

`podman-compose` 1.1.0 does not load env files (e.g `.env`) when running `podman-compose` command in a different working directory (from `compose.yaml`).

**To Reproduce**

The bug can be reproduced by the following set up:

```bash
# Create a directory containing compose.yaml and .env
mkdir project-demo

# Create the compose.yaml
cat <<'EOF' >project-demo/compose.yaml
# This file was copied from podman-compose/tests/env-file-tests
services:
  app:
    image: busybox
    command: ["/bin/busybox", "sh", "-c", "env | grep ZZ"]
    tmpfs:
      - /run
      - /tmp
    environment:
      ZZVAR1: $ZZVAR1
EOF

# Create the .env
cat <<'EOF' >project-demo/.env
ZZVAR1=podman-rocks-123
EOF
```

Run the following command:

```bash
podman-compose -f project-demo/compose.yaml config | grep ZZVAR1
```

**Expected behavior**

`podman-compose` loads the `.env` located in the same directory with `compose.yaml`.

```bash
$ podman-compose -f project-demo/compose.yaml config | grep ZZVAR1
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 5.0.2
      ZZVAR1: podman-rocks-123
```

**Actual behavior**

No envfile is loaded even if `env_file: './.env'` is specified in the `compose.yaml`.

```bash
$ podman-compose -f project-demo/compose.yaml config | grep ZZVAR1
      ZZVAR1: ''
```

**Output**

```
$ podman-compose version
podman-compose version
podman-compose version 1.1.0
podman version 5.0.2
```

**Environment:**
 - OS: Linux and Mac
 - podman version: 5.0.2
 - podman compose version: 1.1.0 (2681566580b4eaadfc5e6000ad19e49e56006e2b)

**Additional context**

I verified that this bug was not in 1.0.6. The behavior from 1.0.6 seemed consistent with `docker compose`.

The bug MAY come from https://github.com/containers/podman-compose/commit/59a59c1a3aacd8ba29c1bbd201bf388a3090a487#diff-afacb71932eed96cfb44057ef839da783c130d3a0062376a797a5f19f258292e.

**Comment by jrunestone** [comment]
Can confirm!
