### ISSUE TITLE
Update the pypi version to 1.1.0 because the 1.0.6 version does not support the Compose specification for env_file

### ISSUE THREAD

**Issue by andrew-ma** [containers/podman-compose#948]
**To Reproduce**
Install the pypi version
```shell
python3 -m pip install --user podman-compose
```

**Expected behavior**
- env_file of the Compose specification should work according to https://github.com/compose-spec/compose-spec/blob/master/spec.md#env_file

```
$ podman-compose version
podman-compose version 1.1.0
podman version 4.6.1

```

**Environment:**
 - OS: WSL
 - podman version: 4.6.1
 - podman compose version: previously 1.0.6, now 1.1.0

**Comment by manics** [comment]
There's no automated GitHub workflow to publish the PyPI package, is it handled manually?

**Comment by luckylinux** [comment]
Workaround:
```
# (Optional) Create a Dedicated Python venv
(podman-compose) podman@HOST:~$ python -m venv ~/podman-compose
(podman-compose) podman@HOST:~$ source ~/podman-compose/bin/activate

# Install Podman Compose
(podman-compose) podman@HOST:~$ pip install git+https://github.com/containers/podman-compose.git@v1.1.0

# Print Version
(podman-compose) podman@HOST:~$ podman-compose --version
podman-compose version 1.1.0
podman version 4.9.4
```

On a Separate Note, [this](https://github.com/containers/podman-compose?tab=readme-ov-file#manual) DOES NOT work:
```
# Create User ~/.local/bin Folder if not existing yet
podman@HOST:~$ mkdir -p ~/.local/bin

# Follow Manual Setup Instructions
podman@HOST:~$ curl -o ~/.local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/main/podman_compose.py
podman@HOST:~$ chmod +x ~/.local/bin/podman-compose

# Test
/usr/local/bin/podman-compose --version
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 5, in <module>
    from podman_compose import main
ModuleNotFoundError: No module named 'podman_compose'
```

Not sure if it's a `podman-compose` vs `podman_compose` (dash vs underscore) issue that is NOT correctly handled by Python or `podman-compose`.

**Comment by luckylinux** [comment]
@andrew-ma: are you sure you need `podman-compose` Version 1.1.0 to get the `env_file` Directive working ? I used `env_file` several Times with `podman-compose` Version 1.0.6 without Issues ...

**Comment by andrew-ma** [comment]
Ok yeah didn’t know it was working with 1.0.6. If so that would be great
then.  Thanks for your response!

**Comment by luckylinux** [comment]
@andrew-ma: well I thought it was ... and it is ... but only if the file is named `.env`:
```YAML
env_file:
  - .env
```

I was trying to get Nautobot Example running with Podman (long story ... not working yet) and there they used 2 `.env` files (`local.env` and `creds.env` and those were NOT recognized).

Similarly when I was trying to feed Caddy some Environment Variables: `caddy.env` was getting ignored, `.env` worked correctly).

So I think you are right, if the file is NOT `.env` (or maybe also other files are supported ? `.env.xxx` or `.xxx.env` ???).

**Comment by p12tic** [comment]
podman-compose 1.1.0 has been released to pypi https://pypi.org/project/podman-compose/1.1.0/#description
