### ISSUE TITLE
cap_add and cap_drop appear to not be supported

### ISSUE THREAD

**Issue by JimTheCactus** [containers/podman-compose#95]
In working with an existing docker-compose file, I found that podman-compose seems to silently ignore both cap_add and cap_drop. (https://docs.docker.com/compose/compose-file/compose-file-v2/#cap_add-cap_drop). Podman itself supports these, and using `podman run` to work around it works, but it would be nice if podman-compose supported it, or at least generated a warning or error when the unsupported function was encountered.

I know we're still early in, so I just wanted to make sure this in on the radar.

**Comment by jhollowayj** [comment]
Looks like this was added in https://github.com/containers/podman-compose/commit/e8147e350b0441bdbcc82e5b4fd4f09d6cb44ecf on `Apr 22, 2020`.  I think this issue can be closed.

**Comment by JimTheCactus** [comment]
Looks like it. Thanks for pinging me and I'll close this out!
