### ISSUE TITLE
podman-compose rebuilds an image that is up-to-date, pressumably for the environment set in docker-compose.yml

### ISSUE THREAD

**Issue by flixman** [containers/podman-compose#969]
**Describe the bug**
In my docker-compose.yml file I am setting some environment on an image for which I have also a section to build. Although the image is just built (through podman build), podman-compose is re-building it. I observe that, in the output of this build, there is an ENV statement with the variables I am setting on the environment for the service in the docker-compose.yml. Is this the reason for the rebuild? Is this expected behavior? If not, I will file a proper issue with the output of the commands and so.

**Comment by p12tic** [comment]
@flixman The expected behavior is however docker-compose behaves in equivalent scenario.
