### ISSUE TITLE
k8s.gcr.io in China

### ISSUE THREAD

**Issue by Hill-98** [containers/podman-compose#99]
k8s.gcr.io In China, due to the firewall barrier, k8s.gcr.io can not access the normal, making it impossible to obtain `k8s.gcr.io/pause`.
I think you can add an option to use `docker.io/mirrorgooglecontainers/pause` the mirror, and pass the `--infra-image` to the podman.

**Comment by athrunsun** [comment]
You can download `pause` image from a mirror like [`gcr.azk8s.cn`](https://mirror.azure.cn/help/gcr-proxy-cache.html) before executing `podman-compose`:

```sh
podman pull gcr.azk8s.cn/google_containers/pause
```

**Comment by Hill-98** [comment]
> You can download `pause` image from a mirror like [`gcr.azk8s.cn`](https://mirror.azure.cn/help/gcr-proxy-cache.html) before executing `podman-compose`:
> 
> ```shell
> podman pull gcr.azk8s.cn/google_containers/pause
> ```
This does not solve the problem of podman-compose because podman pod create has the following settings by default.
`--infra-image string     The image of the infra container to associate with the pod (default "k8s.gcr.io/pause:3.1")`
podman-compose must pass `--infra-image gcr.azk8s.cn / google_containers / pause`

**Comment by jecnua** [comment]
Also be careful with gcr.azk8s.cn because if you are not running in azure they may block your ip (it happened to us). It's open to everybody but is for Azure so they may decide to block you if they see too many requests (or not too many, we were just doing a rolling upgrade).

**Comment by muayyad-alsadi** [comment]
I guess this should be customized in `/usr/share/containers/libpod.conf` and `/etc/containers/libpod.conf`
it reads something like this

```
# Default infra (pause) image name for pod infra containers
infra_image = "k8s.gcr.io/pause:3.1"
```

**Comment by Hill-98** [comment]
> I guess this should be customized in `/usr/share/containers/libpod.conf` and `/etc/containers/libpod.conf`
> it reads something like this
> 
> ```
> # Default infra (pause) image name for pod infra containers
> infra_image = "k8s.gcr.io/pause:3.1"
> ```

thanks for your reminder

**Comment by panda2134** [comment]
This problem occurs again with podman installed from ArchLinux official repo.

`podman-compose` seems to be not obeying the `infra_image` config in `/etc/containers/containers.conf`. I specified an alternative address for `pause` there, but podman-compose still tries to download from GCR.

**Comment by muayyad-alsadi** [comment]
@panda2134  please try podman-compose branch 1.x

**Comment by panda2134** [comment]
> @panda2134 please try podman-compose branch 1.x

Thanks. It works now.
