### ISSUE TITLE
Release version 1.2.0 to EPEL 8 / EPEL 9

### ISSUE THREAD

**Issue by martinsuchan** [containers/podman-compose#996]
Could you please release new version of podman-compose 1.2 to EPEL 8 / EPEL 9 upstream?
https://packages.fedoraproject.org/pkgs/podman-compose/podman-compose/

We use this channel as a source for our Docker packages and we're currently stuck with the latest version 1.0.6.
I can see that version 1.2.0 is already in testing for channel Fedora 39 and 40.
Thanks!

**Comment by p12tic** [comment]
Thanks for bug report, but this repository does not have access to adjust versions included into fedora. Perhaps https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&version=rawhide&component=podman-compose is a better avenue?

According to https://packages.fedoraproject.org/pkgs/podman-compose/podman-compose/ the new versions are already in the process of being released.
